using System.Text.Json.Serialization;
using Seqeron.Mcp.Analysis.Tools;

namespace Seqeron.Mcp.Analysis;

[JsonSourceGenerationOptions(WriteIndented = false)]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(int[]))]
[JsonSerializable(typeof(double[]))]
[JsonSerializable(typeof(Dictionary<string, int>))]
[JsonSerializable(typeof(Dictionary<int, int>))]
[JsonSerializable(typeof(Dictionary<string, double>))]
[JsonSerializable(typeof(Dictionary<string, int[]>))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(double[][]))]
[JsonSerializable(typeof(string[][]))]
[JsonSerializable(typeof(char))]

// KmerAnalyzer
[JsonSerializable(typeof(KmerCountsResult))]
[JsonSerializable(typeof(KmerSpectrumResult))]
[JsonSerializable(typeof(KmerListResult))]
[JsonSerializable(typeof(KmerFrequenciesResult))]
[JsonSerializable(typeof(KmerDistanceResult))]
[JsonSerializable(typeof(KmerCountItem))]
[JsonSerializable(typeof(KmerCountItem[]))]
[JsonSerializable(typeof(KmersWithMinCountResult))]
[JsonSerializable(typeof(KmerPositionsResult))]
[JsonSerializable(typeof(AnalyzeKmersResult))]

// SequenceStatistics
[JsonSerializable(typeof(DoubleProfileResult))]
[JsonSerializable(typeof(DinucleotideFrequenciesResult))]
[JsonSerializable(typeof(DinucleotideRatiosResult))]
[JsonSerializable(typeof(CodonFrequenciesResult))]
[JsonSerializable(typeof(ChouFasmanItem))]
[JsonSerializable(typeof(ChouFasmanItem[]))]
[JsonSerializable(typeof(PredictChouFasmanResult))]

// GenomicAnalyzer
[JsonSerializable(typeof(RepeatItem))]
[JsonSerializable(typeof(RepeatItem[]))]
[JsonSerializable(typeof(FindRepeatsResult))]
[JsonSerializable(typeof(TandemRepeatItem))]
[JsonSerializable(typeof(TandemRepeatItem[]))]
[JsonSerializable(typeof(FindTandemRepeatsResult))]
[JsonSerializable(typeof(MotifPositionsResult))]
[JsonSerializable(typeof(FindKnownMotifsResult))]
[JsonSerializable(typeof(CommonRegionItem))]
[JsonSerializable(typeof(CommonRegionItem[]))]
[JsonSerializable(typeof(FindCommonRegionsResult))]
[JsonSerializable(typeof(OrfItem))]
[JsonSerializable(typeof(OrfItem[]))]
[JsonSerializable(typeof(FindOpenReadingFramesResult))]

// RepeatFinder
[JsonSerializable(typeof(MicrosatelliteItem))]
[JsonSerializable(typeof(MicrosatelliteItem[]))]
[JsonSerializable(typeof(FindMicrosatellitesResult))]
[JsonSerializable(typeof(InvertedRepeatItem))]
[JsonSerializable(typeof(InvertedRepeatItem[]))]
[JsonSerializable(typeof(FindInvertedRepeatsResult))]
[JsonSerializable(typeof(DirectRepeatItem))]
[JsonSerializable(typeof(DirectRepeatItem[]))]
[JsonSerializable(typeof(FindDirectRepeatsResult))]
[JsonSerializable(typeof(PalindromeItem))]
[JsonSerializable(typeof(PalindromeItem[]))]
[JsonSerializable(typeof(FindPalindromesResult))]
[JsonSerializable(typeof(TandemRepeatSummaryResult))]

// MotifFinder
[JsonSerializable(typeof(MotifMatchItem))]
[JsonSerializable(typeof(MotifMatchItem[]))]
[JsonSerializable(typeof(FindDegenerateMotifResult))]
[JsonSerializable(typeof(PwmInput))]
[JsonSerializable(typeof(PwmResult))]
[JsonSerializable(typeof(ScanWithPwmResult))]
[JsonSerializable(typeof(ConsensusResult))]
[JsonSerializable(typeof(DiscoveredMotifItem))]
[JsonSerializable(typeof(DiscoveredMotifItem[]))]
[JsonSerializable(typeof(DiscoverMotifsResult))]
[JsonSerializable(typeof(SharedMotifItem))]
[JsonSerializable(typeof(SharedMotifItem[]))]
[JsonSerializable(typeof(FindSharedMotifsResult))]
[JsonSerializable(typeof(RegulatoryElementItem))]
[JsonSerializable(typeof(RegulatoryElementItem[]))]
[JsonSerializable(typeof(FindRegulatoryElementsResult))]

// ProteinMotifFinder
[JsonSerializable(typeof(ProteinMotifMatchItem))]
[JsonSerializable(typeof(ProteinMotifMatchItem[]))]
[JsonSerializable(typeof(FindProteinMotifsResult))]
[JsonSerializable(typeof(PrositeRegexResult))]
[JsonSerializable(typeof(SignalPeptideResult))]
[JsonSerializable(typeof(RegionScoreItem))]
[JsonSerializable(typeof(RegionScoreItem[]))]
[JsonSerializable(typeof(PredictTransmembraneHelicesResult))]
[JsonSerializable(typeof(PredictCoiledCoilsResult))]
[JsonSerializable(typeof(ProteinLowComplexityItem))]
[JsonSerializable(typeof(ProteinLowComplexityItem[]))]
[JsonSerializable(typeof(FindProteinLowComplexityRegionsResult))]
[JsonSerializable(typeof(ProteinDomainItem))]
[JsonSerializable(typeof(ProteinDomainItem[]))]
[JsonSerializable(typeof(FindProteinDomainsResult))]

// SequenceComplexity
[JsonSerializable(typeof(ComplexityPointItem))]
[JsonSerializable(typeof(ComplexityPointItem[]))]
[JsonSerializable(typeof(WindowedComplexityResult))]
[JsonSerializable(typeof(DnaLowComplexityItem))]
[JsonSerializable(typeof(DnaLowComplexityItem[]))]
[JsonSerializable(typeof(FindLowComplexityRegionsResult))]
[JsonSerializable(typeof(DustScoreResult))]
[JsonSerializable(typeof(MaskLowComplexityResult))]
[JsonSerializable(typeof(CompressionRatioResult))]

// ComparativeGenomics
[JsonSerializable(typeof(GeneInput))]
[JsonSerializable(typeof(GeneInput[]))]
[JsonSerializable(typeof(GeneInput[][]))]
[JsonSerializable(typeof(SyntenicBlockItem))]
[JsonSerializable(typeof(SyntenicBlockItem[]))]
[JsonSerializable(typeof(FindSyntenicBlocksResult))]
[JsonSerializable(typeof(OrthologPairItem))]
[JsonSerializable(typeof(OrthologPairItem[]))]
[JsonSerializable(typeof(FindOrthologsResult))]
[JsonSerializable(typeof(FindReciprocalBestHitsResult))]
[JsonSerializable(typeof(RearrangementEventItem))]
[JsonSerializable(typeof(RearrangementEventItem[]))]
[JsonSerializable(typeof(DetectRearrangementsResult))]
[JsonSerializable(typeof(CompareGenomesResult))]
[JsonSerializable(typeof(ReversalDistanceResult))]
[JsonSerializable(typeof(FindConservedClustersResult))]
[JsonSerializable(typeof(AniResult))]
[JsonSerializable(typeof(DotPlotPoint))]
[JsonSerializable(typeof(DotPlotPoint[]))]
[JsonSerializable(typeof(GenerateDotPlotResult))]

// DisorderPredictor
[JsonSerializable(typeof(DisorderResiduePredictionItem))]
[JsonSerializable(typeof(DisorderResiduePredictionItem[]))]
[JsonSerializable(typeof(DisorderRegionItem))]
[JsonSerializable(typeof(DisorderRegionItem[]))]
[JsonSerializable(typeof(PredictDisorderResult))]
[JsonSerializable(typeof(SegRegionItem))]
[JsonSerializable(typeof(SegRegionItem[]))]
[JsonSerializable(typeof(PredictLowComplexitySegResult))]
[JsonSerializable(typeof(MorfItem))]
[JsonSerializable(typeof(MorfItem[]))]
[JsonSerializable(typeof(PredictMorfsResult))]
[JsonSerializable(typeof(DisorderPropensityResult))]
[JsonSerializable(typeof(IsDisorderPromotingResult))]

// GcSkewCalculator
[JsonSerializable(typeof(GcSkewResult))]
[JsonSerializable(typeof(AtSkewResult))]
[JsonSerializable(typeof(GcSkewPointItem))]
[JsonSerializable(typeof(GcSkewPointItem[]))]
[JsonSerializable(typeof(WindowedGcSkewResult))]
[JsonSerializable(typeof(CumulativeGcSkewPointItem))]
[JsonSerializable(typeof(CumulativeGcSkewPointItem[]))]
[JsonSerializable(typeof(CumulativeGcSkewResult))]
[JsonSerializable(typeof(GcContentPointItem))]
[JsonSerializable(typeof(GcContentPointItem[]))]
[JsonSerializable(typeof(PredictReplicationOriginResult))]
[JsonSerializable(typeof(AnalyzeGcContentResult))]

// RnaSecondaryStructure
[JsonSerializable(typeof(BasePairItem))]
[JsonSerializable(typeof(BasePairItem[]))]
[JsonSerializable(typeof(BasePairCoord))]
[JsonSerializable(typeof(BasePairCoord[]))]
[JsonSerializable(typeof(StemItem))]
[JsonSerializable(typeof(LoopItem))]
[JsonSerializable(typeof(StemLoopItem))]
[JsonSerializable(typeof(StemLoopItem[]))]
[JsonSerializable(typeof(PseudoknotItem))]
[JsonSerializable(typeof(PseudoknotItem[]))]
[JsonSerializable(typeof(CanPairResult))]
[JsonSerializable(typeof(BasePairTypeResult))]
[JsonSerializable(typeof(RnaComplementBaseResult))]
[JsonSerializable(typeof(FindStemLoopsResult))]
[JsonSerializable(typeof(StemEnergyResult))]
[JsonSerializable(typeof(TerminalMismatchEnergyResult))]
[JsonSerializable(typeof(DanglingEndEnergyResult))]
[JsonSerializable(typeof(HairpinLoopEnergyResult))]
[JsonSerializable(typeof(InternalLoopEnergyResult))]
[JsonSerializable(typeof(BulgeLoopEnergyResult))]
[JsonSerializable(typeof(MultibranchLoopEnergyResult))]
[JsonSerializable(typeof(FlushCoaxialStackingResult))]
[JsonSerializable(typeof(MismatchCoaxialStackingResult))]
[JsonSerializable(typeof(MinimumFreeEnergyResult))]
[JsonSerializable(typeof(PredictRnaStructureResult))]
[JsonSerializable(typeof(DetectPseudoknotsResult))]
[JsonSerializable(typeof(ParseDotBracketResult))]
[JsonSerializable(typeof(ValidateDotBracketResult))]
[JsonSerializable(typeof(FindRnaInvertedRepeatsItem))]
[JsonSerializable(typeof(FindRnaInvertedRepeatsItem[]))]
[JsonSerializable(typeof(FindRnaInvertedRepeatsResult))]
public partial class AppJsonContext : JsonSerializerContext
{
}
