// KMER-DIST-001 (audit round 2, WP7) — Mash bottom-s MinHash sketches (MurmurHash3_x64_128, seed 42, 32-bit hashes
// for k ≤ 16), sketch comparison (x/s, Jaccard estimate, Mash distance, binomial p-value) and the exact containment
// index C(A, B) = |K(A) ∩ K(B)| / |K(A)|.
// Evidence: docs/Evidence/KMER-DIST-001-Evidence.md; TestSpecs: KMER-DIST-001.md §4.7; algorithm doc §7.6.
// Sources: Ondov et al. 2016 (Genome Biol 17:132); Mash v2.3 src/mash/Sketch.cpp (addMinHashes, use64 = 4^k > 2^32,
//          sketchFile: records shorter than k skipped, length = Σ record lengths), hash.cpp (h1 / low 32 bits),
//          MinHashHeap.cpp (non-redundant bottom-s), CommandDistance.cpp (compareSketches, pValue =
//          gsl_cdf_binomial_Q(x − 1, r, denom)), MurmurHash3.cpp; Koslicki & Zabeti 2019 (Appl Math Comput 354:206).
// Reference values (executed):
//   - the Mash 2.3 binary (`mash dist -k K -s S [-n] ref.fa qry.fa`, `mash info -d`), printed with C++ default
//     precision (6 significant digits) — compared here as strings after formatting with "G6";
//   - sourmash 4.9.4 (MinHash(n=1000, ksize=21) = the Mash hash set; MinHash(scaled=1).contained_by / jaccard);
//   - mmh3 5.x (mmh3.hash64(key, 42, signed=False)) for MurmurHash3_x64_128.
// The sequences are generated by the 64-bit LCG below; the same generator in Python (gen.py, Evidence) wrote the
// FASTA files given to Mash and sourmash.

using System.Globalization;
using System.Text;

namespace Seqeron.Genomics.Tests.Unit.Analysis;

[TestFixture]
public class KmerAnalyzer_MinHashContainment_Tests
{
    #region Deterministic sequences (LCG, identical to gen.py)

    private sealed class Lcg(ulong seed)
    {
        private ulong _x = seed;
        public ulong Next()
        {
            _x = unchecked(_x * 6364136223846793005UL + 1442695040888963407UL);
            return _x >> 33;
        }
    }

    private static string Dna(int n, ulong seed)
    {
        var g = new Lcg(seed);
        var sb = new StringBuilder(n);
        for (int i = 0; i < n; i++)
            sb.Append("ACGT"[(int)((g.Next() >> 29) & 3)]);
        return sb.ToString();
    }

    private static string Mutate(string seq, int perMille, ulong seed)
    {
        var g = new Lcg(seed);
        var sb = new StringBuilder(seq.Length);
        foreach (char c in seq)
        {
            if (g.Next() % 1000 < (ulong)perMille)
                sb.Append("ACGT"[("ACGT".IndexOf(c) + 1 + (int)(g.Next() % 3)) % 4]);
            else
                sb.Append(c);
        }
        return sb.ToString();
    }

    private static readonly string A = Dna(10000, 1);
    private static readonly string B = Mutate(A, 10, 2);   // ~1 % substitutions (near-identical)
    private static readonly string C = Mutate(A, 50, 3);   // ~5 % substitutions
    private static readonly string D = Dna(10000, 4);      // unrelated
    private static readonly string E = Lower5kWithN();     // A[2000..7000) lower-case + "NNNNN" (contained in A)
    private static readonly string[] AA2 = [A[..6000], A[6000..]]; // A split into two FASTA records

    private static string Lower5kWithN()
    {
        var e = A[2000..7000].ToLowerInvariant();
        return e[..1000] + "NNNNN" + e[1000..];
    }

    private static IEnumerable<string> Records(string name) => name switch
    {
        "A" => [A], "B" => [B], "C" => [C], "D" => [D], "E" => [E], "AA2" => AA2,
        _ => throw new ArgumentException(name),
    };

    #endregion

    [Test]
    public void Generator_MatchesPythonFastaPrefixes()
    {
        Assert.Multiple(() =>
        {
            Assert.That(A[..30], Is.EqualTo("CGGCTGGATAGGTCAGCGGATTGGCTGATT"));
            Assert.That(B[..30], Is.EqualTo("CGGCTGGATTGGTCAGCGGATTGGCTGATT"));
            Assert.That(D[..30], Is.EqualTo("CGTCACTATCAATTACACTGCGGTATTTGG"));
            Assert.That(E, Has.Length.EqualTo(5005));
        });
    }

    #region MurmurHash3_x64_128

    // mmh3.hash64(key, 42, signed=False) → (h1, h2).
    [TestCase("", 17305828677633410339UL, 15060430851467758521UL)]
    [TestCase("A", 16750156190880784680UL, 12134197709928125219UL)]
    [TestCase("ACGT", 2597925387403686983UL, 6984365358888629242UL)]
    [TestCase("ACGTACGTA", 3684529260574405972UL, 6691951328708870556UL)]
    [TestCase("ACGTACGTACGTACG", 5002160178696126918UL, 4352572467220137489UL)]
    [TestCase("ACGTACGTACGTACGT", 4706917051267373191UL, 12844982669895470291UL)]
    [TestCase("ACGTACGTACGTACGTACGTA", 13036166743686632327UL, 4543100632486228299UL)]
    [TestCase("ACGTACGTACGTACGTACGTACGTACGTACGT", 2590157638889282535UL, 9603203953392732922UL)]
    public void MurmurHash3X64_128_MatchesMmh3(string key, ulong h1, ulong h2)
    {
        var (a, b) = KmerAnalyzer.MurmurHash3X64_128(Encoding.ASCII.GetBytes(key), 42);
        Assert.Multiple(() =>
        {
            Assert.That(a, Is.EqualTo(h1));
            Assert.That(b, Is.EqualTo(h2));
        });
    }

    #endregion

    #region Sketches = mash sketch / mash info -d

    [Test]
    public void Sketch_k21_s5_EqualsMashInfoDumpAndSourmash()
    {
        // mash sketch -k 21 -s 5 A.fa; mash info -d (hashBits 64); sourmash MinHash(n=5, ksize=21) gives the same five.
        var sketch = KmerAnalyzer.CreateMinHashSketch(A, 21, 5);
        Assert.Multiple(() =>
        {
            Assert.That(sketch.Hashes, Is.EqualTo(new ulong[]
                { 6460448764372083, 7468640311819670, 7856285671510867, 9659045342622411, 10133432196212684 }));
            Assert.That(sketch.Use64, Is.True);
            Assert.That(sketch.Length, Is.EqualTo(10000));
        });
    }

    [Test]
    public void Sketch_k16_s5_Uses32BitHash_EqualsMashInfoDump()
    {
        // mash sketch -k 16 -s 5 A.fa: 4^16 = 2^32 → use64 false, low 32 bits of h1.
        var sketch = KmerAnalyzer.CreateMinHashSketch(A, 16, 5);
        Assert.Multiple(() =>
        {
            Assert.That(sketch.Hashes, Is.EqualTo(new ulong[] { 357156, 675973, 681892, 948453, 1205556 }));
            Assert.That(sketch.Use64, Is.False);
        });
    }

    [Test]
    public void Sketch_LengthCountsNButSkipsShortRecords()
    {
        // mash info -d E_k21.msh: "length" : 5005 (the five N included); records shorter than k are skipped.
        Assert.That(KmerAnalyzer.CreateMinHashSketch(E, 21).Length, Is.EqualTo(5005));
        Assert.That(KmerAnalyzer.CreateMinHashSketch(new[] { A, "ACGTACGTACGTACGTACGT" }, 21).Length, Is.EqualTo(10000));
        Assert.That(KmerAnalyzer.CreateMinHashSketch(new[] { "acgt", null! }, 21).Hashes, Is.Empty);
    }

    #endregion

    #region mash dist

    private static IEnumerable<TestCaseData> MashDistCases()
    {
        // ref, query, k, s, canonical, Mash output: distance, p-value, x, denominator (mash dist -k K -s S [-n]).
        object[][] rows =
        [
            ["A", "B", 21, 1000, true, "0.0101459", "0", 678, 1000],
            ["A", "C", 21, 1000, true, "0.0492808", "0", 216, 1000],
            ["A", "D", 21, 1000, true, "1", "1", 0, 1000],
            ["A", "E", 21, 1000, true, "0.0196919", "0", 494, 1000],
            ["E", "A", 21, 1000, true, "0.0196919", "0", 494, 1000],
            ["AA2", "B", 21, 1000, true, "0.0101459", "0", 678, 1000],
            ["AA2", "A", 21, 1000, true, "2.38274e-05", "0", 999, 1000],
            ["A", "B", 21, 50, true, "0.0118017", "1.09468e-273", 32, 50],
            ["A", "C", 21, 50, true, "0.0344723", "3.83401e-131", 16, 50],
            ["A", "E", 21, 50, true, "0.0219913", "1.86848e-196", 23, 50],
            ["AA2", "A", 21, 50, true, "0", "0", 50, 50],
            ["A", "B", 21, 10, true, "0.0193079", "4.78577e-43", 5, 10],
            ["A", "C", 21, 10, true, "0.0368186", "1.76324e-25", 3, 10],
            ["A", "E", 21, 10, true, "0.0193079", "6.32327e-44", 5, 10],
            ["AA2", "A", 21, 10, true, "0", "3.60663e-90", 10, 10],
            ["A", "B", 21, 100000, true, "0.0101216", "0", 8069, 11891],
            ["A", "C", 21, 100000, true, "0.0502924", "0", 3471, 16489],
            ["A", "D", 21, 100000, true, "1", "1", 0, 19960],
            ["A", "E", 21, 100000, true, "0.0194995", "0", 4960, 9980],
            ["AA2", "B", 21, 100000, true, "0.010192", "0", 8049, 11891],
            ["AA2", "A", 21, 100000, true, "4.77863e-05", "0", 9960, 9980],
            ["A", "B", 16, 1000, true, "0.00949197", "0", 753, 1000],
            ["A", "C", 16, 1000, true, "0.0514934", "0", 281, 1000],
            ["A", "E", 16, 1000, true, "0.0252583", "0", 501, 1000],
            ["AA2", "B", 16, 1000, true, "0.00963442", "0", 750, 1000],
            ["AA2", "A", 16, 1000, true, "9.39614e-05", "0", 997, 1000],
            ["A", "B", 16, 50, true, "0.0111051", "2.23086e-202", 36, 50],
            ["A", "C", 16, 50, true, "0.0423958", "1.30457e-88", 17, 50],
            ["A", "E", 16, 50, true, "0.0307798", "3.40982e-121", 22, 50],
            ["AA2", "A", 16, 50, true, "0", "1.99748e-297", 50, 50],
            ["A", "B", 16, 10, true, "0.0121348", "3.47734e-40", 7, 10],
            ["A", "C", 16, 10, true, "0.034976", "3.85705e-22", 4, 10],
            ["A", "E", 16, 10, true, "0.034976", "7.63922e-23", 4, 10],
            ["AA2", "A", 16, 10, true, "0", "4.5719e-60", 10, 10],
            ["A", "B", 16, 100000, true, "0.0101151", "0", 8493, 11477],
            ["A", "C", 16, 100000, true, "0.0504411", "0", 4455, 15515],
            ["A", "E", 16, 100000, true, "0.0255299", "0", 4970, 9985],
            ["AA2", "A", 16, 100000, true, "4.69984e-05", "0", 9970, 9985],
            // mash dist -n (non-canonical)
            ["A", "B", 21, 1000, false, "0.00997914", "0", 682, 1000],
            ["A", "B", 16, 50, false, "0.0101152", "9.8267e-209", 37, 50],
            ["A", "E", 21, 1000, false, "0.0202137", "0", 486, 1000],
            ["A", "E", 16, 50, false, "0.0288636", "3.22382e-127", 23, 50],
            // unrelated pairs at small k: non-trivial p-values (32-bit path)
            ["A", "D", 8, 1000, true, "0.163715", "3.51356e-20", 156, 1000],
            ["C", "D", 8, 1000, true, "0.170166", "7.96259e-17", 147, 1000],
            ["E", "D", 8, 1000, true, "0.226404", "4.71317e-08", 89, 1000],
            ["A", "D", 8, 200, true, "0.154477", "1.91228e-06", 34, 200],
            ["C", "D", 8, 200, true, "0.142692", "2.51081e-08", 38, 200],
            ["E", "D", 8, 200, true, "0.238693", "0.0348761", 16, 200],
            ["A", "D", 9, 1000, true, "0.277279", "7.98107e-07", 43, 1000],
            ["C", "D", 9, 1000, true, "0.274831", "3.26044e-07", 44, 1000],
            ["E", "D", 9, 1000, true, "0.354541", "0.0175359", 21, 1000],
            ["A", "D", 9, 200, true, "0.27244", "0.0137623", 9, 200],
            ["C", "D", 9, 200, true, "0.335603", "0.320676", 5, 200],
            ["E", "D", 9, 200, true, "0.335603", "0.109276", 5, 200],
            ["A", "D", 10, 1000, true, "0.358945", "0.000406774", 14, 1000],
            ["C", "D", 10, 1000, true, "0.374163", "0.00356671", 12, 1000],
            ["E", "D", 10, 1000, true, "0.427567", "0.0426093", 7, 1000],
            ["A", "D", 10, 200, true, "0.352145", "0.070753", 3, 200],
            ["E", "D", 10, 200, true, "1", "1", 0, 200],
            ["A", "D", 11, 1000, true, "0.502133", "0.33404", 2, 1000],
            ["A", "D", 12, 1000, true, "0.402692", "0.000257674", 4, 1000],
            ["C", "D", 12, 1000, true, "0.517967", "0.257683", 1, 1000],
            ["E", "D", 12, 1000, true, "0.517967", "0.180282", 1, 1000],
        ];
        foreach (var r in rows)
            yield return new TestCaseData(r).SetName($"MashDist_{r[0]}_{r[1]}_k{r[2]}_s{r[3]}{((bool)r[4] ? "" : "_n")}");
    }

    /// <summary>C++ ostream default formatting (precision 6, %g) of a double.</summary>
    private static string Cpp(double v) => v.ToString("G6", CultureInfo.InvariantCulture).ToLowerInvariant();

    [TestCaseSource(nameof(MashDistCases))]
    public void CompareMinHashSketches_EqualsMashDistOutput(
        string reference, string query, int k, int s, bool canonical, string distance, string pValue, int x, int denom)
    {
        var r = KmerAnalyzer.CreateMinHashSketch(Records(reference), k, s, canonical);
        var q = KmerAnalyzer.CreateMinHashSketch(Records(query), k, s, canonical);
        var result = KmerAnalyzer.CompareMinHashSketches(r, q);
        Assert.Multiple(() =>
        {
            Assert.That(result.SharedHashes, Is.EqualTo(x), "x");
            Assert.That(result.Denominator, Is.EqualTo(denom), "s");
            Assert.That(result.Jaccard, Is.EqualTo((double)x / denom), "J");
            Assert.That(Cpp(result.Distance), Is.EqualTo(distance), "distance");
            Assert.That(Cpp(result.PValue), Is.EqualTo(pValue), "p-value");
        });
    }

    [Test]
    public void SketchLargerThanUnion_EqualsExactJaccardAndMashDistance()
    {
        // mash dist -s 100000 (s ≥ |union|) is the exact canonical Jaccard: 8069/11891 = sourmash scaled=1 jaccard
        // 0.678580438987470.
        var opt = new KmerCountingOptions(Canonical: true);
        var cmp = KmerAnalyzer.CompareMinHashSketches(
            KmerAnalyzer.CreateMinHashSketch(A, 21, 100000), KmerAnalyzer.CreateMinHashSketch(B, 21, 100000));
        Assert.Multiple(() =>
        {
            Assert.That(cmp.Jaccard, Is.EqualTo(KmerAnalyzer.JaccardSimilarity(A, B, 21, opt)));
            Assert.That(cmp.Jaccard, Is.EqualTo(0.678580438987470).Within(1e-14));
            Assert.That(cmp.Distance, Is.EqualTo(KmerAnalyzer.MashDistance(A, B, 21, opt)));
        });
    }

    [Test]
    public void Compare_DifferentSketchSizes_UsesSmaller()
    {
        // Mash reduces the larger sketch to the reference's size; the merge is capped at min(s).
        var big = KmerAnalyzer.CreateMinHashSketch(A, 21, 1000);
        var small = KmerAnalyzer.CreateMinHashSketch(B, 21, 50);
        var cmp = KmerAnalyzer.CompareMinHashSketches(big, small);
        Assert.Multiple(() =>
        {
            Assert.That(cmp.SharedHashes, Is.EqualTo(32));
            Assert.That(cmp.Denominator, Is.EqualTo(50));
        });
    }

    [Test]
    public void Compare_Validation_AndEmptyConvention()
    {
        var a21 = KmerAnalyzer.CreateMinHashSketch(A, 21, 10);
        Assert.Multiple(() =>
        {
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a21, KmerAnalyzer.CreateMinHashSketch(A, 16, 10)));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a21, KmerAnalyzer.CreateMinHashSketch(A, 21, 10, canonical: false)));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a21, KmerAnalyzer.CreateMinHashSketch(A, 21, 10, seed: 7)));
            Assert.Throws<ArgumentNullException>(() => KmerAnalyzer.CompareMinHashSketches(null!, a21));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.CreateMinHashSketch(A, 0));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.CreateMinHashSketch(A, 33));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.CreateMinHashSketch(A, 21, 0));
            Assert.Throws<ArgumentNullException>(() => KmerAnalyzer.CreateMinHashSketch((IEnumerable<string>)null!, 21));

            var empty = KmerAnalyzer.CompareMinHashSketches(
                KmerAnalyzer.CreateMinHashSketch("", 21), KmerAnalyzer.CreateMinHashSketch("ACG", 21));
            Assert.That(empty, Is.EqualTo(new MashComparison(0, 0, 0.0, 0.0, 1.0)));
        });
    }

    [Test]
    public void MashPValue_Formula()
    {
        // Mash pValue(x, lenRef, lenQry, 4^k, s): x = 0 → 1; A/D k=9 s=200 → 9 shared of 200 = 0.0137623 (mash dist).
        Assert.Multiple(() =>
        {
            Assert.That(KmerAnalyzer.MashPValue(0, 10000, 10000, 9, 200), Is.EqualTo(1.0));
            Assert.That(Cpp(KmerAnalyzer.MashPValue(9, 10000, 10000, 9, 200)), Is.EqualTo("0.0137623"));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.MashPValue(-1, 1, 1, 9, 2));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.MashPValue(1, 1, 1, 0, 2));
        });
    }

    #endregion

    #region Containment index (sourmash scaled=1 contained_by)

    // sourmash 4.9.4: MinHash(n=0, ksize=k, scaled=1), add_sequence(seq, force=True); a.contained_by(b).
    [TestCase("A", "B", 21, 0.808517034068136)]
    [TestCase("A", "C", 21, 0.347795591182365)]
    [TestCase("A", "D", 21, 0.0)]
    [TestCase("A", "E", 21, 0.496993987975952)]
    [TestCase("E", "A", 21, 1.0)]
    [TestCase("A", "B", 16, 0.850575863795693)]
    [TestCase("A", "C", 16, 0.446169253880821)]
    [TestCase("A", "E", 16, 0.497746619929895)]
    [TestCase("E", "A", 16, 1.0)]
    public void ContainmentIndex_Canonical_EqualsSourmashScaled1(string a, string b, int k, double expected)
    {
        double c = KmerAnalyzer.ContainmentIndex(Records(a).Single(), Records(b).Single(), k, new KmerCountingOptions(Canonical: true));
        Assert.That(c, Is.EqualTo(expected).Within(1e-14));
    }

    [Test]
    public void ContainmentIndex_IdentityAndConventions()
    {
        var opt = new KmerCountingOptions(Canonical: true);
        int nA = KmerAnalyzer.DistinctKmers(A, 21, opt).Count;
        int nB = KmerAnalyzer.DistinctKmers(B, 21, opt).Count;
        double cab = KmerAnalyzer.ContainmentIndex(A, B, 21, opt);
        double cba = KmerAnalyzer.ContainmentIndex(B, A, 21, opt);
        double j = KmerAnalyzer.JaccardSimilarity(A, B, 21, opt);
        Assert.Multiple(() =>
        {
            Assert.That(cab * nA, Is.EqualTo(cba * nB).Within(1e-9), "C(A,B)|A| = C(B,A)|B| = |A∩B|");
            Assert.That(Math.Round(cab * nA), Is.EqualTo(8069), "mash dist -s 100000 shared");
            Assert.That(j, Is.LessThanOrEqualTo(Math.Min(cab, cba)));
            // literal: GATTACA k=3 {GAT, ATT, TTA, TAC, ACA} in GATTACCA {GAT, ATT, TTA, TAC, ACC, CCA} → 4/5.
            Assert.That(KmerAnalyzer.ContainmentIndex("GATTACA", "GATTACCA", 3), Is.EqualTo(0.8));
            Assert.That(KmerAnalyzer.ContainmentIndex("", "ACGT", 2), Is.EqualTo(0.0));
            Assert.That(KmerAnalyzer.ContainmentIndex(null!, null!, 2), Is.EqualTo(0.0));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.ContainmentIndex("ACGT", "ACGT", 0));
        });
    }

    #endregion
}
