// KMER-DIST-001 (audit round 3, WP9) — spaced -d EV evolutionary distance, the spaced reader (non-letters deleted) in the
// spaced-faithful AcgtOnly mode, sourmash FracMinHash (scaled) sketches, Mash p-value / sketch validation, d2*/d2S clamp.
// Evidence: docs/Evidence/KMER-DIST-001-Evidence.md; docs/algorithms/K-mer/K-mer_Euclidean_Distance.md §5.3, §7.7, §7.8.
// Reference values (executed, not the code under test):
//   - spaced 1.2.0 (Ubuntu archive binary, source spaced_1.2.0-201605+dfsg src/sort.h): spaced [-r] -t 1 -f <patterns>
//     -d EV|JS|EU, 12 printed digits (C++ setprecision(12)), locked to one unit of the 12th digit; "-nan" = NaN. Every row also equals the Python
//     replica ref.py (reader: non-letters deleted, non-ACGT letters -> N; EV formula of the sort.h EV branch).
//   - sourmash 4.9.4 (pip): MinHash(n=0, ksize=k, scaled=S) .add_sequence(seq, force=True); len(), count_common,
//     jaccard, contained_by, max_containment; MinHash(0, 21, scaled=S)._max_hash.
// Audit round 4 (WP10): FracMinHash downsampling (sourmash downsample=True / MinHash.downsample), abundance tracking
// (track_abundance=True: angular_similarity, contained_by_weighted), u32 scaled range, MashPValue k range (Mash -k 1..32).
// Reference values: sourmash 4.9.4 executed in Python (scratch ref.py / ab.py / cli.py), including the sourmash compare CLI.
// Test sequences are generated by a 64-bit LCG (x <- x*6364136223846793005 + 1442695040888963407 mod 2^64, base = x>>62)
// in both Python (gen2.py / sm.py) and here, so no long literals are embedded.

using System.Globalization;

namespace Seqeron.Genomics.Tests.Unit.Analysis;

[TestFixture]
public class KmerAnalyzer_SpacedEvAndFracMinHash_Tests
{
    private static readonly KmerCountingOptions AcgtOnly = new(AcgtOnly: true);

    private static readonly Dictionary<string, string[]> Patterns = new()
    {
        ["P8"] = ["110101100111", "101110011011", "111001010111"],
        ["P6"] = ["11011011", "10111011", "11101101"],
        ["P5"] = ["11011", "10111", "11101"],
        ["P7"] = ["1101011", "1011101", "1110011"],
        ["P4"] = ["1111"],
        ["PT"] = ["1011", "1101"],
    };

    #region LCG test data (identical to the Python generators)

    private static ulong _x;

    private static ulong Next() => _x = unchecked(_x * 6364136223846793005UL + 1442695040888963407UL);

    private static string Random(ulong seed, int n)
    {
        _x = seed;
        var c = new char[n];
        for (int i = 0; i < n; i++)
            c[i] = "ACGT"[(int)(Next() >> 62)];
        return new string(c);
    }

    private static string Mutate(string s, ulong seed, int percent)
    {
        _x = seed;
        var c = s.ToCharArray();
        for (int i = 0; i < c.Length; i++)
        {
            ulong r = Next();
            if ((r >> 33) % 100 < (ulong)percent)
                c[i] = "ACGT"[(int)(((ulong)"ACGT".IndexOf(c[i]) + 1 + (r >> 40) % 3) % 4)];
        }
        return new string(c);
    }

    // gen2.py dirty(): gaps '-', '*', digits inserted; N / R substituted; every 5th symbol lower-cased.
    private static string Dirty(string s)
    {
        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < s.Length; i++)
        {
            char ch = s[i];
            if (i % 53 == 0) sb.Append('-');
            if (i % 71 == 0) sb.Append('*');
            if (i % 97 == 0) sb.Append('7');
            if (i % 89 == 0) ch = 'N';
            else if (i % 113 == 0) ch = 'R';
            if (i % 5 == 0) ch = char.ToLowerInvariant(ch);
            sb.Append(ch);
        }
        return sb.ToString();
    }

    private static readonly Lazy<Dictionary<string, string>> SpacedSeqs = new(() =>
    {
        string a = Random(11, 1500);
        return new Dictionary<string, string>
        {
            ["A"] = a,
            ["B"] = Mutate(a, 13, 10),
            ["C"] = Mutate(a, 17, 25),
            ["D"] = Dirty(Mutate(a, 19, 12)),
            ["E"] = a.Substring(200, 1200),
            ["G1"] = "ACG-TACGTACGGT-ACCA*TTG",
            ["G2"] = "ACGTTACGTAC1GGTAACCATT",
            ["N1"] = "AGGTAAGGTGNGTTGAGATctggacTTTTGACGCCTRGAGCCCGCAGTGCTCCTCGAAAAGTAGCNNATGCCTTGGGCTGCT",
            ["N2"] = "CAAAGGCCCTACCTTCTTATAGTCCTTYCAACATACAAGTAtagttgGAAGTTCTAAGTTCAGNTTAATC",
        };
    });

    private static readonly Lazy<Dictionary<string, string>> SourmashSeqs = new(() =>
    {
        string a = Random(1, 20000);
        string b = Mutate(a, 7, 5);
        var e = b.ToCharArray();
        for (int i = 0; i < e.Length; i += 997)
            e[i] = 'N';
        string es = new string(e);
        es = es[..100].ToLowerInvariant() + es[100..];
        return new Dictionary<string, string>
        {
            ["A"] = a,
            ["B"] = b,
            ["C"] = a.Substring(5000, 10000),
            ["D"] = Random(2, 8000),
            ["E"] = es,
        };
    });

    // ab.py: R = rnd(3,400), U = rnd(4,1500), V = rnd(5,700); P = R·R·R·U·V (R thrice), Q = R·U·U·mut(V,9,10) (U twice),
    // W = R[:200] + "N" + R[200:] + lower(U) + R.
    private static readonly Lazy<Dictionary<string, string>> AbundanceSeqs = new(() =>
    {
        string r = Random(3, 400), u = Random(4, 1500), v = Random(5, 700);
        var s = SourmashSeqs.Value;
        return new Dictionary<string, string>
        {
            ["P"] = r + r + r + u + v,
            ["Q"] = r + u + u + Mutate(v, 9, 10),
            ["W"] = r[..200] + "N" + r[200..] + u.ToLowerInvariant() + r,
            ["A"] = s["A"],
            ["B"] = s["B"],
            ["C"] = s["C"],
        };
    });

    #endregion

    private static string Printed(double v) => v.ToString("G12", CultureInfo.InvariantCulture);

    private static KmerDistanceMetric Metric(string d) => d switch
    {
        "EV" => KmerDistanceMetric.SpacedEvolutionary,
        "JS" => KmerDistanceMetric.JensenShannon,
        _ => KmerDistanceMetric.EuclideanCounts,
    };

    #region spaced binary (EV / JS / EU, with and without -r)

    // spaced [-r] -t 1 -f <patterns> -d <metric>: first FASTA record = seq1, second = seq2; both = run without -r.
    [TestCase("A","B", "P8", "EV", false, 0.117255304438)]
    [TestCase("A","B", "P8", "EV", true, 0.119414426485)]
    [TestCase("A","B", "P8", "JS", false, 0.573935509)]
    [TestCase("A","B", "P8", "JS", true, 0.692408317556)]
    [TestCase("A","B", "P8", "EU", false, 41.7372414404)]
    [TestCase("A","B", "P8", "EU", true, 57.2042902264)]
    [TestCase("A","B", "P6", "EV", false, 0.27326159765)]
    [TestCase("A","B", "P6", "EV", true, 1.2)]
    [TestCase("A","B", "P6", "JS", false, 0.360407175454)]
    [TestCase("A","B", "P6", "JS", true, 0.432800922136)]
    [TestCase("A","B", "P6", "EU", false, 38.304880869)]
    [TestCase("A","B", "P6", "EU", true, 59.4256571831)]
    [TestCase("A","B", "P5", "EV", false, 1.2)]
    [TestCase("A","B", "P5", "EV", true, 1.2)]
    [TestCase("A","B", "P5", "JS", false, 0.0249247335432)]
    [TestCase("A","B", "P5", "JS", true, 0.030951292486)]
    [TestCase("A","B", "P5", "EU", false, 32.262871029)]
    [TestCase("A","B", "P5", "EU", true, 106.990877086)]
    [TestCase("A","B", "P4", "EV", false, 1.2)]
    [TestCase("A","B", "P4", "EV", true, 1.2)]
    [TestCase("A","B", "P4", "JS", false, 0.0232399885393)]
    [TestCase("A","B", "P4", "JS", true, 0.0280616199437)]
    [TestCase("A","B", "P4", "EU", false, 32.6802692767)]
    [TestCase("A","B", "P4", "EU", true, 106.146125695)]
    [TestCase("A","C", "P8", "EV", false, 0.308204981926)]
    [TestCase("A","C", "P8", "EV", true, 0.311479608973)]
    [TestCase("A","C", "P8", "JS", false, 0.87840790659)]
    [TestCase("A","C", "P8", "JS", true, 0.900815658374)]
    [TestCase("A","C", "P8", "EU", false, 51.6461687545)]
    [TestCase("A","C", "P8", "EU", true, 64.825313067)]
    [TestCase("A","C", "P6", "EV", false, double.NaN)]
    [TestCase("A","C", "P6", "EV", true, 1.2)]
    [TestCase("A","C", "P6", "JS", false, 0.577605364911)]
    [TestCase("A","C", "P6", "JS", true, 0.544139069544)]
    [TestCase("A","C", "P6", "EU", false, 49.0548493374)]
    [TestCase("A","C", "P6", "EU", true, 65.8801972484)]
    [TestCase("A","C", "P5", "EV", false, 1.2)]
    [TestCase("A","C", "P5", "EV", true, 1.2)]
    [TestCase("A","C", "P5", "JS", false, 0.0406351816508)]
    [TestCase("A","C", "P5", "JS", true, 0.0372460687849)]
    [TestCase("A","C", "P5", "EU", false, 42.9715950544)]
    [TestCase("A","C", "P5", "EU", true, 110.685038147)]
    [TestCase("A","C", "P4", "EV", false, 1.2)]
    [TestCase("A","C", "P4", "EV", true, 1.2)]
    [TestCase("A","C", "P4", "JS", false, 0.0466983564156)]
    [TestCase("A","C", "P4", "JS", true, 0.0386809753419)]
    [TestCase("A","C", "P4", "EU", false, 45.1220566907)]
    [TestCase("A","C", "P4", "EU", true, 110.611934257)]
    [TestCase("D","E", "P8", "EV", false, 0.154793408617)]
    [TestCase("D","E", "P8", "EV", true, 0.156900799006)]
    [TestCase("D","E", "P8", "JS", false, 0.63686524548)]
    [TestCase("D","E", "P8", "JS", true, 0.718359461301)]
    [TestCase("D","E", "P8", "EU", false, 41.460642764)]
    [TestCase("D","E", "P8", "EU", true, 54.7873578962)]
    [TestCase("D","E", "P6", "EV", false, 0.304993693825)]
    [TestCase("D","E", "P6", "EV", true, 1.2)]
    [TestCase("D","E", "P6", "JS", false, 0.447560572907)]
    [TestCase("D","E", "P6", "JS", true, 0.498360366106)]
    [TestCase("D","E", "P6", "EU", false, 39.3947139608)]
    [TestCase("D","E", "P6", "EU", true, 59.0154539137)]
    [TestCase("D","E", "P5", "EV", false, 1.2)]
    [TestCase("D","E", "P5", "EV", true, 1.2)]
    [TestCase("D","E", "P5", "JS", false, 0.0428628088243)]
    [TestCase("D","E", "P5", "JS", true, 0.0452263911236)]
    [TestCase("D","E", "P5", "EU", false, 38.9172812114)]
    [TestCase("D","E", "P5", "EU", true, 111.150221664)]
    [TestCase("D","E", "P4", "EV", false, 1.2)]
    [TestCase("D","E", "P4", "EV", true, 1.2)]
    [TestCase("D","E", "P4", "JS", false, 0.0388550548277)]
    [TestCase("D","E", "P4", "JS", true, 0.0424546178083)]
    [TestCase("D","E", "P4", "EU", false, 37.549966711)]
    [TestCase("D","E", "P4", "EU", true, 110.258786498)]
    [TestCase("N1","N2", "P5", "EV", false, 1.2)]
    [TestCase("N1","N2", "P5", "EV", true, 1.2)]
    [TestCase("N1","N2", "P5", "JS", false, 0.706137367852)]
    [TestCase("N1","N2", "P5", "JS", true, 0.644779801994)]
    [TestCase("N1","N2", "P5", "EU", false, 11.2827316031)]
    [TestCase("N1","N2", "P5", "EU", true, 14.4441651361)]
    [TestCase("N1","N2", "P7", "EV", false, double.NaN)]
    [TestCase("N1","N2", "P7", "EV", true, 0.767483449137)]
    [TestCase("N1","N2", "P7", "JS", false, 0.767473374082)]
    [TestCase("N1","N2", "P7", "JS", true, 0.724905982831)]
    [TestCase("N1","N2", "P7", "EU", false, 10.59658835)]
    [TestCase("N1","N2", "P7", "EU", true, 12.8296572574)]
    [TestCase("N1","N2", "P4", "EV", false, 1.2)]
    [TestCase("N1","N2", "P4", "EV", true, 1.2)]
    [TestCase("N1","N2", "P4", "JS", false, 0.693975547992)]
    [TestCase("N1","N2", "P4", "JS", true, 0.618160592821)]
    [TestCase("N1","N2", "P4", "EU", false, 11.3578166916)]
    [TestCase("N1","N2", "P4", "EU", true, 14.2478068488)]
    [TestCase("N1","N2", "P8", "EV", false, 1.2)]
    [TestCase("N1","N2", "P8", "EV", true, 1.2)]
    [TestCase("N1","N2", "P8", "JS", false, 0.702514522161)]
    [TestCase("N1","N2", "P8", "JS", true, 0.702514522161)]
    [TestCase("N1","N2", "P8", "EU", false, 9.50435265839)]
    [TestCase("N1","N2", "P8", "EU", true, 11.5902079481)]
    [TestCase("G1","G2", "P5", "EV", false, 0.159471857578)]
    [TestCase("G1","G2", "P5", "EV", true, 0.194616371339)]
    [TestCase("G1","G2", "P5", "JS", false, 0.330976739232)]
    [TestCase("G1","G2", "P5", "JS", true, 0.396910673996)]
    [TestCase("G1","G2", "P5", "EU", false, 3.77806939218)]
    [TestCase("G1","G2", "P5", "EU", true, 7.04250256263)]
    [TestCase("G1","G2", "P7", "EV", false, 0.194860355167)]
    [TestCase("G1","G2", "P7", "EV", true, 0.203096229828)]
    [TestCase("G1","G2", "P7", "JS", false, 0.583517771786)]
    [TestCase("G1","G2", "P7", "JS", true, 0.651184225901)]
    [TestCase("G1","G2", "P7", "EU", false, 4.20170339826)]
    [TestCase("G1","G2", "P7", "EU", true, 6.60651070081)]
    [TestCase("G1","G2", "P4", "EV", false, 0.115591795132)]
    [TestCase("G1","G2", "P4", "EV", true, 0.14630010832)]
    [TestCase("G1","G2", "P4", "JS", false, 0.257923626693)]
    [TestCase("G1","G2", "P4", "JS", true, 0.346029410258)]
    [TestCase("G1","G2", "P4", "EU", false, 3.60555127546)]
    [TestCase("G1","G2", "P4", "EU", true, 7.74596669241)]
    [TestCase("G1","G2", "P8", "EV", false, 1.2)]
    [TestCase("G1","G2", "P8", "EV", true, 1.2)]
    [TestCase("G1","G2", "P8", "JS", false, 1)]
    [TestCase("G1","G2", "P8", "JS", true, 1)]
    [TestCase("G1","G2", "P8", "EU", false, 4.35889894354)]
    [TestCase("G1","G2", "P8", "EU", true, 5.29150262213)]
    public void SpacedWordDistance_AcgtOnly_EqualsSpacedBinary(string first, string second, string patterns, string metric, bool both, double printed)
    {
        double actual = KmerAnalyzer.SpacedWordDistance(
            SpacedSeqs.Value[first], SpacedSeqs.Value[second], Patterns[patterns], Metric(metric), AcgtOnly, both);
        if (double.IsNaN(printed))
        {
            Assert.That(actual, Is.NaN);
            return;
        }
        // Equal to the 12 printed significant digits: within one unit of the 12th digit (summation order may move the
        // last printed digit, e.g. D/E P6 JS both 0.4983603661055… prints …106 in C++ and …105 here).
        double unit = Math.Pow(10, Math.Floor(Math.Log10(Math.Abs(printed))) - 11);
        Assert.That(actual, Is.EqualTo(printed).Within(unit));
    }

    [Test]
    public void SpacedReader_GapInput_EqualsSpacedBinary_AndStrippedInput()
    {
        // tiny.fa  >X ACG-TACGT  >Y ACGTTACGA, patterns 1011/1101 (spaced binary, 12 digits):
        // JS -r 0.57013316426 (no -r 0.57013316426), EU -r 2.64575131106 / 4.69041575982, EV -r 0.427666596474 / 0.578620038162.
        // Before WP9 the gap was kept as an N window: JS -r 0.25.
        const string x = "ACG-TACGT", y = "ACGTTACGA";
        string[] p = Patterns["PT"];
        Assert.Multiple(() =>
        {
            Assert.That(Printed(KmerAnalyzer.SpacedWordDistance(x, y, p, KmerDistanceMetric.JensenShannon, AcgtOnly)), Is.EqualTo("0.57013316426"));
            Assert.That(Printed(KmerAnalyzer.SpacedWordDistance(x, y, p, KmerDistanceMetric.JensenShannon, AcgtOnly, true)), Is.EqualTo("0.57013316426"));
            Assert.That(Printed(KmerAnalyzer.SpacedWordDistance(x, y, p, KmerDistanceMetric.EuclideanCounts, AcgtOnly)), Is.EqualTo("2.64575131106"));
            Assert.That(Printed(KmerAnalyzer.SpacedWordDistance(x, y, p, KmerDistanceMetric.EuclideanCounts, AcgtOnly, true)), Is.EqualTo("4.69041575982"));
            Assert.That(Printed(KmerAnalyzer.SpacedWordDistance(x, y, p, KmerDistanceMetric.SpacedEvolutionary, AcgtOnly)), Is.EqualTo("0.427666596474"));
            Assert.That(Printed(KmerAnalyzer.SpacedWordDistance(x, y, p, KmerDistanceMetric.SpacedEvolutionary, AcgtOnly, true)), Is.EqualTo("0.578620038162"));
            // The reader deletes '-', '*', digits and blanks: identical to the stripped input.
            Assert.That(KmerAnalyzer.SpacedWordDistance("AC G-*7TACGT", y, p, KmerDistanceMetric.JensenShannon, AcgtOnly),
                Is.EqualTo(KmerAnalyzer.SpacedWordDistance("ACGTACGT", y, p, KmerDistanceMetric.JensenShannon, AcgtOnly)));
            // The literal default windows the string as given (a gap is a symbol), so it differs.
            Assert.That(KmerAnalyzer.SpacedWordDistance(x, y, p, KmerDistanceMetric.JensenShannon, KmerCountingOptions.Default),
                Is.Not.EqualTo(KmerAnalyzer.SpacedWordDistance(x, y, p, KmerDistanceMetric.JensenShannon, AcgtOnly)));
        });
    }

    #endregion

    #region EV contract

    [Test]
    public void KmerDistance_SpacedEvolutionary_IsContiguousPattern()
    {
        var s = SpacedSeqs.Value;
        Assert.Multiple(() =>
        {
            foreach (bool both in new[] { false, true })
            {
                Assert.That(KmerAnalyzer.KmerDistance(s["A"], s["B"], 8, KmerDistanceMetric.SpacedEvolutionary, 0, both),
                    Is.EqualTo(KmerAnalyzer.SpacedWordDistance(s["A"], s["B"], ["11111111"], KmerDistanceMetric.SpacedEvolutionary, AcgtOnly, both)));
            }
            // spaced -f 11111111 -d EV on A/B: -r 0.119340289783, default (both strands) 0.122709335653.
            Assert.That(KmerAnalyzer.KmerDistance(s["A"], s["B"], 8, KmerDistanceMetric.SpacedEvolutionary), Is.EqualTo(0.119340289783).Within(1e-12));
            Assert.That(KmerAnalyzer.KmerDistance(s["A"], s["B"], 8, KmerDistanceMetric.SpacedEvolutionary, 0, bothStrands: true),
                Is.EqualTo(0.122709335653).Within(1e-12));
            // spaced -r -f pat3 (1111) on A/B saturates: 1.2.
            Assert.That(KmerAnalyzer.KmerDistance(s["A"], s["B"], 4, KmerDistanceMetric.SpacedEvolutionary), Is.EqualTo(1.2));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.KmerDistance(s["A"], s["B"], 4, KmerDistanceMetric.SpacedEvolutionary, 1));
        });
    }

    [Test]
    public void SpacedEvolutionary_AlwaysUsesSpacedReader()
    {
        var s = SpacedSeqs.Value;
        Assert.That(
            KmerAnalyzer.SpacedWordDistance(s["D"], s["E"], Patterns["P8"], KmerDistanceMetric.SpacedEvolutionary),
            Is.EqualTo(KmerAnalyzer.SpacedWordDistance(s["D"], s["E"], Patterns["P8"], KmerDistanceMetric.SpacedEvolutionary, AcgtOnly)));
    }

    [Test]
    public void SpacedEvolutionary_InvalidInput_Throws()
    {
        var s = SpacedSeqs.Value;
        Assert.Multiple(() =>
        {
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.KmerDistance(
                KmerAnalyzer.CountKmers("ACGT", 2), KmerAnalyzer.CountKmers("ACGA", 2), KmerDistanceMetric.SpacedEvolutionary))!.ParamName,
                Is.EqualTo("metric"));
            // Same weight (3), different lengths: spaced keeps one don't-care count.
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.SpacedWordDistance(
                s["A"], s["B"], ["1011", "10101"], KmerDistanceMetric.SpacedEvolutionary, AcgtOnly))!.ParamName, Is.EqualTo("patterns"));
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.SpacedWordDistance(
                "AC-GT", s["B"], ["110011"], KmerDistanceMetric.SpacedEvolutionary, AcgtOnly))!.ParamName, Is.EqualTo("seq1"));
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.SpacedWordDistance(
                s["A"], null!, ["11"], KmerDistanceMetric.SpacedEvolutionary, AcgtOnly))!.ParamName, Is.EqualTo("seq2"));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.SpacedWordDistance(
                s["A"], s["B"], ["11"], KmerDistanceMetric.SpacedEvolutionary, new KmerCountingOptions(Canonical: true)));
        });
    }

    [TestCase("ev")]
    [TestCase(" EV ")]
    [TestCase("evolutionary")]
    public void ParseDistanceMetric_Ev(string name)
        => Assert.That(KmerAnalyzer.ParseDistanceMetric(name), Is.EqualTo(KmerDistanceMetric.SpacedEvolutionary));

    #endregion

    #region FracMinHash (sourmash scaled)

    // sourmash 4.9.4 MinHash(0, 21, scaled=S)._max_hash (Rust max_hash_for_scaled, truncating).
    [TestCase(1, 18446744073709551615UL)]
    [TestCase(3, 6148914691236516864UL)]
    [TestCase(10, 1844674407370955264UL)]
    [TestCase(100, 184467440737095520UL)]
    [TestCase(1000, 18446744073709552UL)]
    [TestCase(7919, 2329428472497733UL)]
    [TestCase(2049, 9002803354665472UL)]
    [TestCase(123456789, 149418628356UL)]
    [TestCase(4294967295L, 4294967297UL)]
    public void FracMinHashMaxHash_EqualsSourmash(long scaled, ulong expected)
        => Assert.That(KmerAnalyzer.FracMinHashMaxHash(scaled), Is.EqualTo(expected));

    // sourmash: len(a), len(b), a.count_common(b), a.jaccard(b), a.contained_by(b), b.contained_by(a), a.max_containment(b).
    [TestCase("A", "B", 21, 1, 19980, 19980, 7145, 0.21773579155873837, 0.3576076076076076, 0.3576076076076076, 0.3576076076076076)]
    [TestCase("A", "C", 21, 1, 19980, 9980, 9980, 0.4994994994994995, 0.4994994994994995, 1.0, 1.0)]
    [TestCase("A", "D", 21, 1, 19980, 7980, 0, 0.0, 0.0, 0.0, 0.0)]
    [TestCase("A", "E", 21, 1, 19980, 19559, 6996, 0.21497710721199645, 0.35015015015015016, 0.35768699831279716, 0.35768699831279716)]
    [TestCase("C", "B", 21, 1, 9980, 19980, 3623, 0.1375631241219577, 0.3630260521042084, 0.18133133133133134, 0.3630260521042084)]
    [TestCase("A", "B", 21, 10, 2030, 1963, 713, 0.2173780487804878, 0.35123152709359606, 0.3632195618950586, 0.3632195618950586)]
    [TestCase("A", "C", 21, 10, 2030, 1011, 1011, 0.4980295566502463, 0.4980295566502463, 1.0, 1.0)]
    [TestCase("A", "D", 21, 10, 2030, 822, 0, 0.0, 0.0, 0.0, 0.0)]
    [TestCase("A", "E", 21, 10, 2030, 1925, 699, 0.21468058968058967, 0.3443349753694581, 0.3631168831168831, 0.3631168831168831)]
    [TestCase("C", "B", 21, 10, 1011, 1963, 381, 0.14693405322020825, 0.3768545994065282, 0.19409067753438614, 0.3768545994065282)]
    [TestCase("A", "B", 21, 100, 187, 194, 59, 0.18322981366459629, 0.3155080213903743, 0.30412371134020616, 0.3155080213903743)]
    [TestCase("A", "C", 21, 100, 187, 94, 94, 0.5026737967914439, 0.5026737967914439, 1.0, 1.0)]
    [TestCase("A", "D", 21, 100, 187, 80, 0, 0.0, 0.0, 0.0, 0.0)]
    [TestCase("A", "E", 21, 100, 187, 190, 58, 0.18181818181818182, 0.31016042780748665, 0.30526315789473685, 0.31016042780748665)]
    [TestCase("C", "B", 21, 100, 94, 194, 34, 0.13385826771653545, 0.3617021276595745, 0.17525773195876287, 0.3617021276595745)]
    [TestCase("A", "B", 21, 1000, 23, 14, 5, 0.15625, 0.21739130436987927, 0.35714315204470304, 0.35714315204470304)]
    [TestCase("A", "C", 21, 1000, 23, 15, 15, 0.6521739130434783, 0.6521739131096378, 1.0, 1.0)]
    [TestCase("A", "D", 21, 1000, 23, 11, 0, 0.0, 0.0, 0.0, 0.0)]
    [TestCase("A", "E", 21, 1000, 23, 14, 5, 0.15625, 0.21739130436987927, 0.35714315204470304, 0.35714315204470304)]
    [TestCase("C", "B", 21, 1000, 15, 14, 4, 0.16, 0.2666667476307222, 0.28571452163576244, 0.28571452163576244)]
    [TestCase("A", "B", 31, 1, 19970, 19970, 4314, 0.12109133778700949, 0.21602403605408113, 0.21602403605408113, 0.21602403605408113)]
    [TestCase("A", "C", 31, 1, 19970, 9970, 9970, 0.4992488733099649, 0.4992488733099649, 1.0, 1.0)]
    [TestCase("A", "D", 31, 1, 19970, 7970, 0, 0.0, 0.0, 0.0, 0.0)]
    [TestCase("A", "E", 31, 1, 19970, 19349, 4162, 0.11838325226839605, 0.20841261892839258, 0.21510155563595018, 0.21510155563595018)]
    [TestCase("C", "B", 31, 1, 9970, 19970, 2207, 0.07958028341686799, 0.2213640922768305, 0.11051577366049073, 0.2213640922768305)]
    [TestCase("A", "B", 31, 10, 1966, 1958, 435, 0.12467755803955288, 0.22126144455747712, 0.22216547497446373, 0.22216547497446373)]
    [TestCase("A", "C", 31, 10, 1966, 1006, 1006, 0.5116988809766022, 0.5116988809766022, 1.0, 1.0)]
    [TestCase("A", "D", 31, 10, 1966, 727, 0, 0.0, 0.0, 0.0, 0.0)]
    [TestCase("A", "E", 31, 10, 1966, 1896, 419, 0.12169619517862329, 0.2131230925737538, 0.2209915611814346, 0.2209915611814346)]
    [TestCase("C", "B", 31, 10, 1006, 1958, 215, 0.07821025827573663, 0.21371769383697814, 0.10980592441266598, 0.21371769383697814)]
    [TestCase("A", "B", 31, 100, 177, 195, 41, 0.12386706948640483, 0.23163841807909605, 0.21025641025641026, 0.23163841807909605)]
    [TestCase("A", "C", 31, 100, 177, 96, 96, 0.5423728813559322, 0.5423728813559322, 1.0, 1.0)]
    [TestCase("A", "D", 31, 100, 177, 81, 0, 0.0, 0.0, 0.0, 0.0)]
    [TestCase("A", "E", 31, 100, 177, 191, 40, 0.12195121951219512, 0.22598870056497175, 0.2094240837696335, 0.22598870056497175)]
    [TestCase("C", "B", 31, 100, 96, 195, 19, 0.06985294117647059, 0.19791666666666666, 0.09743589743589744, 0.19791666666666666)]
    [TestCase("A", "B", 31, 1000, 19, 16, 2, 0.06060606060606061, 0.10526315847892492, 0.1250000139547377, 0.1250000139547377)]
    [TestCase("A", "C", 31, 1000, 19, 9, 9, 0.47368421052631576, 0.4736842131551622, 1.0, 1.0)]
    [TestCase("A", "D", 31, 1000, 19, 12, 0, 0.0, 0.0, 0.0, 0.0)]
    [TestCase("A", "E", 31, 1000, 19, 14, 2, 0.06451612903225806, 0.10526315847892492, 0.14285726081788122, 0.14285726081788122)]
    [TestCase("C", "B", 31, 1000, 9, 16, 1, 0.041666666666666664, 0.1111247633815629, 0.06250000697736885, 0.1111247633815629)]
    public void CompareFracMinHashSketches_EqualsSourmash(
        string a, string b, int k, int scaled, int lenA, int lenB, int common,
        double jaccard, double containmentAInB, double containmentBInA, double maxContainment)
    {
        var sa = KmerAnalyzer.CreateFracMinHashSketch(SourmashSeqs.Value[a], k, scaled);
        var sb = KmerAnalyzer.CreateFracMinHashSketch(SourmashSeqs.Value[b], k, scaled);
        var c = KmerAnalyzer.CompareFracMinHashSketches(sa, sb);
        Assert.Multiple(() =>
        {
            Assert.That(sa.Hashes, Has.Count.EqualTo(lenA));
            Assert.That(sb.Hashes, Has.Count.EqualTo(lenB));
            Assert.That(c.SharedHashes, Is.EqualTo(common));
            Assert.That(c.UnionHashes, Is.EqualTo(lenA + lenB - common));
            Assert.That(c.Jaccard, Is.EqualTo(jaccard).Within(1e-15));
            Assert.That(c.ContainmentAInB, Is.EqualTo(containmentAInB).Within(1e-15));
            Assert.That(c.ContainmentBInA, Is.EqualTo(containmentBInA).Within(1e-15));
            Assert.That(c.MaxContainment, Is.EqualTo(maxContainment).Within(1e-15));
        });
    }

    [Test]
    public void CreateFracMinHashSketch_HashesEqualSourmash()
    {
        // sourmash: sorted(MinHash(0, 21, scaled=1000) + C).hashes)[:5], len 15.
        var sketch = KmerAnalyzer.CreateFracMinHashSketch(SourmashSeqs.Value["C"], 21, 1000);
        Assert.Multiple(() =>
        {
            Assert.That(sketch.Hashes, Has.Count.EqualTo(15));
            Assert.That(sketch.Hashes.Take(5), Is.EqualTo(new ulong[]
                { 4371404454895749, 5919670475642754, 6049817491049527, 9659045342622411, 10788914448772484 }));
            Assert.That(sketch.MaxHash, Is.EqualTo(18446744073709552UL));
            Assert.That(sketch.Hashes, Is.Ordered.Ascending);
            Assert.That(sketch.Hashes.All(h => h <= sketch.MaxHash));
        });
    }

    [Test]
    public void FracMinHash_Scaled1_EqualsExactCanonicalSets()
    {
        var s = SourmashSeqs.Value;
        var canonical = new KmerCountingOptions(Canonical: true);
        var c = KmerAnalyzer.CompareFracMinHashSketches(
            KmerAnalyzer.CreateFracMinHashSketch(s["A"], 21, 1), KmerAnalyzer.CreateFracMinHashSketch(s["E"], 21, 1));
        Assert.Multiple(() =>
        {
            Assert.That(c.Jaccard, Is.EqualTo(KmerAnalyzer.JaccardSimilarity(s["A"], s["E"], 21, canonical)).Within(1e-15));
            Assert.That(c.ContainmentAInB, Is.EqualTo(KmerAnalyzer.ContainmentIndex(s["A"], s["E"], 21, canonical)).Within(1e-15));
            Assert.That(c.ContainmentBInA, Is.EqualTo(KmerAnalyzer.ContainmentIndex(s["E"], s["A"], 21, canonical)).Within(1e-15));
        });
    }

    [Test]
    public void FracMinHash_EdgeCasesAndValidation()
    {
        var a = KmerAnalyzer.CreateFracMinHashSketch("ACGTACGTTGCA", 4, 1);
        var empty = KmerAnalyzer.CreateFracMinHashSketch(null!, 4, 1);
        Assert.Multiple(() =>
        {
            Assert.That(empty.Hashes, Is.Empty);
            // Rust jaccard: common / max(1, union); contained_by of an empty sketch = 0.
            Assert.That(KmerAnalyzer.CompareFracMinHashSketches(empty, empty), Is.EqualTo(new FracMinHashComparison(0, 0, 0.0, 0.0, 0.0, 0.0)));
            Assert.That(KmerAnalyzer.CompareFracMinHashSketches(a, empty).ContainmentAInB, Is.EqualTo(0.0));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.CreateFracMinHashSketch("ACGT", 0, 1));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.CreateFracMinHashSketch("ACGT", 2, 0));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(a, KmerAnalyzer.CreateFracMinHashSketch("ACGT", 4, 10)));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(a, KmerAnalyzer.CreateFracMinHashSketch("ACGT", 3, 1)));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(a, KmerAnalyzer.CreateFracMinHashSketch("ACGT", 4, 1, canonical: false)));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(a, a with { Hashes = [5UL, 3UL] }));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(a, a with { Hashes = [3UL, 3UL] }));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(a, a with { MaxHash = 10UL }));
            var s10 = KmerAnalyzer.CreateFracMinHashSketch("ACGT", 4, 10);
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(s10, s10 with { Hashes = [ulong.MaxValue] }));
            Assert.Throws<ArgumentNullException>(() => KmerAnalyzer.CompareFracMinHashSketches(null!, a));
        });
    }

    #endregion

    #region FracMinHash downsampling and abundance (audit round 4, WP10)

    [Test]
    public void FracMinHashScaled_U32Range()
    {
        Assert.Multiple(() =>
        {
            var top = KmerAnalyzer.CreateFracMinHashSketch(SourmashSeqs.Value["C"], 21, 4294967295L);
            Assert.That(top.Scaled, Is.EqualTo(4294967295L));
            Assert.That(top.MaxHash, Is.EqualTo(4294967297UL));
            Assert.That(top.Hashes.All(h => h <= 4294967297UL));
            Assert.That(Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.FracMinHashMaxHash(4294967296L))!.ParamName,
                Is.EqualTo("scaled"));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.FracMinHashMaxHash(0));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.CreateFracMinHashSketch("ACGT", 2, 4294967296L));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(top, top with { Scaled = 4294967296L }));
        });
    }

    [Test]
    public void DownsampleFracMinHash_EqualsSourmashDownsample()
    {
        // sourmash: x = MinHash(0, 21, scaled=10) + C; xd = x.downsample(scaled=1000): len 1011 -> 15, _max_hash
        // 18446744073709552, hashes == MinHash(0, 21, scaled=1000) + C. MinHash(0, 21, scaled=1) + C downsampled to 7919:
        // _max_hash 2329428472497733 (the truncating Rust value).
        var c = SourmashSeqs.Value["C"];
        var x = KmerAnalyzer.CreateFracMinHashSketch(c, 21, 10);
        var xd = KmerAnalyzer.DownsampleFracMinHash(x, 1000);
        var direct = KmerAnalyzer.CreateFracMinHashSketch(c, 21, 1000);
        Assert.Multiple(() =>
        {
            Assert.That(x.Hashes, Has.Count.EqualTo(1011));
            Assert.That(xd.Hashes, Has.Count.EqualTo(15));
            Assert.That(xd.Scaled, Is.EqualTo(1000L));
            Assert.That(xd.MaxHash, Is.EqualTo(18446744073709552UL));
            Assert.That(xd.Hashes, Is.EqualTo(direct.Hashes));
            Assert.That(xd.Hashes.Take(3), Is.EqualTo(new ulong[] { 4371404454895749, 5919670475642754, 6049817491049527 }));
            Assert.That(KmerAnalyzer.DownsampleFracMinHash(KmerAnalyzer.CreateFracMinHashSketch(c, 21, 1), 7919).MaxHash,
                Is.EqualTo(2329428472497733UL));
            Assert.That(KmerAnalyzer.DownsampleFracMinHash(x, 10).Hashes, Is.EqualTo(x.Hashes));
            // sourmash: "new scaled 1 is lower than current sample scaled 10" (Rust CannotUpsampleScaled).
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.DownsampleFracMinHash(x, 1))!.ParamName, Is.EqualTo("newScaled"));
            Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.DownsampleFracMinHash(x, 0));
            Assert.Throws<ArgumentNullException>(() => KmerAnalyzer.DownsampleFracMinHash(null!, 10));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.DownsampleFracMinHash(x with { MaxHash = 1 }, 100));
        });
    }

    // sourmash 4.9.4, x = MinHash(0, k, scaled=sa) + a, y = MinHash(0, k, scaled=sb) + b, S = max(sa, sb):
    // len(x.downsample(S)), len(y.downsample(S)), count_common, x.jaccard(y, downsample=True), and — as
    // `sourmash compare --containment / --max-containment` (signatures downsampled to S first) =
    // x.downsample(S).contained_by(y.downsample(S)) — containment A in B, B in A, max containment.
    [TestCase("A", "B", 21, 10, 100, 187, 194, 59, 0.18322981366459629, 0.3155080213903743, 0.30412371134020616, 0.3155080213903743)]
    [TestCase("A", "C", 21, 1, 1000, 23, 15, 15, 0.6521739130434783, 0.6521739131096378, 1.0, 1.0)]
    [TestCase("C", "B", 31, 100, 10, 96, 195, 19, 0.06985294117647059, 0.19791666666666666, 0.09743589743589744, 0.19791666666666666)]
    [TestCase("B", "A", 31, 1000, 10, 16, 19, 2, 0.06060606060606061, 0.1250000139547377, 0.10526315847892492, 0.1250000139547377)]
    [TestCase("A", "D", 21, 1, 10, 2030, 822, 0, 0.0, 0.0, 0.0, 0.0)]
    [TestCase("A", "E", 21, 3, 7919, 0, 1, 0, 0.0, 0.0, 0.0, 0.0)]
    public void CompareFracMinHashSketches_Downsample_EqualsSourmash(
        string a, string b, int k, long sa, long sb, int lenA, int lenB, int common,
        double jaccard, double containmentAInB, double containmentBInA, double maxContainment)
    {
        var x = KmerAnalyzer.CreateFracMinHashSketch(SourmashSeqs.Value[a], k, sa);
        var y = KmerAnalyzer.CreateFracMinHashSketch(SourmashSeqs.Value[b], k, sb);
        var c = KmerAnalyzer.CompareFracMinHashSketches(x, y, downsample: true);
        Assert.Multiple(() =>
        {
            Assert.That(c.SharedHashes, Is.EqualTo(common));
            Assert.That(c.UnionHashes, Is.EqualTo(lenA + lenB - common));
            Assert.That(c.Jaccard, Is.EqualTo(jaccard).Within(1e-15));
            Assert.That(c.ContainmentAInB, Is.EqualTo(containmentAInB).Within(1e-15));
            Assert.That(c.ContainmentBInA, Is.EqualTo(containmentBInA).Within(1e-15));
            Assert.That(c.MaxContainment, Is.EqualTo(maxContainment).Within(1e-15));
            Assert.That(c.AngularSimilarity, Is.Null);
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(x, y));
        });
    }

    [Test]
    public void CreateFracMinHashSketch_TrackAbundance_EqualsSourmash()
    {
        // sourmash MinHash(0, 21, scaled=1, track_abundance=True) + P: 2600 hashes, abundances {1, 2, 3}, sum 3380 (= the
        // 3380 windows); first three (hash, abundance) pairs below. downsample(scaled=10): 230 hashes, sum 280.
        var p = AbundanceSeqs.Value["P"];
        var x = KmerAnalyzer.CreateFracMinHashSketch(p, 21, 1, trackAbundance: true);
        var xd = KmerAnalyzer.DownsampleFracMinHash(x, 10);
        Assert.Multiple(() =>
        {
            Assert.That(x.Hashes, Has.Count.EqualTo(2600));
            Assert.That(x.Abundances, Is.Not.Null);
            Assert.That(x.Abundances!.Distinct().Order(), Is.EqualTo(new long[] { 1, 2, 3 }));
            Assert.That(x.Abundances!.Sum(), Is.EqualTo(3380));
            Assert.That(x.Hashes.Take(3), Is.EqualTo(new ulong[] { 955398923976067, 14257512090346972, 18451528553218193 }));
            Assert.That(x.Abundances!.Take(3), Is.EqualTo(new long[] { 1, 1, 1 }));
            Assert.That(xd.Hashes, Has.Count.EqualTo(230));
            Assert.That(xd.Abundances!.Sum(), Is.EqualTo(280));
            Assert.That(x.Hashes, Is.EqualTo(KmerAnalyzer.CreateFracMinHashSketch(p, 21, 1).Hashes));
            Assert.That(KmerAnalyzer.CreateFracMinHashSketch(p, 21, 1).Abundances, Is.Null);
        });
    }

    // sourmash 4.9.4, MinHash(0, k, scaled, track_abundance=True) + seq for both (downsample=True when sa != sb):
    // x.angular_similarity(y) (= x.similarity(y)), x.similarity(y, ignore_abundance=True) (Jaccard), and at S = max(sa, sb)
    // xd.contained_by_weighted(yd), yd.contained_by_weighted(xd).
    [TestCase("P", "Q", 21, 1, 1, 0.4701473676328215, 0.63748031496063, 0.8236686390532545, 0.8590686274509803)]
    [TestCase("P", "Q", 21, 10, 10, 0.4751112686176898, 0.5923344947735192, 0.7857142857142857, 0.8394366197183099)]
    [TestCase("P", "W", 15, 1, 1, 0.7252694187711534, 0.722158438576349, 0.7855877141169522, 0.9942781690140845)]
    [TestCase("Q", "W", 31, 3, 3, 0.6075379149728062, 0.7157303370786516, 0.823021582733813, 0.9907894736842106)]
    [TestCase("P", "Q", 21, 1, 10, 0.4751112686176898, 0.5923344947735192, 0.7857142857142857, 0.8394366197183099)]
    [TestCase("A", "B", 21, 10, 10, 0.2325202182944529, 0.2173780487804878, 0.35123152709359606, 0.3632195618950586)]
    [TestCase("C", "B", 21, 100, 100, 0.1620291624837299, 0.13385826771653545, 0.3617021276595745, 0.17525773195876287)]
    [TestCase("P", "Q", 7, 1, 1, 0.5725053795568437, 0.8135313531353136, 0.9328226281673542, 0.9425989252564729)]
    [TestCase("W", "Q", 21, 10, 100, 0.6670115706749962, 0.7142857142857143, 1.0, 0.8260869565217391)]
    public void CompareFracMinHashSketches_Abundance_EqualsSourmash(
        string a, string b, int k, long sa, long sb, double angular, double jaccard, double weightedAInB, double weightedBInA)
    {
        var x = KmerAnalyzer.CreateFracMinHashSketch(AbundanceSeqs.Value[a], k, sa, trackAbundance: true);
        var y = KmerAnalyzer.CreateFracMinHashSketch(AbundanceSeqs.Value[b], k, sb, trackAbundance: true);
        var c = KmerAnalyzer.CompareFracMinHashSketches(x, y, downsample: sa != sb);
        Assert.Multiple(() =>
        {
            Assert.That(c.AngularSimilarity, Is.EqualTo(angular).Within(1e-15));
            Assert.That(c.Jaccard, Is.EqualTo(jaccard).Within(1e-15));
            Assert.That(c.WeightedContainmentAInB, Is.EqualTo(weightedAInB).Within(1e-15));
            Assert.That(c.WeightedContainmentBInA, Is.EqualTo(weightedBInA).Within(1e-15));
        });
    }

    [Test]
    public void CompareFracMinHashSketches_AbundanceEdgeCases()
    {
        var p = AbundanceSeqs.Value["P"];
        var q = AbundanceSeqs.Value["Q"];
        var withAb = KmerAnalyzer.CreateFracMinHashSketch(p, 21, 1, trackAbundance: true);
        var flat = KmerAnalyzer.CreateFracMinHashSketch(q, 21, 1);
        var c = KmerAnalyzer.CompareFracMinHashSketches(withAb, flat);
        var empty = KmerAnalyzer.CreateFracMinHashSketch("", 21, 1, trackAbundance: true);
        Assert.Multiple(() =>
        {
            // sourmash: x.similarity(y) with one flat sketch = jaccard 0.63748031496063; angular_similarity raises TypeError.
            Assert.That(c.Jaccard, Is.EqualTo(0.63748031496063).Within(1e-15));
            Assert.That(c.AngularSimilarity, Is.Null);
            Assert.That(c.WeightedContainmentAInB, Is.EqualTo(0.8236686390532545).Within(1e-15));
            Assert.That(c.WeightedContainmentBInA, Is.Null);
            Assert.That(KmerAnalyzer.CompareFracMinHashSketches(withAb, withAb).AngularSimilarity, Is.EqualTo(1.0));
            // Rust angular_similarity: a zero norm gives 0.
            Assert.That(KmerAnalyzer.CompareFracMinHashSketches(empty, withAb).AngularSimilarity, Is.EqualTo(0.0));
            Assert.That(KmerAnalyzer.CompareFracMinHashSketches(empty, withAb).WeightedContainmentAInB, Is.EqualTo(0.0));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(withAb with { Abundances = [1L] }, withAb));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareFracMinHashSketches(
                withAb with { Abundances = withAb.Abundances!.Select(_ => 0L).ToArray() }, withAb));
        });
    }

    #endregion

    #region Mash p-value and MinHash sketch validation, d2*/d2S clamp

    [Test]
    public void MashPValue_InconsistentInput_ThrowsArgumentException()
    {
        Assert.Multiple(() =>
        {
            // Length 0 with shared hashes: Mash's r = 0/0 = NaN (unreachable from a real comparison).
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.MashPValue(1, 0, 0, 21, 10))!.ParamName, Is.EqualTo("length1"));
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.MashPValue(1, 10, 0, 21, 10))!.ParamName, Is.EqualTo("length2"));
            // x > s: Mash's gsl_cdf_binomial_Q(x - 1, r, s) returns 0 silently.
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.MashPValue(5, 1000, 1000, 21, 3))!.ParamName, Is.EqualTo("sharedHashes"));
            Assert.That(KmerAnalyzer.MashPValue(0, 0, 0, 21, 10), Is.EqualTo(1.0));
            Assert.That(KmerAnalyzer.MashPValue(3, 1000, 1000, 21, 3), Is.InRange(0.0, 1.0));
            // WP10: k outside Mash's -k range 1..32 (Command.cpp: Option(Integer, "k", ..., 1, 32)). Before: k = 600 gave
            // Math.Pow(4, 600) = Infinity, r = NaN and an undocumented ArgumentOutOfRangeException("p") from BinomialUpperTail.
            Assert.That(Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.MashPValue(1, 1000, 1000, 600, 10))!.ParamName, Is.EqualTo("k"));
            Assert.That(Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.MashPValue(1, 1000, 1000, 33, 10))!.ParamName, Is.EqualTo("k"));
            Assert.That(Assert.Throws<ArgumentOutOfRangeException>(() => KmerAnalyzer.MashPValue(1, 1000, 1000, 0, 10))!.ParamName, Is.EqualTo("k"));
            // k = 32: r = 2.710505431213761e-17, scipy binom.sf(0, 10, r) = 2.7105054312137606e-16.
            Assert.That(KmerAnalyzer.MashPValue(1, 1000, 1000, 32, 10), Is.EqualTo(2.7105054312137606e-16).Within(1e-12).Percent);
        });
    }

    [Test]
    public void CompareMinHashSketches_MalformedSketch_ThrowsArgumentException()
    {
        var a = KmerAnalyzer.CreateMinHashSketch("ACGTACGGTTGCAACGTTAGCA", 4, 100);
        Assert.Multiple(() =>
        {
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a, a with { Hashes = a.Hashes.Reverse().ToArray() }))!.ParamName,
                Is.EqualTo("query"));
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a with { Hashes = [1UL, 1UL] }, a))!.ParamName,
                Is.EqualTo("reference"));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a, a with { SketchSize = 2 }));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a, a with { Hashes = null! }));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a, a with { Length = -1 }));
        });
    }

    [Test]
    public void CompareMinHashSketches_KOutsideMashRangeOrUse64Inconsistent_ThrowsArgumentException()
    {
        // WP11: K was not validated, so a hand-built sketch with K = 40 reached MashPValue and surfaced as an
        // ArgumentOutOfRangeException("k") from the p-value. Mash Command.cpp: -k range 1..32; Sketch.cpp:
        // use64 = alphabetSize^k > 2^32 (DNA: k > 16), so a 32-bit sketch holds only values <= 2^32 - 1.
        var k40 = new MinHashSketch(40, 10, true, 42, true, 1000, new ulong[] { 1, 2, 3 });
        var a = KmerAnalyzer.CreateMinHashSketch("ACGTACGGTTGCAACGTTAGCA", 4, 100);
        var b = KmerAnalyzer.CreateMinHashSketch("ACGTACGGTTGCAACGTTAGCAACGGTACGTTTAGCAGT", 21, 100);
        Assert.Multiple(() =>
        {
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(k40, k40))!.ParamName,
                Is.EqualTo("reference"));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(k40 with { K = 0, Use64 = false }, k40 with { K = 0, Use64 = false }));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(k40 with { K = 33 }, k40 with { K = 33 }));
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a, a with { Use64 = true }))!.ParamName,
                Is.EqualTo("query"));
            Assert.That(Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(b with { Use64 = false }, b))!.ParamName,
                Is.EqualTo("reference"));
            Assert.Throws<ArgumentException>(() => KmerAnalyzer.CompareMinHashSketches(a, a with { Hashes = [1UL, (ulong)uint.MaxValue + 1] }));
            // Boundaries stay valid: K = 32 (64-bit) and K = 16 (32-bit, largest value 2^32 - 1).
            Assert.That(KmerAnalyzer.CompareMinHashSketches(k40 with { K = 32 }, k40 with { K = 32 }).Jaccard, Is.EqualTo(1.0));
            var k16 = new MinHashSketch(16, 10, true, 42, false, 1000, new ulong[] { 1, uint.MaxValue });
            Assert.That(KmerAnalyzer.CompareMinHashSketches(k16, k16).SharedHashes, Is.EqualTo(2));
            Assert.That(KmerAnalyzer.CompareMinHashSketches(a, a).Jaccard, Is.EqualTo(1.0));
            Assert.That(KmerAnalyzer.CompareMinHashSketches(b, b).Jaccard, Is.EqualTo(1.0));
        });
    }

    [Test]
    public void MinHashSketch_FromHashes_NormalisesAndCompares()
    {
        var a = KmerAnalyzer.CreateMinHashSketch("ACGTACGGTTGCAACGTTAGCA", 4, 5);
        var full = KmerAnalyzer.CreateMinHashSketch("ACGTACGGTTGCAACGTTAGCA", 4, 1000);
        var shuffled = full.Hashes.Reverse().Concat(full.Hashes).ToArray();
        var rebuilt = MinHashSketch.FromHashes(4, 5, true, 42, a.Length, shuffled);
        Assert.Multiple(() =>
        {
            Assert.That(rebuilt.Hashes, Is.EqualTo(a.Hashes));
            Assert.That(rebuilt.Use64, Is.False);
            Assert.That(KmerAnalyzer.CompareMinHashSketches(rebuilt, a), Is.EqualTo(KmerAnalyzer.CompareMinHashSketches(a, a)));
            Assert.That(MinHashSketch.FromHashes(21, 5, true, 42, 0, []).Use64, Is.True);
            Assert.Throws<ArgumentNullException>(() => MinHashSketch.FromHashes(4, 5, true, 42, 0, null!));
            Assert.Throws<ArgumentOutOfRangeException>(() => MinHashSketch.FromHashes(33, 5, true, 42, 0, []));
            Assert.Throws<ArgumentOutOfRangeException>(() => MinHashSketch.FromHashes(4, 0, true, 42, 0, []));
            Assert.Throws<ArgumentOutOfRangeException>(() => MinHashSketch.FromHashes(4, 5, true, 42, -1, []));
            // WP11: k <= 16 is a 32-bit sketch (Mash use64 = 4^k > 2^32); a 64-bit value cannot belong to it.
            Assert.Throws<ArgumentOutOfRangeException>(() => MinHashSketch.FromHashes(0, 5, true, 42, 0, []));
            Assert.That(Assert.Throws<ArgumentException>(() => MinHashSketch.FromHashes(16, 5, true, 42, 0, [(ulong)uint.MaxValue + 1]))!.ParamName,
                Is.EqualTo("hashes"));
            Assert.That(MinHashSketch.FromHashes(16, 5, true, 42, 0, [uint.MaxValue]).Use64, Is.False);
            Assert.That(MinHashSketch.FromHashes(17, 5, true, 42, 0, [ulong.MaxValue]).Use64, Is.True);
        });
    }

    [Test]
    public void BackgroundAdjustedD2_IdenticalSequences_DistancesClampedToZero()
    {
        // Before the clamp: S1 vs S1, k = 2, r = 0 gave d2* = d2S = -1.1102230246251565e-16 (rounding; Cauchy–Schwarz bounds
        // both to [0, 1]).
        const string s1 = "AGGTAAGGTGGTTGAGATCTGGACTTTTGACGCCTGGAGCCCGCAGTGCTCCTCGAAAAGTAGCCATGCCTTGGGCTGCT";
        var st = KmerAnalyzer.BackgroundAdjustedD2(s1, s1, 2, 0);
        Assert.Multiple(() =>
        {
            Assert.That(st.D2StarDistance, Is.EqualTo(0.0));
            Assert.That(st.D2ShepherdDistance, Is.EqualTo(0.0));
            Assert.That(KmerAnalyzer.KmerDistance(s1, s1, 2, KmerDistanceMetric.D2Star), Is.EqualTo(0.0));
            Assert.That(KmerAnalyzer.BackgroundAdjustedD2("ACGTTGCAACGGT", "ACGTTGCAACGGT", 3, 2, bothStrands: true).D2StarDistance, Is.EqualTo(0.0));
        });
    }

    #endregion
}
