// MOTIF-CONS-001 / MOTIF-GENERATE-001 — reference-tool consensus algorithms (B05 follow-up)
// Evidence: docs/Evidence/MOTIF-CONS-001-Evidence.md, docs/Evidence/MOTIF-GENERATE-001-Evidence.md
// TestSpec: tests/TestSpecs/MOTIF-CONS-001.md, tests/TestSpecs/MOTIF-GENERATE-001.md
// Sources: EMBOSS 6.6.0 nucleus/embcons.c (embConsCalc), emboss/cons.c, emboss/acd/cons.acd,
//          data/EDNAFULL, data/EBLOSUM62 (raw.githubusercontent.com/kimrutherford/EMBOSS + Ubuntu
//          emboss-data 6.6.0+dfsg-12ubuntu2); Biopython 1.85 Bio/Align/AlignInfo.py dumb_consensus.
// Every EMBOSS expected string below is the verbatim output of the EMBOSS 6.6.0 `cons` binary
// (Ubuntu package name em_cons) for the command line in the test description, with the rows
// written to a.fa (FASTA, weight 1) or a.msf (MSF with the listed Weight: values). Dumb-consensus
// expectations are the output of Biopython 1.85 SummaryInfo.dumb_consensus. Generated by the
// cross-check harness (seed 20260930); see the Evidence file for the full run (780 EMBOSS cases).

namespace Seqeron.Genomics.Tests.Unit.Analysis;

[TestFixture]
public class MotifFinder_AlignmentConsensus_Tests
{
    #region EMBOSS cons — reference-locked

    private static readonly TestCaseData[] EmbossCases =
    {
        new TestCaseData(new[] { "ACGTAC-T", "ACGTTCAT", "AGGTAC-T", "tCGAAG-T" }, ConsensusResidueType.Nucleotide, null, 0, null, null, "ACGTACnT").SetName("Emboss_000").SetDescription("cons -sequence a.fa -snucleotide"),
        new TestCaseData(new[] { "ACGTAC-T", "ACGTTCAT", "AGGTAC-T", "tCGAAG-T" }, ConsensusResidueType.Nucleotide, 0.0f, 0, null, null, "ACGTACaT").SetName("Emboss_001").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0"),
        new TestCaseData(new[] { "ACGTAC-T", "ACGTTCAT", "AGGTAC-T", "tCGAAG-T" }, ConsensusResidueType.Nucleotide, null, 4, null, null, "NNGNNNNT").SetName("Emboss_002").SetDescription("cons -sequence a.fa -snucleotide -identity 4"),
        new TestCaseData(new[] { "ACGTAC-T", "ACGTTCAT", "AGGTAC-T", "tCGAAG-T" }, ConsensusResidueType.Nucleotide, 1.0f, 0, 3.0f, null, "acGtacaT").SetName("Emboss_003").SetDescription("cons -sequence a.fa -snucleotide -plurality 1.0 -setcase 3.0"),
        new TestCaseData(new[] { "ACGTAC-T", "ACGTTCAT", "AGGTAC-T", "tCGAAG-T" }, ConsensusResidueType.Nucleotide, 2.5f, 1, 0.0f, null, "ACGTACNT").SetName("Emboss_004").SetDescription("cons -sequence a.fa -snucleotide -plurality 2.5 -identity 1 -setcase 0.0"),
        new TestCaseData(new[] { "AC.TX~", "AC.TX~", "AC-TXA" }, ConsensusResidueType.Nucleotide, null, 0, null, null, "ACnTnn").SetName("Emboss_005").SetDescription("cons -sequence a.fa -snucleotide"),
        new TestCaseData(new[] { "AC.TX~", "AC.TX~", "AC-TXA" }, ConsensusResidueType.Nucleotide, 0.0f, 0, null, null, "AC-Tna").SetName("Emboss_006").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0"),
        new TestCaseData(new[] { "AC.TX~", "AC.TX~", "AC-TXA" }, ConsensusResidueType.Nucleotide, null, 3, null, null, "ACnTnN").SetName("Emboss_007").SetDescription("cons -sequence a.fa -snucleotide -identity 3"),
        new TestCaseData(new[] { "AC.TX~", "AC.TX~", "AC-TXA" }, ConsensusResidueType.Nucleotide, 1.0f, 0, 3.0f, null, "acntna").SetName("Emboss_008").SetDescription("cons -sequence a.fa -snucleotide -plurality 1.0 -setcase 3.0"),
        new TestCaseData(new[] { "AC.TX~", "AC.TX~", "AC-TXA" }, ConsensusResidueType.Nucleotide, 2.5f, 1, 0.0f, null, "ACnTnN").SetName("Emboss_009").SetDescription("cons -sequence a.fa -snucleotide -plurality 2.5 -identity 1 -setcase 0.0"),
        new TestCaseData(new[] { "MKVLAAGIVG", "MKVLSAGIVA", "MRVLAAG-VG", "MKILTAGLVG" }, ConsensusResidueType.Protein, null, 0, null, null, "MKVLAAGIVG").SetName("Emboss_010").SetDescription("cons -sequence a.fa -sprotein"),
        new TestCaseData(new[] { "MKVLAAGIVG", "MKVLSAGIVA", "MRVLAAG-VG", "MKILTAGLVG" }, ConsensusResidueType.Protein, 0.0f, 0, null, null, "MKVLAAGIVG").SetName("Emboss_011").SetDescription("cons -sequence a.fa -sprotein -plurality 0.0"),
        new TestCaseData(new[] { "MKVLAAGIVG", "MKVLSAGIVA", "MRVLAAG-VG", "MKILTAGLVG" }, ConsensusResidueType.Protein, null, 4, null, null, "MXXLXAGXVX").SetName("Emboss_012").SetDescription("cons -sequence a.fa -sprotein -identity 4"),
        new TestCaseData(new[] { "MKVLAAGIVG", "MKVLSAGIVA", "MRVLAAG-VG", "MKILTAGLVG" }, ConsensusResidueType.Protein, 1.0f, 0, 3.0f, null, "MKVLaAGiVg").SetName("Emboss_013").SetDescription("cons -sequence a.fa -sprotein -plurality 1.0 -setcase 3.0"),
        new TestCaseData(new[] { "MKVLAAGIVG", "MKVLSAGIVA", "MRVLAAG-VG", "MKILTAGLVG" }, ConsensusResidueType.Protein, 2.5f, 1, 0.0f, null, "MKVLAAGIVG").SetName("Emboss_014").SetDescription("cons -sequence a.fa -sprotein -plurality 2.5 -identity 1 -setcase 0.0"),
        new TestCaseData(new[] { "HEAGAWGHEE", "PAW-HEAE--", "HEAGAWGHEE" }, ConsensusResidueType.Protein, null, 0, null, null, "HEAGAWGHEE").SetName("Emboss_015").SetDescription("cons -sequence a.fa -sprotein"),
        new TestCaseData(new[] { "HEAGAWGHEE", "PAW-HEAE--", "HEAGAWGHEE" }, ConsensusResidueType.Protein, 0.0f, 0, null, null, "HEAGAWGHEE").SetName("Emboss_016").SetDescription("cons -sequence a.fa -sprotein -plurality 0.0"),
        new TestCaseData(new[] { "HEAGAWGHEE", "PAW-HEAE--", "HEAGAWGHEE" }, ConsensusResidueType.Protein, null, 3, null, null, "XXXXXXXXXX").SetName("Emboss_017").SetDescription("cons -sequence a.fa -sprotein -identity 3"),
        new TestCaseData(new[] { "HEAGAWGHEE", "PAW-HEAE--", "HEAGAWGHEE" }, ConsensusResidueType.Protein, 1.0f, 0, 3.0f, null, "heagawghee").SetName("Emboss_018").SetDescription("cons -sequence a.fa -sprotein -plurality 1.0 -setcase 3.0"),
        new TestCaseData(new[] { "HEAGAWGHEE", "PAW-HEAE--", "HEAGAWGHEE" }, ConsensusResidueType.Protein, 2.5f, 1, 0.0f, null, "XXXXXXXXXX").SetName("Emboss_019").SetDescription("cons -sequence a.fa -sprotein -plurality 2.5 -identity 1 -setcase 0.0"),
        new TestCaseData(new[] { "ACGT", "TGCA" }, ConsensusResidueType.Nucleotide, null, 0, null, null, "acgt").SetName("Emboss_020").SetDescription("cons -sequence a.fa -snucleotide"),
        new TestCaseData(new[] { "ACGT", "TGCA" }, ConsensusResidueType.Nucleotide, 0.0f, 0, null, null, "acgt").SetName("Emboss_021").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0"),
        new TestCaseData(new[] { "ACGT", "TGCA" }, ConsensusResidueType.Nucleotide, null, 2, null, null, "NNNN").SetName("Emboss_022").SetDescription("cons -sequence a.fa -snucleotide -identity 2"),
        new TestCaseData(new[] { "ACGT", "TGCA" }, ConsensusResidueType.Nucleotide, 1.0f, 0, 3.0f, null, "acgt").SetName("Emboss_023").SetDescription("cons -sequence a.fa -snucleotide -plurality 1.0 -setcase 3.0"),
        new TestCaseData(new[] { "ACGT", "TGCA" }, ConsensusResidueType.Nucleotide, 2.5f, 1, 0.0f, null, "NNNN").SetName("Emboss_024").SetDescription("cons -sequence a.fa -snucleotide -plurality 2.5 -identity 1 -setcase 0.0"),
        new TestCaseData(new[] { "AAAA", "AAAA" }, ConsensusResidueType.Nucleotide, null, 0, null, null, "AAAA").SetName("Emboss_025").SetDescription("cons -sequence a.fa -snucleotide"),
        new TestCaseData(new[] { "AAAA", "AAAA" }, ConsensusResidueType.Nucleotide, 0.0f, 0, null, null, "AAAA").SetName("Emboss_026").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0"),
        new TestCaseData(new[] { "AAAA", "AAAA" }, ConsensusResidueType.Nucleotide, null, 2, null, null, "AAAA").SetName("Emboss_027").SetDescription("cons -sequence a.fa -snucleotide -identity 2"),
        new TestCaseData(new[] { "AAAA", "AAAA" }, ConsensusResidueType.Nucleotide, 1.0f, 0, 3.0f, null, "aaaa").SetName("Emboss_028").SetDescription("cons -sequence a.fa -snucleotide -plurality 1.0 -setcase 3.0"),
        new TestCaseData(new[] { "AAAA", "AAAA" }, ConsensusResidueType.Nucleotide, 2.5f, 1, 0.0f, null, "NNNN").SetName("Emboss_029").SetDescription("cons -sequence a.fa -snucleotide -plurality 2.5 -identity 1 -setcase 0.0"),
        new TestCaseData(new[] { "A-", "-A" }, ConsensusResidueType.Nucleotide, null, 0, null, null, "aa").SetName("Emboss_030").SetDescription("cons -sequence a.fa -snucleotide"),
        new TestCaseData(new[] { "A-", "-A" }, ConsensusResidueType.Nucleotide, 0.0f, 0, null, null, "aa").SetName("Emboss_031").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0"),
        new TestCaseData(new[] { "A-", "-A" }, ConsensusResidueType.Nucleotide, null, 2, null, null, "NN").SetName("Emboss_032").SetDescription("cons -sequence a.fa -snucleotide -identity 2"),
        new TestCaseData(new[] { "A-", "-A" }, ConsensusResidueType.Nucleotide, 1.0f, 0, 3.0f, null, "aa").SetName("Emboss_033").SetDescription("cons -sequence a.fa -snucleotide -plurality 1.0 -setcase 3.0"),
        new TestCaseData(new[] { "A-", "-A" }, ConsensusResidueType.Nucleotide, 2.5f, 1, 0.0f, null, "NN").SetName("Emboss_034").SetDescription("cons -sequence a.fa -snucleotide -plurality 2.5 -identity 1 -setcase 0.0"),
        new TestCaseData(new[] { "RYKM", "SWBN", "ACGT" }, ConsensusResidueType.Nucleotide, null, 0, null, null, "nnnn").SetName("Emboss_035").SetDescription("cons -sequence a.fa -snucleotide"),
        new TestCaseData(new[] { "RYKM", "SWBN", "ACGT" }, ConsensusResidueType.Nucleotide, 0.0f, 0, null, null, "rykn").SetName("Emboss_036").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0"),
        new TestCaseData(new[] { "RYKM", "SWBN", "ACGT" }, ConsensusResidueType.Nucleotide, null, 3, null, null, "NNNN").SetName("Emboss_037").SetDescription("cons -sequence a.fa -snucleotide -identity 3"),
        new TestCaseData(new[] { "RYKM", "SWBN", "ACGT" }, ConsensusResidueType.Nucleotide, 1.0f, 0, 3.0f, null, "rykn").SetName("Emboss_038").SetDescription("cons -sequence a.fa -snucleotide -plurality 1.0 -setcase 3.0"),
        new TestCaseData(new[] { "RYKM", "SWBN", "ACGT" }, ConsensusResidueType.Nucleotide, 2.5f, 1, 0.0f, null, "NNNn").SetName("Emboss_039").SetDescription("cons -sequence a.fa -snucleotide -plurality 2.5 -identity 1 -setcase 0.0"),
        new TestCaseData(new[] { "KCKBKRKKMGKCKACHMCDTUSTKTY", "HCCGSYBWARGDNGVDHRVYRDKWBV", "VUSBVDNTSSTVYMHUAWUNCYTMBA", "VGYTKMGCNUTBCANUGBHGUTYGVV", "RVWVBRKNYMBUNWNWKVMBVHGRTM", "RNVBHVTMRHYSYHUHCHWUTWVTGW", "UKKCKDHSNHDNWAKDUNCCKSCATS", "RKMDYBTGVAADYNTVSAKVKWTDWN", "YCUWMBSYUDBUHNKUMTKHSMRAMU" }, ConsensusResidueType.Nucleotide, 9.25f, 0, 10.25f, new float[] { 3.0f, 0.25f, 0.75f, 1.0f, 0.75f, 0.5f, 0.75f, 2.0f, 0.25f }, "nnnnnnnnnnnnnnnnnnnnnnnnnn").SetName("Emboss_040").SetDescription("cons -sequence a.msf -snucleotide -plurality 9.25 -setcase 10.25"),
        new TestCaseData(new[] { "UTRTYWDMUT-SDRWBCVG-G", "UTRBYKDYUTTSTRWBCVGCG", "ATRBYWD--TTSTRW-CVGCG" }, ConsensusResidueType.Nucleotide, 3.75f, 0, 0.0f, new float[] { 1.0f, 1.0f, 2.0f }, "NTnnnnnnNTNnNnnnCnGNG").SetName("Emboss_041").SetDescription("cons -sequence a.msf -snucleotide -plurality 3.75 -setcase 0.0"),
        new TestCaseData(new[] { "GMWGYGSHUHAHN.GB--DC-NCAKARMVTCNKHV", "GMAKYRSNU.AHSTG-GWAU-NCAKCDCV-CNDCD", "TM~GRRSBUCBHS-GB-BAMTNCAKCDMVTCNHCM", "GMGGY.--UHG-STGNSWA-ANVA-CDWVU-NHSM", "~MGTYRSBWHA-SGGBGWAUYN-ARCDMV-CSRSM" }, ConsensusResidueType.Nucleotide, 0.0f, 3, null, null, "GmNGyN-NUNA-nNG-N-ANNnCA-CrNvNCnNNv").SetName("Emboss_042").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0 -identity 3"),
        new TestCaseData(new[] { "AGGTAATAGCGATTAGACATCCGTATGTT", "AGGTAAGAGCGATTACACTTTTGTAAATT" }, ConsensusResidueType.Nucleotide, null, 0, 0.0f, null, "AGGTAATAGCGATTAGACATCCGTATGTT").SetName("Emboss_043").SetDescription("cons -sequence a.fa -snucleotide -setcase 0.0"),
        new TestCaseData(new[] { "GUYDRAc", "YcuBrAD" }, ConsensusResidueType.Nucleotide, null, 0, 0.0f, new float[] { 0.5f, 0.25f }, "GUUnnAC").SetName("Emboss_044").SetDescription("cons -sequence a.msf -snucleotide -setcase 0.0"),
        new TestCaseData(new[] { "-CC----AAACGA-GC-GCTTT", "-CCAAGAA-ACG-GGCCGC-TT", "T-GAAGT-AACGATG-CG-TTC", "AC-AC-TA-AC-AGGCCG-T-T", "T-C--GTAAA-GAGGC-GCTT-" }, ConsensusResidueType.Nucleotide, 0.0f, 0, 0.0f, new float[] { 2.0f, 1.5f, 3.0f, 1.5f, 1.5f }, "TCCAAGTAAACGAGGCCGCTTT").SetName("Emboss_045").SetDescription("cons -sequence a.msf -snucleotide -plurality 0.0 -setcase 0.0"),
        new TestCaseData(new[] { "MGwNRCBCAnS", "MgWRRCByaNS", "MGWRrcBYAnS", "YGwRrCWYANS", "MGVRrCYyANS", "MGwRRcbyABS", "MgWRrCBKANs", "MgWrRcbYGNS", "MGWRRcByANk", "MgWrrCBYaNS" }, ConsensusResidueType.Nucleotide, null, 6, null, new float[] { 0.5f, 1.0f, 1.0f, 2.0f, 3.0f, 3.0f, 3.0f, 0.5f, 1.0f, 0.5f }, "nGnnnCnNAnn").SetName("Emboss_046").SetDescription("cons -sequence a.msf -snucleotide -identity 6"),
        new TestCaseData(new[] { "UWC-RWUNH-YDW--U-YNAGGSY-W-V-BB", "--CN--MU-RW-WM--S-HRMGY---YN-UB", "--KKHUY-TRUN-K-UNRKA-DR--Y-KSWB", "KRU-TYSMA--NWA-BA---SH---BS-D--", "KNCNC-SAM-UU----Y-RAKANYHHY-YSB", "NNUAKWVUA-MNWNWVGDVNKGBG-HD-VCK", "-NCKWWN-HR-NNM-K-KVHCMV-VR-N-V-", "-NC--VSUNUDN-K-UG-W-KGUYH-Y-V-B", "-SCV-KSUH----M-UUS-SKKWSH--UTGB" }, ConsensusResidueType.Nucleotide, 6.75f, 0, null, new float[] { 0.5f, 0.25f, 0.75f, 2.0f, 0.25f, 0.25f, 0.75f, 0.5f, 1.5f }, "nnNnnNnnnnnnnnnNnnnnNnnnnnnnnnn").SetName("Emboss_047").SetDescription("cons -sequence a.msf -snucleotide -plurality 6.75"),
        new TestCaseData(new[] { "RVCKYNAWRBCGKSVBGDVDWTTGHY", "HWUMGWRKBUCTASGVAMMDRKTUUY", "DMTTMNMHWDNCYWBBCDMDBTTUKN", "HYUGNHSWRKCKGUVAWWKYWUTUCB", "YAMTMASHRGCARUABGTCHWUGCBV", "STDMHNYWBMAAKSCDGWNCWATDUU", "BHMUVWGSHCVRHSWMGTKVMRTUUY", "UMDTKNSNNGBVGDCADKSHHTTKUY" }, ConsensusResidueType.Nucleotide, null, 0, 9.0f, null, "nantnngnnncngnnngtcnnttuuu").SetName("Emboss_048").SetDescription("cons -sequence a.fa -snucleotide -setcase 9"),
        new TestCaseData(new[] { "GCG", "-CG" }, ConsensusResidueType.Nucleotide, 1.25f, 0, 0.0f, new float[] { 1.0f, 0.25f }, "NCG").SetName("Emboss_049").SetDescription("cons -sequence a.msf -snucleotide -plurality 1.25 -setcase 0.0"),
        new TestCaseData(new[] { "TTTCTTGCGGGGTGAGGTGGG", "TCCCCCGGACGATCGACGCAA", "TAATTCAATACGCCCTACTTT", "GGGGTGGGGTAACACCAACTG", "TTCCGAAAAGCGCTGCTCATC", "CCCATGGAACTGACGCAGTTT" }, ConsensusResidueType.Nucleotide, 3.25f, 0, null, null, "TnnnTnGnnnnGnnnnnnnTn").SetName("Emboss_050").SetDescription("cons -sequence a.fa -snucleotide -plurality 3.25"),
        new TestCaseData(new[] { "CGTCTGATTGTCGACATCATGACAGACAAAAAC--AG--GCCAT-CG", "GTTCCTTCGGTGT-TCTAACGGTCTCCAT-CGG---GGCGACG--G-", "--GG-CAGT-TACAAAAAGGACCCTG-AACGCCCAAAGCGT-C-GGG" }, ConsensusResidueType.Nucleotide, 3.0f, 0, 4.0f, null, "nnnnnnnnnntnnnnnnnnnnnnnnnnannnnnnnnnnngnnnnnnn").SetName("Emboss_051").SetDescription("cons -sequence a.fa -snucleotide -plurality 3 -setcase 4"),
        new TestCaseData(new[] { "-dTgUwMgDDMHUC", "VhMUWGccUDUhUY", "mGVMsKAC-VHMVa" }, ConsensusResidueType.Nucleotide, 3.0f, 0, null, null, "nnnnNnNNnnnnNN").SetName("Emboss_052").SetDescription("cons -sequence a.fa -snucleotide -plurality 3"),
        new TestCaseData(new[] { "AAKS", "CHKS", "ACKS", "BCKS", "ACKS", "ACKS", "ACHY" }, ConsensusResidueType.Nucleotide, 3.25f, 0, 0.0f, null, "ACnn").SetName("Emboss_053").SetDescription("cons -sequence a.fa -snucleotide -plurality 3.25 -setcase 0.0"),
        new TestCaseData(new[] { "T--G-CTATTCTGTAG-T--TGCATAAGGG-TA-CACC-CCTGA-G", "--AT-TGT--CCCATGACA-G-CTGG-TA-G-GACTT----TCGC-", "T-TG--CA-CAAGCTCG-C--A--TGCAT-C-GCTCAT-AGTGGAT", "T-CG-GGAGT-CC-TTA-C--CGAAGTGAC-A--AAATC-TCCG-A", "TGATC-A-G-TGAT--GCCG-A-GCAAT-G-ACCGGA--TTGCTT-", "CCGC-G-A-CGAGTAA-ACCACTTGCT-CT-T--CA-AT-ATTC-G", "GA-C-TC-G-AGAACCTAGACC-CGCT-GT---TTATTA-GCCTTT", "--ACGTA-CCAACCGCCGGAGT-C-CA-A-C-A-GGG-GAAC---C", "GGT--TC--G-GAG-CTCT-TG-C-ACGG--G-A--T-TA-GT--G", "TA--AG---TTGAATC-T-T--AACT-A-TACAGCCC---AT--T-", "ATT-CG---C--GTCCCG-TAAA--GG-CG-ACAG-CCT-G--TTG" }, ConsensusResidueType.Nucleotide, null, 3, 3.25f, null, "NNnnNnnNnnnnNnnCNnnNNnNnnNnnnnNnnnnnnnnnnNnnNn").SetName("Emboss_054").SetDescription("cons -sequence a.fa -snucleotide -identity 3 -setcase 3.25"),
        new TestCaseData(new[] { "CGGTTGCTAACTTACGCTAGGAATTCTTGCGTATATTCGGAGGTCA", "TTTTGGTTCACATCTTGTAGTAAATCTGCCGTGTATAGAATGTTTC", "TTCCACGCTCCGTAGTCAGGCCGGCCTCGGGTATATGGCAGCATCT", "CTCCAGTACTGCTCGAGAACAACCGCTGCGGTATCAGCAATCGTAG", "AGTCATTTTACACACTTTAGTCGGCCTCTGGTATCCGGCAACGTAC" }, ConsensusResidueType.Nucleotide, 5.0f, 0, 0.0f, null, "NNNNNNNNNNNNNNNNNNNNNNNNNCTNNNGTNTNNNNNNNNNTNN").SetName("Emboss_055").SetDescription("cons -sequence a.fa -snucleotide -plurality 5 -setcase 0.0"),
        new TestCaseData(new[] { "KHWWWUNBYBSKYVATSWRHS", "KHSWRUNBYBVAWVATTCRYH", "KHSWTGNBYBURWCATUWRMH", "KHSWWANUYBURYVATTVRTR", "HHSWSBRMYYSDYAVTTWRMH", "KBSWTUNBHBUWYVATTWRMV", "KTSWWYNBYBURBVRTSWRMH", "KHSNAWNBYNURYMATKWMMK" }, ConsensusResidueType.Nucleotide, 5.0f, 0, 0.0f, null, "nNnnTUnnnnUAnNATTnnnn").SetName("Emboss_056").SetDescription("cons -sequence a.fa -snucleotide -plurality 5.0 -setcase 0.0"),
        new TestCaseData(new[] { "tTGTCGgcGGCagGTCGaCACAacccgGgCcGtaCaacCCaAATGTTC", "TttccaGgGTAagGTcgACaCTAATCGgACAgTCGcAaTcAAAccTgC", "AgTACGGtATGaGATcGacAATAcTAGgGcaAGCGCAATCAaaCgtTC", "aATCggGTCTAaAtTCgaCAcTaCtCgGCCCcAGCgAaTcaATagttc", "CtTccgGtGGaaGGTcGACAcTAATcGGcCaCGGgCAaTCAATCtttA", "AtTCCGGTGTAAGGtCGacAATAGTacggcAACAGGCATcAATCgTAC", "CgTccCGtgCAAGGAcGAcActAcTCagGtaGGaGCAaTCACTCcTtC", "TTCcCGgCgGAAGGTAcatAcAACtCGGGCAGaAGGaAaTTATCaCTC" }, ConsensusResidueType.Nucleotide, 10.25f, 5, null, new float[] { 1.5f, 0.75f, 3.0f, 0.75f, 1.5f, 0.5f, 2.0f, 0.5f }, "NNNNNNGNNNNANNNNNANANNANNNNGNNNNNNNNNNNNNNNNNNNN").SetName("Emboss_057").SetDescription("cons -sequence a.msf -snucleotide -plurality 10.25 -identity 5"),
        new TestCaseData(new[] { "G", "A", "A" }, ConsensusResidueType.Nucleotide, null, 1, null, null, "A").SetName("Emboss_058").SetDescription("cons -sequence a.fa -snucleotide -identity 1"),
        new TestCaseData(new[] { "KTTSCNRMBHGHTRVUGDGDR", "NTCWSNSKNRUDTRRGGCUGU", "KUCWCNVMBSGHTRVUGDGGU", "KTDWCKSMNSGHTSAUGRGGU", "KTCWCMSANSGHTRVUGDGGS", "KTCWNNSCNSGHTDVCGAAKU" }, ConsensusResidueType.Nucleotide, null, 0, 0.0f, null, "nTCnCnnNnnGnTnNUGNGGU").SetName("Emboss_059").SetDescription("cons -sequence a.fa -snucleotide -setcase 0.0"),
        new TestCaseData(new[] { "MDRBARVDYYSND", "MDRKARVDYYSND", "MDRKARVDYYSND", "MDRKARVDNYSND", "MDRKARVDYYKND", "MDDKARVKYYSMD", "MDRKAMVMYYSND", "MDRKARVDTYSND" }, ConsensusResidueType.Nucleotide, null, 6, 0.0f, null, "nnnnAnnnNnnnn").SetName("Emboss_060").SetDescription("cons -sequence a.fa -snucleotide -identity 6 -setcase 0.0"),
        new TestCaseData(new[] { "UVW", "YDA", "VVM", "UNW", "HBN", "VGK", "KRA", "VKM" }, ConsensusResidueType.Nucleotide, null, 8, 0.0f, null, "NNN").SetName("Emboss_061").SetDescription("cons -sequence a.fa -snucleotide -identity 8 -setcase 0.0"),
        new TestCaseData(new[] { "DVMAVRDUGD", "WVMAVRSUGD", "-VMAVNDYG-", "HVMAVRN--D", "HVWAVSD-GV", "HV-AVR-UYD", "HVMAVRD-GD", "-V-AVNDUGD", "UTMAV-CUGD", "CVMMV-BG-D", "HBMAKR-UGK" }, ConsensusResidueType.Nucleotide, null, 0, 2.5f, null, "nnnAnnnUGn").SetName("Emboss_062").SetDescription("cons -sequence a.fa -snucleotide -setcase 2.5"),
        new TestCaseData(new[] { "-gVSTcWkDn-DbKURnr-HCTwDUMAH", "dGhSMCTnDNAdBSuV-RHKKDWdAwah", "D-UTtCtkDNtVBSUCnRUHdMWDUHAH", "DUUC--TKDNBdBTSDNrAHkTw-uWAH" }, ConsensusResidueType.Nucleotide, 2.0f, 2, null, null, "nguNtCTnnnNnnNUNnnNnNtnnUnAn").SetName("Emboss_063").SetDescription("cons -sequence a.fa -snucleotide -plurality 2.0 -identity 2"),
        new TestCaseData(new[] { "cCGCATcGCGtCACgCACAGaT", "TACGcCTGaTGTctGGCTCgAG", "aaCAgCGaGTTcGCGtTggGgA", "ACCGCCCGcCtCCGcaCACaTC", "CAAactCTCcGcTCgTTAccCA", "GacAACgGCCAACGTctGCTGG", "GttAaCaAATTaAcAGgCtCaC", "CcGTTAgcGGAAGtTcCggCaT", "tCACAtGTTAAGcCttGCcGtT", "GAcCccAGAGAACttGCAtTCC", "CtGAgTATatcCAcGGTaTtGC" }, ConsensusResidueType.Nucleotide, 0.0f, 0, null, null, "cacaaCggcttccCggcacgac").SetName("Emboss_064").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0"),
        new TestCaseData(new[] { "--GCGGGTCAG-TA", "GCGCGGG-CTGCTA", "GCTCGGGTCAGCAA", "GCGCGGGT-AGCTA", "GCGC-GGTCAGCTA", "G--C-GGTCACCTA", "GCGCG--TC-GCTA", "ACGC-GG-CAGCT-", "GCGCGGGTCAGCTA", "G-GCGGG--GGCTA", "GCGCGGGTCA-CTA", "GCGCGTGTCAGCTA" }, ConsensusResidueType.Nucleotide, 0.0f, 0, 13.0f, null, "gcgcgggtcagcta").SetName("Emboss_065").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0 -setcase 13"),
        new TestCaseData(new[] { "YGYVMWST", "CTYGSDCD" }, ConsensusResidueType.Nucleotide, null, 0, null, null, "ygnnnnst").SetName("Emboss_066").SetDescription("cons -sequence a.fa -snucleotide"),
        new TestCaseData(new[] { "MN-KAWD", "RNRSAWW", "RGD-A-W", "VNDUAWN", "BNDSAK-", "WVDKAAN", "RNDSAUW", "RNDSAWW", "R-DS-WW", "DNDYAWV", "RN-SARW", "RU-CABW" }, ConsensusResidueType.Nucleotide, 0.0f, 0, 0.0f, null, "r---A--").SetName("Emboss_067").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0 -setcase 0.0"),
        new TestCaseData(new[] { "-USNVYB-CT-SN-CKV-A-", "TBBW--VCDDS-DNYSC-H-", "DSBSACUUSUHA-VSTVDTR", "KWHS-B-GNDRAM-RUAU-K", "BA-SGVD--H--TDKHAH--", "BB-T---TSVNSKTUUNRHM", "-TD-BG--GGCMVBHGB-AB", "DSCYG-UCKMDRR----R-N", "N-HURGH-TD--CTTT-HHD", "H--WCCNMCV-WDDMBG--N", "S-A-S---K-YKW--NUN-B", "-ST--HHAU-BSR-TT--TY" }, ConsensusResidueType.Nucleotide, 11.25f, 8, 0.0f, null, "NNNNNNNNNNNNNNNNNNNN").SetName("Emboss_068").SetDescription("cons -sequence a.fa -snucleotide -plurality 11.25 -identity 8 -setcase 0.0"),
        new TestCaseData(new[] { "CC-T--GA-ACG", "-CTAT-GACGCC", "C--AC---GAC-", "-GT-TT--CCAG", "---ATGT-T-TC", "-CG-T--AGCC-", "GC--G-G-A-G-", "TG---G-CGC-G", "GT--TC--AGTA" }, ConsensusResidueType.Nucleotide, 4.0f, 0, null, null, "ncnnTnnnnnnn").SetName("Emboss_069").SetDescription("cons -sequence a.fa -snucleotide -plurality 4.0"),
        new TestCaseData(new[] { "GC-N-RBYT-MR-G-K-", "NS-NBVR-C-VGNC-MS", "GD-N-BMHBRA-NMN-U", "-D-S-SH-DRUCHMN-A", "-SSA-KR-DR-CNGYBG", "--N-MNRRRRAVY-N--", "G-NBS-Y--AV--GY-Y", "K-W--NSW-YMN--N-Y", "VDV-Y-GRARAU--R-N", "R-N--M-RD-AV-G--S", "DYVNS-RN-RA--G-V-" }, ConsensusResidueType.Nucleotide, 6.25f, 0, 2.0f, new float[] { 0.75f, 0.5f, 2.0f, 1.0f, 0.5f, 3.0f, 0.5f, 0.5f, 3.0f, 2.0f, 0.5f }, "NnnnnnnnnAAnnNnnn").SetName("Emboss_070").SetDescription("cons -sequence a.msf -snucleotide -plurality 6.25 -setcase 2.0"),
        new TestCaseData(new[] { "TCGACAGGGCCTCCG", "TCTACGGGGCCTCCG", "TCTACGGGGCCTCCG", "TCTACGGGGCCTACG", "TCTACGGGGCCTCCG", "TCTACGGGGCCTCCC", "TCTATGTGGCCTCCG", "TCTACAGGGCCTCCG", "TCTTCGGGGCCTCCG" }, ConsensusResidueType.Nucleotide, 0.0f, 6, null, null, "TCTACGGGGCCTCCG").SetName("Emboss_071").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0 -identity 6"),
        new TestCaseData(new[] { "ATVMURAGCUCWBADRSBYSAAR", "ATVMURAGCUCWKADNSBYSABR", "ATVMURAGNUCWKADNSBYSABR", "ATVMURAGCUCRKADNSSYSABR", "ATVMURAGCRCWKGDNSBYSABR", "ATWMURHGCUCNKADWTCYSABR", "ATVNURAGCUUWKADNSBYSABR", "ATVGUBAGCVCWKADNABYSAGR" }, ConsensusResidueType.Nucleotide, 0.0f, 0, 0.0f, null, "ATvnUrAGCUCnbAdnsSysAbr").SetName("Emboss_072").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0 -setcase 0.0"),
        new TestCaseData(new[] { "TAGCCTCGTAAGGATCTGAAAT", "TGTCCACGAAGCAACCTTTTCC", "ATCTGTCACGACGACATATGTG", "GGACCGCAGGAGCATTATTTGA", "ACGAATTGTAAGCATAACACTC", "GGGGTGCATACACTAAACTTGC", "CGAGGACTAGTGCCAATTCCAA", "ACGCCGCGAAATTATAATTACC", "GGACTGCCAAAGCTTCATTCAC", "GGGGCTCGAGAGAATTATAAGC", "TCGCGTCGCACACCTAGCGGGG" }, ConsensusResidueType.Nucleotide, null, 0, null, null, "nGGCnnCGnAAGCATAATTnnC").SetName("Emboss_073").SetDescription("cons -sequence a.fa -snucleotide"),
        new TestCaseData(new[] { "ggc.TATT-tCgt-g-C--AaATTa-AA---GATcTA---c-c----AC-", "GAGGa~TGA--A--Gtc--A---G-CTC--a-AGg--tGA-Ggc-A-Ct-", ".c-GCA-g-GACc-CcT--Gg---GA--TtcA--GG----AAcAacA-G-", "~T-gtCCat-A-g-CTgcC---g--CG-tG--C-AA---G-GggTAAgT-", "~AgcG-A-GT--C--gT-aTA-G-A--T-G--GCGa-AcT-CGGT-A-Tt", "A.gCGGGGA-t-A-c-CAGTACGAcc-gGTa-TT-AA-CatG--CGCGA-" }, ConsensusResidueType.Nucleotide, 0.0f, 2, null, null, "g-ggt--g-t-N--c-cNN-aNgN-cNNt-aN--gaaNc-Ngg---a-tN").SetName("Emboss_074").SetDescription("cons -sequence a.fa -snucleotide -plurality 0.0 -identity 2"),
        new TestCaseData(new[] { "-M-TIW--SL--FTCDI--AVR--K-VG-F", "CI-T-Y-HEDT--N-CN-SRYR--MHVGH-", "C---IW-H--S-K-CCG---V-WLMGV-YD", "C-LTISPEP-T-FF--Q-Y-AR-LWSVG--", "CILTIW-H-CL--YC-QI-RP-WP--VGNG", "SI---YPHP--DF--C-HF-VRWLQC--WG", "-LLRWAPHPCTDF--CQIFAV-ERMH-G--", "--L--WPH--TLFNMC-I---APL-HVE-G", "CDLTI--HPLTD-N-C-IFAVRWLMHVRYG", "----EW--PCH--NCC-IC---QRMHVLYI", "CT---WP-P-GVF---QIFAV--V---GYG", "CI--IWPHW-TD-RCC---TV--WMHV-YG" }, ConsensusResidueType.Protein, 0.0f, 0, 0.0f, new float[] { 3.0f, 0.5f, 1.5f, 2.0f, 2.0f, 0.75f, 0.25f, 0.5f, 0.75f, 1.0f, 0.5f, 2.0f }, "CILTIWPHPCTDFNCCQIFAVRWLMHVGYG").SetName("Emboss_075").SetDescription("cons -sequence a.msf -sprotein -plurality 0.0 -setcase 0.0"),
        new TestCaseData(new[] { "STMMMFNDSIDGANPGRNHTK-FERV", "SAMEMFEDPAIKWQCGR-HTVYFETV", "S-SHPF-DMIIGW-WTSNFLK-FER-", "SA--MFNDWIFGWMPGRN-W-YFERV", "SAMHMF-DSIIGWNV-RN-TKLFERV", "S-MHMYNESP-IWNLGRNHWA-FHRS", "IAMHMFN-GIEI-NPQRNHTMGF--V", "-RTHMFND-IIGWNKGR-WTKRFEHV", "SAMHKF-ESGI-SNPGRNETKYFERV" }, ConsensusResidueType.Protein, null, 0, 3.5f, null, "SAMHMFNDXIIGWNXGRNXTKxFERV").SetName("Emboss_076").SetDescription("cons -sequence a.fa -sprotein -setcase 3.5"),
        new TestCaseData(new[] { "EPCDSBQWGWADKBIYNZXBPYHCFIPBMEMMPAIMVGCHKAQQH", "EPCDSBQWGYADKZIYNZWBPYXCFIXBMFMMPAIMVGCHKAQQH", "EPCDABQPGWADKZIYNZWBPYLCFIPBMEMMPAIPVGCHKAQQH", "EPCDSBQWGWGDKZIYNMPBPYLCFIPBMENMPAIMVGCHKAQQN", "EPCKSBQWGWADRZIYNZWBPYLKFIPBMEMEPAIQVGCHKAQQH", "EPCDSBBWGWADRZIYNZWBPYLCFIPBMEMMPAIMVGCHKAQQH", "EPCDSBWWDWADKZIYNZWBPMLCFIHBMEMMPAIMVGCHKAQQH", "EPCDSBQWGWADKZIYNZWBPYLCFIEBMEMMPZIMVGCHKAQQN", "EPCDSBZWCWADKZIYNZWBPYLXFBPBMEMMPKIMVXCHKAQQH" }, ConsensusResidueType.Protein, 5.5f, 0, null, null, "EPCDSBQWGWADKZIYNZWBPYLCFIPBMEMMPAIMVGCHKAQQH").SetName("Emboss_077").SetDescription("cons -sequence a.fa -sprotein -plurality 5.5"),
        new TestCaseData(new[] { "MV-PSLMTLHKGQNICKFEHPAAVQFK-YHLDN", "MVCMSLMTLHKGQNICKFEDFAFV-TKMYHLFN", "-VSK-LMTLHKG-NICKFERFAYVS-KMSHLFN" }, ConsensusResidueType.Protein, null, 2, 4.0f, null, "mvXXslmtlhkgqnickfeXfaXvXXkmyhlfn").SetName("Emboss_078").SetDescription("cons -sequence a.fa -sprotein -identity 2 -setcase 4"),
        new TestCaseData(new[] { "rYASGQGILBvLrSzIYYHiwlIYXDzBBwnRvKas", "TZvEGPlIXBVlRYnVWzHBwlYypRHbGNRHnkIV", "TFVKgHMibMPpRfsvFzhBWLIGXDzTBNrHBKAV", "TCWSGHMiBbVlASNVhZBBWlaynHgBBfrHNKAV", "IzVFeSPIBBVLRAnVEqEBwZiyHEzHqgRHNAMV", "rWVSshmIbbvLRANVhzHBwLiYxDZBRNrfNQaF", "CZVDGhMIVBvLRSsvyzHRzAwWXezBBQrpNkaV", "tTVSGgMIbBmHKSNvYZHCWMivXDzPHNhSnKxv", "PZVSGhBfBBDLDsnvYHhBYFIWLBYBrnRHNKcv", "MVyCVhMIBBVLRSXvFZHBkLRyGZZBBnRHNKAM" }, ConsensusResidueType.Protein, 0.0f, 0, null, new float[] { 3.0f, 1.5f, 2.0f, 0.25f, 1.0f, 3.0f, 2.0f, 0.5f, 0.75f, 1.5f }, "tYVsGHMIBBVLRSNVYZHBWLIYxDZBBNRhNKAV").SetName("Emboss_079").SetDescription("cons -sequence a.msf -sprotein -plurality 0.0"),
        new TestCaseData(new[] { "--AA---SFRGVK--S-G-SffIAVy-D-Ih-Nt-Yms", "aWALd--R----M-qsi-P-RF-SVRT--I-LvNwYAS", "lLH-NRhd-GgLkMQsM-PfK-IA-RTD---cqNeWm-", "--adI-HpSG-v-MQsigK-KdiavRRDQR-AT-GMMS" }, ConsensusResidueType.Protein, 4.0f, 0, null, null, "xxXxxxxxxxxXxxXSXxxxXxXAXXxXxxxxxxxXXX").SetName("Emboss_080").SetDescription("cons -sequence a.fa -sprotein -plurality 4.0"),
        new TestCaseData(new[] { "KLMATTC", "LVFYFMT", "DWS-MPR", "-N-FEWC", "APTKFLK", "VCQ-MNQ", "PKPIKKR", "A-EI-RH", "MAGANEP" }, ConsensusResidueType.Protein, 7.75f, 0, null, null, "xxxxxxx").SetName("Emboss_081").SetDescription("cons -sequence a.fa -sprotein -plurality 7.75"),
        new TestCaseData(new[] { "EW-MR-TKWSPFVDARAPL-YKHCKMHTFK-T-MYECEQFRVM", "Y-MYEEH-HIKYPALMRCDHWWRCTHCSGTRPS--EMC-CTEF", "LYIDAMKGGKRES--ILPNVT-WNHG-MPCQQWEATYYWVMGH", "-IRICCYY-RNIVYF-HKWLAQTCIRI---LI-KPNWAIDTPK", "TNGYFCMNFVITKCHNLESDTVALECHKRDNVLPRK-HPCRRC", "KCHT-WY-FWSPIMSNQKVQAFTHEVCTCFKAVYKFSMNHQQM", "PQPW-ATLF-HIPVHSDVTWG-CAEAAGNSMEGRPNKRWQT--", "WCWAWGLKMIYDKSTFNNASY-R-NRWNEIS-VDMPER-RIRV", "---YNVLHYTENVRQAEDLCTVVAQWTILVTSKTW--SNMATM", "-LFL-AVNYP-PYW-DSEKPTT-QEPQMKAGFKNQP-EAAHKW" }, ConsensusResidueType.Protein, 6.5f, 0, 0.0f, new float[] { 3.0f, 0.25f, 1.0f, 2.0f, 3.0f, 0.5f, 3.0f, 2.0f, 0.25f, 0.5f }, "xxxYxXXXFxxXXxXNXXXxXXxXEXXXxxxxxxxXxXXXXXX").SetName("Emboss_082").SetDescription("cons -sequence a.msf -sprotein -plurality 6.5 -setcase 0.0"),
        new TestCaseData(new[] { "ZfyVbvvnCtHQQGfHZWnPdWG", "zfYVBVVNCThqQgZhKQNPFLG", "ZFYVBVVNCtHqQGFHZQnBDLG", "zFyVBVvNCTHQQgDhZVNpDLG", "ZIevBqvNkTHQQGFHEQnpplg", "zfYvBVVNCtHDqgfHZQNPdLG", "ZvYvbVVNCthqsgFHZQNpdlg", "ZFdGbvvncRhQQGfHZHBpDlG", "ZFyvBVVNCTHRqGFHZQnpQLG" }, ConsensusResidueType.Protein, 9.0f, 6, 10.0f, null, "zxxxbxvnxxhxxgxhzxnxxxg").SetName("Emboss_083").SetDescription("cons -sequence a.fa -sprotein -plurality 9 -identity 6 -setcase 10"),
        new TestCaseData(new[] { "-RhF--Y-F--tV-LwW--Y-mMs--pSQ", "FTI-QEC--RTShkETPPWr-N-A-ESAL", "K-nY--Shys-Pitqi-PTDTKSRPlK-c" }, ConsensusResidueType.Protein, null, 1, null, null, "xxHFxxxxFxxTVxQxxPxxxxxSxxxSx").SetName("Emboss_084").SetDescription("cons -sequence a.fa -sprotein -identity 1"),
        new TestCaseData(new[] { "CISRWMMRDNVTAHAMTILZAKHEKNZXXSRHR", "AISREMMRNNVTFHAMTTLZAKCEGNZXNSRHR", "RISRRMMRDNVTYHNDBGLZWKCEFNZXXSRKR", "AISREMMRDNVTYHAMYTLZAKCEKNZXXSRHR", "AISREMMRDNVTEIRMMTLZAKCEKNZXXSYHR", "SISYVMMRDNVTFHAMTTLZAKCEPNZXISRHR", "AISREMCRDNVTEHAMTTXZAKCEYNZXXSRHR" }, ConsensusResidueType.Protein, 1.5f, 0, null, null, "AISREMMRDNVTYHAMTTLZAKCEkNZxxSRHR").SetName("Emboss_085").SetDescription("cons -sequence a.fa -sprotein -plurality 1.5"),
        new TestCaseData(new[] { "WLYQILMSWYFMCNDHZSDGWZLAIPRWQMPMEEFVZMLBABLTXGRFEK", "TPDQTVXPYYMAZBQDGPERXPKQPGHWBMRQYEENWKGBBMKEYXXVZY", "QLDSHPRWFTLBDGMXNVEHWEPAIHADQHQVESTTEEABPKTTFCWKYF", "HXIPNZKGVYWADBKTRTELGCAEIGZSQMEQCVEXEKTBAZVTFCKZVB", "VLRQMCRQFYWCHIGFZPELWAHYIGYAQMPELBDXERGBXRKLEPSFZZ", "GNDQWQCHFYXFLBCAEPSMYQLAZGGWEMFVEEGRSYGKXZHIMFGBZK", "EFESFLRMCYWAWWWGZPPVBWLALTGWQGPVEBEXEKGBSZMTSPDMZP" }, ConsensusResidueType.Protein, null, 0, 8.0f, null, "xxdqxxrxfywxxbxxzpemwxxaigxwqmxveeexekgbxzxtxxxxex").SetName("Emboss_086").SetDescription("cons -sequence a.fa -sprotein -setcase 8"),
        new TestCaseData(new[] { "WD--YTKCD-GN--AKV-S-FM--P-P-C-PRWFMT-A", "DDSA-TK---GNLTA-LG--FM-F--PNCAP-WFITGP", "DDSA-TKCDNGNL---DGSRWMCFPMPNCA-RW-WTGP", "-DHA-FDC-QGNL--KD--DFMCF-MANCAPRWFWTQP", "-DS-YTKCDWG---A-D-S-NM--PMPNCAPRW-WTGP", "DDRAY-MCDNF-LTAKNGSD-MC--MPN-QPRWFWTGP", "DDCD--KCMNG--TAK--SD-M-FP-PECA-RWFWTGP", "DD-AYTKCDNGNLTAKDG-DFMC-P-PN-AP-W-WM-P", "-D-AY-K-DN-NL---DG--FMC-P-PNCA--W-WT-P", "-D--YTKCDNGNLTA-DHS-FDAFPS-NEA-RW-WT--" }, ConsensusResidueType.Protein, 0.0f, 1, 6.5f, new float[] { 0.5f, 0.75f, 1.5f, 0.25f, 0.5f, 0.5f, 3.0f, 0.25f, 0.75f, 1.0f }, "dDsaytKCdNGnltakdgSdfMcfPmPnCApRWfWTgP").SetName("Emboss_087").SetDescription("cons -sequence a.msf -sprotein -plurality 0.0 -identity 1 -setcase 6.5"),
        new TestCaseData(new[] { "NPSTCBIDNXHEHIQQMBYXAQTQKMSPMWQAWZDTW", "LCYRFQKHWEBPIHAWGNLHBZXWBXDHRYDBSCVEX", "CZMTPQAFSLWKDDVZWCLVYSHRRKGAYAZCFLGPS", "DHYXPNGQXVDEYWVHMVKDRFLKBYLKZBGYWNBQD", "QHZILFDCKVYQVPERAXBBPVLICCPBLHBRZGQWK", "RHNRDIWIDPPKKXVTQETZENPBPNVEPWMVWGCSD" }, ConsensusResidueType.Protein, 0.0f, 4, 0.0f, new float[] { 1.5f, 0.75f, 0.75f, 1.0f, 1.0f, 2.0f }, "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX").SetName("Emboss_088").SetDescription("cons -sequence a.msf -sprotein -plurality 0.0 -identity 4 -setcase 0.0"),
        new TestCaseData(new[] { "GT-RSK-ERFQAT-Q", "CDPSEIFCG-MQCMC", "ERSRAWVPKSLSPYM", "ECWMFFPNCTRGLI-", "CMCKHT-NYKVREKM", "WNTNFQ-NICKYFMK", "R-TGKWIHEPEGICQ", "NCIEENGPQLIAISV", "EKGIDVKIWEEWYDA", "DNCSQDQEPFLYYL-" }, ConsensusResidueType.Protein, 0.0f, 0, 0.0f, new float[] { 1.5f, 0.75f, 1.0f, 1.5f, 2.0f, 0.75f, 2.0f, 0.75f, 1.5f, 3.0f }, "ENCSEW-NQ-MYYMM").SetName("Emboss_089").SetDescription("cons -sequence a.msf -sprotein -plurality 0.0 -setcase 0.0"),
        new TestCaseData(new[] { "K--TVWAPTNDHEKE-HAP", "-TLFKRMS-DQTHKASGGS", "PVH-AF-FKNQIKSPWYIG", "D-LCDGYHAFPHSSEIIRE" }, ConsensusResidueType.Protein, 3.25f, 0, 4.25f, new float[] { 0.25f, 2.0f, 0.75f, 0.25f }, "xxxxxxxxxxxxxxxxxxx").SetName("Emboss_090").SetDescription("cons -sequence a.msf -sprotein -plurality 3.25 -setcase 4.25"),
        new TestCaseData(new[] { "-GSDZBBXKHWFVFPR-LKPQIQHPDMCCIF", "NLSGZHZ-WLDFFFERB-KPQNRLPHKPP-V", "DNMN-NE-WTDVCFM-BGNPQDXS-NMPTBF", "MNPIAZXGWHSYXFYNYV-PWICCPD-NQ--", "EDVDTQ-GWSY-XFAMBRKPBIQECD-T-BF", "MNGDLBXGLYREXQPMNXFC--QPVHFLKPG", "MN-EZHTGBRDQXGPMQX-PEBWLPDMLSW-", "MNW-AVXXIMYZXIPYZ-YPHKKRP-XLFVX", "N-YEZYHYCESAXMWRBTYTAEQFPDMYWBF", "MXGX-HCGSHCFXXGMBICZQ-AL-EM-ZBE", "-YSDYRH-VKEFXFVGABPPRIRLQBCEYBK" }, ConsensusResidueType.Protein, null, 6, null, new float[] { 2.0f, 0.75f, 1.0f, 3.0f, 0.5f, 3.0f, 1.5f, 0.25f, 2.0f, 0.5f, 2.0f }, "XXXXXXXXXXXXXFXXXXXPXXXXPXXXXXX").SetName("Emboss_091").SetDescription("cons -sequence a.msf -sprotein -identity 6"),
        new TestCaseData(new[] { "IqRdpZN-V-Z-SpCACB", "CYcBP--v---EH----V", "H-ND-WGShC-qApZKWQ", "-tTgSifH-B-MVrecfi", "mV-L-zcEyZ-I-e---B", "VAdiH-VT-B-b--crN-", "H-qkP-FVF--Ag-V---", "nSHiKk-LvaWX-g-L-I", "ryBFK--Mi-ZcQtY-Q-" }, ConsensusResidueType.Protein, 9.0f, 0, 10.0f, null, "xxxxxxxxxxxxxxxxxx").SetName("Emboss_092").SetDescription("cons -sequence a.fa -sprotein -plurality 9 -setcase 10"),
        new TestCaseData(new[] { "chDNpqIrPZBXhqKBASCZeqPcQKIFRxEAxAy", "KddngyiWlXBxHqKBWSCKEPACQKKGNXzaNHy" }, ConsensusResidueType.Protein, null, 0, 3.0f, null, "chdnpqirpzbxhqkbasczeqpcqkifrxeaxay").SetName("Emboss_093").SetDescription("cons -sequence a.fa -sprotein -setcase 3"),
        new TestCaseData(new[] { "ANFIP", "NSNIM", "MTK.Y", "BWEIT", "H.KTV", "BWVNE", "XRCST", "M.CCM", "GPM.G", "CK.TS", "NWIWS", "KRIKZ" }, ConsensusResidueType.Protein, null, 3, 20.5f, new float[] { 2.0f, 0.75f, 1.0f, 0.75f, 3.0f, 1.5f, 3.0f, 1.0f, 3.0f, 1.0f, 1.0f, 1.5f }, "XXXXX").SetName("Emboss_094").SetDescription("cons -sequence a.msf -sprotein -identity 3 -setcase 20.5"),
        new TestCaseData(new[] { "-NY-FRNCGRMI-PRN--VMRL", "DNTV-RNCG-MWE-RSHVVMDL", "DNTYSR--GRMIE-RN-VV-DL", "D---FR-CG-MIEPR--VVMDL", "D--Y-RN-GRMIEPRN-V---L", "Q-TYFRWC-RMIHPRNHVV-DL", "-NTY-RNCGRMIEPRNHVVMDL", "-NT---N-GRMIEP-NHVGYDL", "-NTYFRNCG-MIE-RGIVVGDL", "-N-Y-RNCTRMI--R-TVVM-L", "-N--FRNCG--I-PR-HVV-DL", "DNTYF-N-GR-I-PR-HVVMDL" }, ConsensusResidueType.Protein, 0.0f, 0, null, null, "dNTYfRNCGRMIEPRNhVVmDL").SetName("Emboss_095").SetDescription("cons -sequence a.fa -sprotein -plurality 0.0"),
        new TestCaseData(new[] { "MyYICBaMSHZHALGPLESNesLKRQClRAEfTeKLRpDRXmDDWIF", "myYIcBQMstFHaLGpDIsNNELkRVCLFfWBTRVaWpDRXWnlWIG", "NYYIcBWMSWZfALgPBISnnSLkyvCLRfECTrVDBvDRXMGDWIG", "myxLCbWPSiLPalGRNisNrsQKVVcLRFeBBRVAbPmRXinDtII", "mYHICbCMShRHALGPgiQNNSLkIvZLLFeBtRvAVPdRKmndWIg" }, ConsensusResidueType.Protein, null, 1, 0.0f, null, "MYYICBXMSXXHALGPBISNNSLKXVCLRFEBTRVAXPDRxMNDWIG").SetName("Emboss_096").SetDescription("cons -sequence a.fa -sprotein -identity 1 -setcase 0.0"),
        new TestCaseData(new[] { "KRMGDHLHI-E-MN-MPWD", "FRQ-DTLHIRWMSEPMPWD", "IKIGDTLFL-WMSCPYYWT", "-WIF-TLHMGWDSNP-PWD", "PRQMDCLHICW-SNPM-CT", "KRIGDTLHIRSGSNPMRC-", "KPIG-TT-IGPMSNPMHVD", "-EHGDTLDKGW-SNPMP-D", "K-IGDILCI-W-SN--PWD", "KSFTDKLHIGWMHNPMKWD", "KR-GT-LKILIFSNPMPQL" }, ConsensusResidueType.Protein, null, 0, null, new float[] { 1.0f, 0.25f, 1.5f, 0.75f, 0.75f, 0.75f, 0.5f, 0.5f, 1.0f, 0.5f, 1.0f }, "KRIGDtLxIxWxSNPMPWD").SetName("Emboss_097").SetDescription("cons -sequence a.msf -sprotein"),
        new TestCaseData(new[] { "FVBQHDKRBLKFXCXDHHXB", "BABRHDDXBLKFXCPDHXXB", "FABQRDKRBGKFXGXHHTQV", "FAICMDKXBLCFXCXDHHXB", "FABBHDKXWMKHXFHZHYXB" }, ConsensusResidueType.Protein, null, 3, 1.0f, null, "FABXHDKXBLKFxCXDHXXB").SetName("Emboss_098").SetDescription("cons -sequence a.fa -sprotein -identity 3 -setcase 1.0"),
        new TestCaseData(new[] { "MBEBPC-YRR-RMS-I", "-SPMTC---XZTNWGY", "TAHPKMFS-NGVD-GA", "FGSWDNQPL-I-QBPH", "NXVMDFEFLHEPVPMR", "FVYAYMK-AA-T-SDR", "XEAZ-DABICHENXIY", "PV-NKTDKK-FIAG-M", "GXZFFZNLLTIV-BNQ", "PE-ZY-CZIQPZCSMF" }, ConsensusResidueType.Protein, null, 0, null, null, "xxxxxxxxlxxxxxxx").SetName("Emboss_099").SetDescription("cons -sequence a.fa -sprotein"),
        new TestCaseData(new[] { "L.-tG-F-C--PR-qI--G-fK-F---QqWHQ--k-sL--Y-C", ".-YtS-glctLpiAf---yeIQYF-y--qLV-YikW-FCPI-N", "D.---c--C-t--AEPL-G-A-NwQ-RI-wV-K-N-r--dMhV", "---NQCQkCfEDi-fK--fTf--l-a--Qc-L-TK-Rs-FdsV", "LeS-Vy--mcNPgYELM-tEf-PiWqMLIcdQSp-----sF-H", ".Es-q-HRCm-K-w-F-wS-CTgI-sp-Q----W-cIKs-fV-", "Da.t-QqmDNWEiGDsM-vvfFQFWQwi-w-S-tKTS-VWfS-", "--HH-CGCTTl-I-TEM-IEFL-K-Y-RQwvlWPkDSlSDF-V", "dN-tGcQ-CTLP-A--Dg--I-tdkEIwe--pEP-af-LDFDV", "D--nTsT-Y---I-fpMAgKfVYfwR-----l-p--m-ITFAd", "-mLTQCqwnI-NQVLP--nrpgYfW----F-lYDKQSKD-T--", "YLST-CgK--Hp-NYW-wG-F-VcVhw--W-V--KC-LSdGWV" }, ConsensusResidueType.Protein, null, 0, null, new float[] { 0.25f, 3.0f, 2.0f, 1.5f, 0.5f, 0.5f, 3.0f, 0.5f, 1.5f, 1.5f, 0.75f, 1.5f }, "xxxTxxxxCxxxIxxxxxxxFxxFxxxxxxxxxxKxxxxxxxx").SetName("Emboss_100").SetDescription("cons -sequence a.msf -sprotein"),
        new TestCaseData(new[] { "--H--IA-AL---GR-LIPH-YVT", "Y-NHLK---LH-MNLEIIDWI-QQ" }, ConsensusResidueType.Protein, null, 1, 3.5f, new float[] { 2.0f, 0.5f }, "xxnxxiaxalxxxgrxiiphxyvt").SetName("Emboss_101").SetDescription("cons -sequence a.msf -sprotein -identity 1 -setcase 3.5"),
        new TestCaseData(new[] { "-ApPyhDK--Ty-H-NqMG-k--TeQiV-SvAI-IHgKWVYFG", "W-T--C-ESD-AWHHLH----Ka-W-vA-PCGDA--G--w---", "RNA-DLNTw--C-mQTt-QVQ---eYDp-wVLKVSKIrPL-I-", "TNNa-R--I-DfLCRiAYQt-Y-YTPN-waNNLYDLPagR---", "EK--e-f-cwS---VDIhVv-----g-tFYQ-lw--YTiTR--", "K--KD-pF-e-aY-QW-FK-Gs---KkL-fRDW--HCyGEc--", "I-yHY-i-WCsRIM-sFr-F-py-AeI--FMKm-A----et--", "FsVWFlWp--dA-WYNDWFS-EEP-TV--ES-CLm--HYHG-W", "NkS--W-F-wl-eT-RMnTP--IEd---nn-aV--MI-YTCPF", "dWVAGS-NKI--QL-Y-E-c-EW--WkrtlYQLl-lCsYV-my" }, ConsensusResidueType.Protein, null, 0, null, null, "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxLxxxxxxxxxx").SetName("Emboss_102").SetDescription("cons -sequence a.fa -sprotein"),
        new TestCaseData(new[] { "SPQQKGMKRLLGAQFTDVNKYCLHCDKGFKPKALSTEPLMLIAAD", "YIEPGAQERMNNEAGRIEITGNTFLQRFTGGSWACFRLWHIEHEY", "WVCEDWADRWSFPEWRDNINQRVVFDPNLQISIYPRTIIAIRDYT", "FGYAGMSVRSSQHNKETGMWTGYEFIKIPLFETTYINMHWVELMD", "RMQWMEPAGEIVFSKKPRWWIAPSGYRDCGFWHFKCKSGGLKDFE" }, ConsensusResidueType.Protein, null, 4, 1.75f, null, "XXXXXXXXRXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX").SetName("Emboss_103").SetDescription("cons -sequence a.fa -sprotein -identity 4 -setcase 1.75"),
        new TestCaseData(new[] { "-VE", "TDE", "TD-", "-KL" }, ConsensusResidueType.Protein, 0.25f, 4, null, null, "XXX").SetName("Emboss_104").SetDescription("cons -sequence a.fa -sprotein -plurality 0.25 -identity 4"),
        new TestCaseData(new[] { "kTIGGEMKwm-MaGSYPLyNCYFSAhDAmt", "-sS-PLmAieNMCc--vELNpIlPcKNRWS", "LgySYPPwWNM-TRKErI-nKTaLpHRDWq", "PHinKNRTPGKDNCHWwVFsYgtT-PERmY", "-LRpDgDRtWETFDrhsNRTEqpFYWvQMq", "yaWAGLLF-eRMPL-RGP-VAgV-WCwLAP" }, ConsensusResidueType.Protein, 2.5f, 0, 0.0f, null, "xSXSXXMXXXKMXXXYXVXNXXXxxXXRMX").SetName("Emboss_105").SetDescription("cons -sequence a.fa -sprotein -plurality 2.5 -setcase 0.0"),
        new TestCaseData(new[] { "SsxmIhHLNIXzW", "CHXmIHMlNi-ZV", "-HXMIZMRCIxcW", "lH--IhZGnIXKW", "SHEmihMLNIvZW", "YTXMNhMl-IXZw", "SHXMIhmLNeXZw", "SR-MI-mLNIXzW" }, ConsensusResidueType.Protein, 1.0f, 0, 4.0f, null, "sHxMIHMLNIxZW").SetName("Emboss_106").SetDescription("cons -sequence a.fa -sprotein -plurality 1.0 -setcase 4.0"),
        new TestCaseData(new[] { "LE~EWY--ANVQDQNPYYDG-PQKDHCYMYNRENPRPLKNF", "YPTRFV.IWWRSD-GEMEFE-SFVVTWCAEMTIETICVWAN", "FEGY~KQILGL-RSAWVG-WGRCANLWQDEKNIEWNFC-CK", "THFRKIVLESIPNEGWLRHMVAGHHMKKIGIEQDHAAGMHC", "MALGTNQNTYTRNTE~VRSGKDSDERDWNQYEM-EHHVLVI" }, ConsensusResidueType.Protein, 2.5f, 0, null, null, "xxxxxxxIxxVxNxxxVxxxxxxxxxxxxExxMExxxVxxx").SetName("Emboss_107").SetDescription("cons -sequence a.fa -sprotein -plurality 2.5"),
        new TestCaseData(new[] { "TDQPFYWMRRVNRIC", "-DQPFYWMRYVNRIC", "-DH---A--YVNR-I" }, ConsensusResidueType.Protein, 3.0f, 0, null, null, "xDXXXXXXXXVNRXX").SetName("Emboss_108").SetDescription("cons -sequence a.fa -sprotein -plurality 3"),
        new TestCaseData(new[] { "RTEP-DA-N-Q-PZ-DR-PGHPICC--W", "-LE-KHCZL-GFX-NK-P-GYZ-I-YZ-", "APNDKAG--EI--MITQ-CMSYWF-YPF", "F--IK-WV--GHR-RCD-FD--F--GIV", "SQAQF--XGWQSPW--MV-LC--A-TKE", "--HXR-SPACKLK--CP-YC-QM--XIM", "PQSQWAKTV-S--MGBH-NFHL-XZTPW", "TS-WNRG-G--RH--IDMGRAAWF-EHE", "-XMYLWYSQ--T-B--RCYV--T-APY-" }, ConsensusResidueType.Protein, 9.0f, 4, 10.0f, null, "XXXXXXXXXXXXXXXXXXXXXXXXXXXX").SetName("Emboss_109").SetDescription("cons -sequence a.fa -sprotein -plurality 9 -identity 4 -setcase 10"),
    };

    [TestCaseSource(nameof(EmbossCases))]
    public void GenerateEmbossConsensus_MatchesEmbossConsBinary(
        string[] rows, ConsensusResidueType type, float? plurality, int identity, float? setcase, float[]? weights, string expected)
    {
        string actual = MotifFinder.GenerateEmbossConsensus(rows, type, plurality, identity, setcase, weights);
        Assert.That(actual, Is.EqualTo(expected));
    }

    // Hand-derived from embcons.c: column A,A,A,T (weights 1, plurality = setcase = 2):
    // score(A) = 5+5-4 = 6 > score(T) = -12; positive matches of A = 3 >= 2 and > 2 -> 'A'.
    // Column G,G,G,G -> 'G'. Column -,A,-,- : all scores 0; the gap incumbent (row 0) is displaced
    // by the equal-scoring A (row 1); positive matches 1 < 2 -> 'N', 1 <= 2 -> 'n'.
    [Test]
    public void GenerateEmbossConsensus_HandDerivedColumns()
    {
        Assert.That(MotifFinder.GenerateEmbossConsensus(new[] { "AG-", "AGA", "AG-", "TG-" }), Is.EqualTo("AGn"));
    }

    [Test]
    public void GenerateEmbossConsensus_PluralityZero_GapIncumbentDisplaced()
    {
        // cons -plurality 0: the gap row 0 is displaced by A (row 1); matches 1 <= setcase 1.5 -> 'a'.
        Assert.That(MotifFinder.GenerateEmbossConsensus(new[] { "-", "A", "-" }, plurality: 0f), Is.EqualTo("a"));
    }

    [Test]
    public void GenerateEmbossConsensus_IdentityOverridesCase_UpperCaseNoConsensus()
    {
        // cons -identity 4 on the classic alignment -> NNGNNNNT (EMBOSS binary).
        var rows = new[] { "ACGTAC-T", "ACGTTCAT", "AGGTAC-T", "tCGAAG-T" };
        Assert.That(MotifFinder.GenerateEmbossConsensus(rows, identity: 4), Is.EqualTo("NNGNNNNT"));
    }

    [Test]
    public void GenerateEmbossConsensus_Protein_NoConsensusIsX_EvenWhenFirstRowLooksNucleic()
    {
        // EMBOSS cons picks 'N' vs 'X' from the composition of the FIRST sequence (ajSeqsetIsNuc) even
        // with -sprotein, so for this protein alignment the binary prints "nnnnnnn". The residue type is
        // explicit here, so the documented protein no-consensus symbol 'x' is used (deliberate deviation).
        var rows = new[] { "NCMCCVW", "HSQAKQW", "QRMHYED", "HLHSRHE", "RNRELNR", "QMMFQDR",
                           "TDISCTT", "PSHPALR", "HSLCWKK", "IAPDDFK", "CPLNWAP", "CKRRQFI" };
        Assert.That(MotifFinder.GenerateEmbossConsensus(rows, ConsensusResidueType.Protein, plurality: 12f),
            Is.EqualTo("xxxxxxx"));
    }

    [Test]
    public void GenerateEmbossConsensus_InputNormalisation_MatchesEmbossReader()
    {
        // '.' and '~' are gaps, lower case is upper-cased, X/? read as N for nucleotides (EMBOSS binary: AC-Tna).
        Assert.That(MotifFinder.GenerateEmbossConsensus(new[] { "AC.TX~", "AC.TX~", "ac-t?A" }, plurality: 0f),
            Is.EqualTo("AC-Tna"));
    }

    [Test]
    public void GenerateEmbossConsensus_Guards()
    {
        Assert.Throws<ArgumentNullException>(() => MotifFinder.GenerateEmbossConsensus(null!));
        Assert.Throws<ArgumentException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT" }));
        Assert.Throws<ArgumentException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT", "ACG" }));
        Assert.Throws<ArgumentException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT", null! }));
        Assert.Throws<ArgumentException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "AC1T", "ACGT" }));
        Assert.Throws<ArgumentException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT", "ACGT" }, weights: new[] { 1f }));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT", "ACGT" }, weights: new[] { 1f, -1f }));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT", "ACGT" }, weights: new[] { 1f, float.NaN }));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT", "ACGT" }, identity: -1));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT", "ACGT" }, plurality: float.NaN));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT", "ACGT" }, setcase: float.NaN));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateEmbossConsensus(new[] { "ACGT", "ACGT" }, (ConsensusResidueType)7));
    }

    [Test]
    public void GenerateEmbossConsensus_ZeroLengthAlignment_ReturnsEmpty()
    {
        Assert.That(MotifFinder.GenerateEmbossConsensus(new[] { "", "" }), Is.EqualTo(""));
    }

    #endregion

    #region Biopython dumb_consensus — reference-locked

    private static readonly TestCaseData[] DumbCases =
    {
        new TestCaseData(new[] { "ACGT", "ATGT", "ATGT" }, 0.7, 'N', false, "ANGT").SetName("Dumb_000"),
        new TestCaseData(new[] { "ACGT", "AT-T", "CT-T", "GT-T" }, 0.7, 'N', false, "NTGT").SetName("Dumb_001"),
        new TestCaseData(new[] { "A-", "-A", "--" }, 0.7, 'X', true, "XX").SetName("Dumb_002"),
        new TestCaseData(new[] { "MKV", "MKV", "mRV" }, 0.5, 'X', false, "MKV").SetName("Dumb_003"),
        new TestCaseData(new[] { "CA.CG--CCACauGGcaa---GAaG-u-uUgUAC", "CCAgaGGC-aUUUCAUaUCuAu-CCccAUu-UAU", "cUugGGGAcUCUUCAUaUG.aCUGgC-CAaAUAG", "UCUG-AaG-UCUAUguA-GGaca-GC-C-gaC-U", "-aaaGAG-UgAGGGAUau-GUaC-Uc-GUGGuuC", ".CGGG-GacUcuCA---UgCAAA-GACGUgA-U-", "ca--A-GGAA---Uau-CgGa-uUgaU-UGA---", "-GU---cgUC-Ua-auAcGgAuCag--CUGAGA-", "CAAGGUgG-Aa-A-U-GauUAAAAG-UGU-UaAC" }, 0.7, '?', false, "????G???????????????????????U???A?").SetName("Dumb_004"),
        new TestCaseData(new[] { "-UGA-ACUCA-AC-CA--UAG--C--CA-UG-UACUU", "AGUGU--GAU-UCA-AGGA-CAGC-CUG-AUCUACAU", "GAUA-CCU-AUCUAACGC-UCCACGU-GCUGUACUCG", "U-CAAUUAAAUGCUA-U-AGGUUUACACGACGC---U", "-CUAUCGCU-UUUAA---AUU-A-AUU--UAA-G-CC", "CUG-CU-UAG-UACC-U-U-UGCG-G-UCUAAAUGUG", "UCUUAGAUA--AAACG--AGCAC--GAUCACCUA--G", "---GCCCC-GGAGGCGCGC-G-UA-GUCCUUUU-UUU" }, 0.0, '?', false, "U?UA?CCUAAU?CAC??GA??A?CAGU?CU??UA?UU").SetName("Dumb_005"),
        new TestCaseData(new[] { "GCACCACCTTGTGCCACGCTTG", "ACACCACCTTGTGTCACGCTTT", "TCACCAAATTGAGCTACGCTTT", "GCACCACCTTGTGACACGCTTT", "GCTCCACCTTGTGCCAGGCTTT" }, 0.3, '?', false, "GCACCACCTTGTGCCACGCTTT").SetName("Dumb_006"),
        new TestCaseData(new[] { "kSYBSSMS", "YCCMSdSN", "tSKYMKvV", "uNDHBDKa", "GHdYuwtU", "vVHVVSCv", "BYwtwhAa", "TYMhUYam", "DUSTdAYG", "tVSSRGas" }, 0.7, 'X', true, "XXXXXXXX").SetName("Dumb_007"),
        new TestCaseData(new[] { "KRWVQYPQGNCNVVGYCEIGHKPVTRF", "PDSTQNTDSWKCRVKESYKTQSTFYHS" }, 0.7, 'N', true, "NNNNQNNNNNNNNVNNNNNNNNNNNNN").SetName("Dumb_008"),
        new TestCaseData(new[] { "VY", "KY", "VY", "vY", "Vy", "CY", "kY", "VY" }, 0.08376759263023059, 'N', true, "VY").SetName("Dumb_009"),
        new TestCaseData(new[] { "GUGAA-C", "CUCG--A", "AAAAU-C", "CG.UAG-", "GUGUGUG", "-GCGACA", "-AGUGUU" }, 0.5, 'N', false, "NNGNAUN").SetName("Dumb_010"),
        new TestCaseData(new[] { "-" }, 0.7, 'N', true, "N").SetName("Dumb_011"),
        new TestCaseData(new[] { "A----A-C--C---CUA", "---A-AG-UGC--C---", "-C-AU-UCG-C-A--U-", "--U----CCG-CUC---", "AC-AU--CC-----UU-", "GCU.UA---G-CAU---", "A--AUA-C-G-C-----" }, 1.0, 'X', false, "XCUAUAXCXGCCXXXUA").SetName("Dumb_012"),
        new TestCaseData(new[] { "W", "W", "W", "Y", "H" }, 0.4549911327559014, '?', false, "W").SetName("Dumb_013"),
        new TestCaseData(new[] { "GUUA-G-U--AAAA-UC-GU-AGG-CG-GGCAGAA-A", "AG.G-GGUAAACAAGAUGGUAAGGAAA-AGACAAAGG", "AGU--GG-GU--AUGGUUUUA---A-UG-GCGUUAUA" }, 0.5, 'X', true, "AGUXXGGUXXAXAAGXUXGUAAGGAXXXXGCXXAAXA").SetName("Dumb_014"),
        new TestCaseData(new[] { "AUACAUGUCCCAGGCCGCCACGUAGGGCA", "UUGCAUGUCGCAGGCGGCCUCGGAAGGAA", "AUUCAUGUCGCCGGACGCAUCGGAAGGAA", "AUACAUGUCGCAGGCCGCCUCGGAAGGCU", "AUAUUUGUCGCGGGUGGGCACGGAAGGCA", "ACACAUGUCGCUGCCCGCCUCGGAAGGCA", "AUACAUUUCGCAGGCGGUCGCGCUUGGCA", "AUAUAUGUCGCAAGCCGCCUAGGAAGGAA" }, 0.3311981817709265, '?', false, "AUACAUGUCGCAGGCCGCCUCGGAAGGCA").SetName("Dumb_015"),
        new TestCaseData(new[] { "CBHRC", "CYHRN", "CBHRN", "CCHMN", "CBHRB", "CWHRN", "CCHRN", "DBHRN", "CBGRN", "VBHRD" }, 1.0, 'X', false, "XXXXX").SetName("Dumb_016"),
        new TestCaseData(new[] { "QLKEPMTLAFSN", "QFK---TLAF-N", "Q-KN--TLAFAN", "QLKCP-TLAFCN", ".-KN-MTIATY-", "Q-KERM-LAFS-", "QRKN-MTLAWY-", "QLKNPMTLVFS-", "QC-N-ETIA-SG" }, 1.0, '?', false, "Q?K???T?????").SetName("Dumb_017"),
        new TestCaseData(new[] { "A-G---TAT-GC-AT-GCTAA--C", "TA.GA-AA-T-G-G-TAACTAGCG", "CA-CC-AG-GT-AG-CTC-GGGGA", "AGGGCC-A-CGC-TAGTCTA-GGG", "ATCTTTGGAG--TGGTGCGATGAC", "-GAA-TGCACGTG-A-TGTGTTCC" }, 0.7, 'N', false, "NNNNNNNNNNGNNNNNNNNNNGNN").SetName("Dumb_018"),
        new TestCaseData(new[] { "NPA", "NPA", "VPA", "NPA", "NSA", "NPA", "FPR", "NPA", "NPA" }, 0.7, 'N', false, "NPA").SetName("Dumb_019"),
        new TestCaseData(new[] { "CATT-CAGGGG-CGT-TT-CATC-GGCGAGCC", "CGCTAAGAG-T-C-TGAGA-AG-A-AGAAACC", "GTCTA----AGAGA-TTA-TAACC-TC---TG", "CCTTAAAC.-C-G-C--ATGGGTAGCA--A-C", "CATCTCAAGAATG--AA-CAAAT-GA-GTAG-", "CACCAA---AAGG-GCAAA-AAA-GCC--AAC", "CACTA-CAGTGAGGTGTCAAA-T-TTCCTATC" }, 0.0, 'X', false, "CACTAAAAGAGAGGTGXAAAAATAGXCGXAXC").SetName("Dumb_020"),
        new TestCaseData(new[] { "A--ACC-C--UAUACC-U-GU-U---U---CA-", ".U---G-----A-UA-UC-A-AU-A--CG-U--", "-UCU-G-U-U-GCC--AU---G-U----U-U-U", ".-----GAUAU-----UG-G-AG-UU-C--CCU", ".C-AU--C--CUC---GG-AUC--U-G-C--AU", "U--GG--AUC-UG---UC-UA-CUCC----A--", "---AG-U-ACCGUG-AAC--CGG----CA--A-" }, 1.0, 'X', false, "XXCXXXXXXXXXXXXXXXXXXXXUXXXCXXXXU").SetName("Dumb_021"),
        new TestCaseData(new[] { "--Y-SR-HY-WS-NSKKU------WT-N--BS-A", "B--S-N-HTHC--H-M--MC-H-BH-R-------", "--R-K-RCN---B-H-VV--W-S----DSN-HKC", "-N-----G----GK-RNB-M----VGUVWW-VT-", "NYUBUBD-G---H--UGM---H-DD-T-------", "H----V-MVYK--RGKD--WU-----VVB-ADU-", "C---HN-N----C-M--D-SHA----WY-DW---", "-UA--YSC---W----KYCGNRV-G---V----M" }, 0.7, 'N', false, "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN").SetName("Dumb_022"),
        new TestCaseData(new[] { "SGBHHWNCSKKSMRYWTRVRCMSVWSCCBBGGTN" }, 0.7, '?', false, "SGBHHWNCSKKSMRYWTRVRCMSVWSCCBBGGTN").SetName("Dumb_023"),
        new TestCaseData(new[] { "G-CCGT-", "G-C-G-G" }, 0.0, 'X', false, "GXCCGTG").SetName("Dumb_024"),
        new TestCaseData(new[] { "-U------G---BSW-G---Y---V-U-ND---B-A-KTH", "-N-WG-D-AR-Y-VS---------MV-----H-A-NY---", "--S-H-W-Y---KAWR-R-NVBBNR-GK-M-RKM-----U" }, 0.9957213794492501, '?', false, "??SW?????R?Y???RGR?N?BBN?V?KN???K???YKT?").SetName("Dumb_025"),
        new TestCaseData(new[] { "a-gUC-CaGu--Aa-aC-", "ACGUU-cGGa---GA---", "Au-aUU-a--a---A-Cg", "--GUUGCU--G--C-aC-", "C----gC-G--gaU--CC", "-c--u-cC----A-aGC-", "aC--AG-a----c-A-AG", ".-gU---A--GC-U-AC-", "aUG----g---G--a-U-", "A-gg-G--g--uA-a-A-" }, 0.5, 'X', false, "XXXUUGCXGXGXAXXaCX").SetName("Dumb_026"),
        new TestCaseData(new[] { "-U---GA-------G---UA-GCU--AU-A", "C----GA-G--CAA-CGA-------G-UG-", "C-UGUG-A--AU----GAU-A-GU--AUG-", "--U--G--GAAUA-G-----AC----A-GA", "----UU-GGA-UA-GCG-U-A-GU---UG-", "CU-A-------UAU---A-A--GU---U-A", "--U--G-GGAAUC----GUAAC-U-GA---" }, 0.0, 'X', false, "CUUXUGAGGAAUAXGCGAUAACGUXGAUGA").SetName("Dumb_027"),
        new TestCaseData(new[] { "-U-A-G--C-A-CU-GGC-A--CU---A-G-------U", "-UA-U-C-G-----UU--CUUA--UU--U-G-GCAAAU", ".--C-AAG--A-C---U--U-A--U-AGAGC-G-G---" }, 0.5, 'N', false, "NUANUNNGNNANCUUNNCCUUACUUUANNGNNGCNAAU").SetName("Dumb_028"),
        new TestCaseData(new[] { "GCACGUCGUUG" }, 0.7, '?', true, "???????????").SetName("Dumb_029"),
        new TestCaseData(new[] { "----U--C----YWCN-WC-H-MTU--NC-CN", "UGWYUM.--B-AYWC-C--RH-----CN----", "UG---M--S----WC--W---VDHUC---KC-", "-G-Y-M---BS-----B---H-W-UCC-C-CD" }, 1.0, 'N', false, "UGWYUMNCSBSAYWCNNWCRHVNNUCCNCKCN").SetName("Dumb_030"),
        new TestCaseData(new[] { "GUCAAUCAGAUAAGUACUCUGU", "AAUAGCUUAGACAGUAUUACCU", "GUGAGGUUUAUAACAGAUAUAU", "GUGAGCUUUUUAUACCCUUUCA", "UGGGGCUUAUGAAAUGUUAUGU", "GUAACACUUAUCUAUGUUAAAU", "GUCAGCAUUUCAGGGGUUCUGU", "GUUACCUAUUUAAAUGUUGACU", "GUGGGCCGUUUAAAUGUUUUUG" }, 0.7359451129530931, 'N', false, "GUNANNNNNNNANNNNNUNNNU").SetName("Dumb_031"),
        new TestCaseData(new[] { "N--C---TGt---H-GT--", "N---Vs-V--WW-SK----", "Y-----MT-Wsw-M--KC-", ".ha------yU-M-k----" }, 0.3, '?', false, "NhaCVsMTG???M??G?C?").SetName("Dumb_032"),
        new TestCaseData(new[] { "GCAcCTAGGGAaTGaGCCA", "GTAACTTAGGTACGAggcA", "GGAgaTACGgTCTtGggCA", "ggAGcTACGGtGGGAGcCA", "CGAaCTaCGGtATGaacCa", "GGAaGaCCggTatGAGCCA", "GgaACtACGGTATGtGCCa", "ggAaCTACAGTATGAAcGa", "CGAACTAcgGTaTGTGCCa" }, 0.0, 'N', true, "GGANCTACGGTATGAGCCA").SetName("Dumb_033"),
    };

    [TestCaseSource(nameof(DumbCases))]
    public void GenerateDumbConsensus_MatchesBiopython(string[] rows, double threshold, char ambiguous, bool requireMultiple, string expected)
    {
        Assert.That(MotifFinder.GenerateDumbConsensus(rows, threshold, ambiguous, requireMultiple), Is.EqualTo(expected));
    }

    [Test]
    public void GenerateDumbConsensus_BiopythonDocExamples()
    {
        // Biopython 1.85 dumb_consensus deprecation-warning doctest (ANGT); the gap_consensus doctest rows give NTGT here (gaps are not emitted).
        Assert.That(MotifFinder.GenerateDumbConsensus(new[] { "ACGT", "ATGT", "ATGT" }, ambiguous: 'N'), Is.EqualTo("ANGT"));
        Assert.That(MotifFinder.GenerateDumbConsensus(new[] { "ACGT", "AT-T", "CT-T", "GT-T" }, ambiguous: 'N'), Is.EqualTo("NTGT"));
    }

    [Test]
    public void GenerateDumbConsensus_EdgeCases()
    {
        Assert.That(MotifFinder.GenerateDumbConsensus(Array.Empty<string>()), Is.EqualTo(""));
        Assert.That(MotifFinder.GenerateDumbConsensus(new[] { "--", ".." }), Is.EqualTo("XX"), "all-gap column");
        Assert.That(MotifFinder.GenerateDumbConsensus(new[] { "A", "-" }), Is.EqualTo("A"));
        Assert.That(MotifFinder.GenerateDumbConsensus(new[] { "A", "-" }, requireMultiple: true), Is.EqualTo("X"));
        Assert.That(MotifFinder.GenerateDumbConsensus(new[] { "A", "a" }, threshold: 0), Is.EqualTo("X"), "case-sensitive tie");
        Assert.Throws<ArgumentNullException>(() => MotifFinder.GenerateDumbConsensus(null!));
        Assert.Throws<ArgumentException>(() => MotifFinder.GenerateDumbConsensus(new[] { "AC", "A" }));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateDumbConsensus(new[] { "A" }, double.NaN));
    }

    #endregion

    #region GenerateConsensus(sequences, inclusionThreshold)

    private static readonly TestCaseData[] ThresholdCases =
    {
        new TestCaseData(new[] { "-TG-A-", "TT--AA", "TTA--C", "TTAGAC", "TAA-AC", "TTA-AA", "T-AGAC", "GTA--C", "TGAGA-", "-TAGAC" }, 0.0, "KDRGAM").SetName("Threshold_000"),
        new TestCaseData(new[] { "AGAAAGGAG" }, 0.0, "AGAAAGGAG").SetName("Threshold_001"),
        new TestCaseData(new[] { "GGTC", "GGTG" }, 0.75, "GGTS").SetName("Threshold_002"),
        new TestCaseData(new[] { "TTNACaCnTnCGGTTtgtnGAtAGGNnTGtTAcANNcgN", "TTNAcAGnTCTGGttTGTTGANAtnnGNgtgACAnCTGN", "ttTACNCNTnTGgttNGTngATaGNnGTcTAACANNCGn", "TTNAcACnTnNgGAttgTnGATAcNNGTgGTaTANnCGN", "TtnACTCNNNTGNTgTgTNtACAGnNGTGcTACAnaCGN", "TTNgcACnTCNGGTTTCtNgAtAGNNGTgTNTCAnncGn", "tTNaCACTTGtgGTTTGTNGaTaGNnGTgtTACANNCgN", "TTNAcacNTNtCGtNtgTNGAANAnNGGGTAANANNcgN", "CTNAcAcNtNTGgTatCTNGATagnNGTGCtaCATncgN", "tTnAcNTgACTAgTTtGTNNaTAGnNGTGTtAcaNCCGT", "TTNCcACgAcTAGATTGTNGACANnNGTGtTacaNgTgN" }, 0.25, "TTTACACGTCTGGTTTGTTGATAGGNGTGTTACATCCGT").SetName("Threshold_003"),
        new TestCaseData(new[] { "ACAAATC", "NCANCTA", "ACANNNA", "NCCNGNA", "NGATCNA", "ACGCCCA", "CGCCCNT", "NNTNCNN", "GCANCAA", "NCCCCNA", "GNATANA", "NGANCNA" }, 0.75, "ACACCTA").SetName("Threshold_004"),
        new TestCaseData(new[] { "AGCGCG-GCTCGCCATACTAATG" }, 0.1, "AGCGCGNGCTCGCCATACTAATG").SetName("Threshold_005"),
        new TestCaseData(new[] { "CGCAAAGGCCCNCGCAACNNNGGATNNNCNTTNACNA", "GCAGGCATTATNATTGGAACNACNGCGATCGCCCAGN", "NNATCTGNAGTCTGCNGTAGACCCGNAGTNNGNANAC", "CGTATGGNCTNATTCNANNACNGNGGCAGNTNNNCCC", "NCAACNCNTNATGGNCGTNCATTTCNNGTGAAGNAAT", "GTNATGAACGTTGGNCGNTNGTGANAGNCANCNNCGG", "CCGCCNGCTGTGTTCNNNGTTAAGNANGGAGNGCNTT", "CCTCANGATAAATAACAAGANTGCNCGATGGATGANA" }, 0.5, "CCAACGGATGTWTGCCGWRMATGMGMGRTRGMGMMRH").SetName("Threshold_006"),
        new TestCaseData(new[] { "ANNTGgAGCtCAAAG", "TGncgGAgcCCAAcG", "CtNCggCACTCAaCG", "tnNCNGAgCtnAACt", "tncCGGAnCTCAaat", "NGacGgAnCtCaAcG", "TNaCgGagctCAACG", "TnNCGgagcTCAACG" }, 0.1, "HKMYGGMRCYCAAMK").SetName("Threshold_007"),
        new TestCaseData(new[] { "AACCTCTAGTC-TGG-ATC-TGG", "ATC-GCT-CTCAACGCG-GAGA-", "A-ATACTACACAAG-TG-CATAT", "A-CGTTTTCGATACG-GTT-A--", "-CCA-GTAGTGC-CTTT-AG-AT", "GACTTGGGGTGTC--C-CC-CAG", "AC-TAGTTACCAGG-TGAGCAT-", "TGG-TTGA-T--AATTGTTG-AC", "A--GGGT-GGCTAC-TGTGAAAA", "-CGATTTGATC-AAAGGT--CA-" }, 0.1, "AMSDDBKDVKSWAVKYGTBRHAK").SetName("Threshold_008"),
        new TestCaseData(new[] { "GCTTAAGTTCTTGC", "GGTTAAGTTATAGC", "CGTTAAGTTCTAGC", "GCTTATGGTCTAGG", "TGTGAAGTTCTAGG", "GGTTAAGTTGTAGC", "GGTTAAGATCTAGC", "CGTCAACTTCAAGC", "GATTAAGTTATAGC", "TGTTAATTTCAAGA", "GGTGAAGATCGAGC" }, 0.5, "GGTTAAGTTCTAGC").SetName("Threshold_009"),
        new TestCaseData(new[] { "CGTCGGNAAGGCGTTAGANCCAACGNAA", "CGTTCGNAAGGCGGTAGANCNAACGNGT", "CGTCCGNACGGCGCTAGANGAAACGNAA", "CGTCCGAAAGGCGGTCGGNCCAAAGNAA", "CGGCCGNGAGGAGGTCGANGCCACNNAT", "CGTCCGNANGGAGGTCGANCCACCGNTA", "CGTCCGTAGGACGGGCGNNCCAACGNAA", "NGGCAGNAAGGCGGTCGATCTATCGNAA", "CGACCGTAAGGCGGTCGACCCAANGNNA", "CTTCCGAAAGGCGTTCGANCCAAGGNAA", "NNTNCGNAGGGCGGTCGANCCAACGNAA" }, 0.25, "CGTCCGWAAGGCGGTMGAYCCAACGNAA").SetName("Threshold_010"),
        new TestCaseData(new[] { "TGGTT", "TGGCC", "AGGGC", "TTAAG", "TGGGT", "TGTTG", "TGGGG", "GGGCA" }, 1.0, "TGGGG").SetName("Threshold_011"),
        new TestCaseData(new[] { "ACCATTAAAGACAAGGACGCCGCCAG", "GACCTATTACCGTAGTCGGGACAGAC", "GTCCACCTCCACTCGCTGAGGGCTGC", "CCCCAGCGTGAAATAAATGACTGCTC" }, 0.0, "VHCMWNHDHSMVWHRNHBRVVBVBDS").SetName("Threshold_012"),
        new TestCaseData(new[] { "-GAC--TAGTATATCTGT-GGAACC-CGAG-CGTGAA", "AGGCTCT-C-A-TTT-TCCCG-TG-ATGTT-CCCGCA", "TGCTC-GT--AG-ATT-TCGGTG-GCC-TTA-C-ACA", "TGGC--TGT-AT-AATCT-TG-TCTACG-CCACTTCG", "TTGC-ATAACACTTCT--CG-ATATAC-G-AACGA-A", "C-GCAC--G-AAT--GATGGGAACG---C-A---TCA", "--G-C-T--CC--C--A--GG--AG-G-TTAAA-G-A", "-G--TG--CTAGTG-ACTCG-ATTC--TTTACATCC-", "-G-AGG--ATAG--AGA-T--C--GC-TTTACCTCT-" }, 0.75, "TGGCYSTAVTAGTTHTATCGGATCGACGTTACCTGCA").SetName("Threshold_013"),
        new TestCaseData(new[] { "tGTgCCCCAGGCTcACcAcgCGTCCa", "AAtTgcAGAcGgGcGaGAtTCcTtGa", "aTtaAGTcaGgCGCAaGGaCCGtGGC", "AGGAGTtgTGGGGCAAcCaCGgTCGc", "CATAgCGGCCGGGCCTGCagTTtTGC", "aagaGCCGTAcCaACCCATacGTCGt", "agTAGCCcAcaCgTATgcCAcATTgt", "gATAaCGaAGCCactCgTAActGTcg", "AaCGGGCGaGGCGcAgGCCGTTaGGC", "AcTaGCtGAGgGCaCCGTaCCCTACc" }, 0.16440931488534416, "ARKRRSBSWSSSRMMHSHHVYBTBSH").SetName("Threshold_014"),
        new TestCaseData(new[] { "TGTAGNGNCTTCNAGAGCN", "GTAAACGACCNAGNTCNTA", "CTATACTGGTACNCCGGTA", "NNGNGTCATGGGAGAGCGA" }, 0.3333333333333333, "BTAARCGACTDCRVNGGTA").SetName("Threshold_015"),
        new TestCaseData(new[] { "GCTAAGTATTTGTTCGTGATCCTGAAATTTA", "CCTAGATCTTTGTTCGTGAACGGGATAGCTA", "CCTAAGACTTTGATCGTGATCGAGAAAGTTA", "CCTAAGTTATTGTGCTAGATCGTCTAAGTTA", "AGTAAGTATTTGTTCGTGAACGTGCAAGGCA" }, 1.0, "CCTAAGTMTTTGTTCGTGATCGTGAAAGTTA").SetName("Threshold_016"),
        new TestCaseData(new[] { "ACGtCACCAaagGNCGaNNGT" }, 0.0, "ACGTCACCAAAGGNCGANNGT").SetName("Threshold_017"),
        new TestCaseData(new[] { "-GTTGATNAAATANATTCGTNTAG-T-NTCTCN-", "TGTTN---AAAANGATTCG---CGATA-TCC--G", "TGTTCATTAATAAN-TTCGTNGC--TANT-TCNG", "TNTTNATT-ATANN-CTCGTNTC-CTA-ATTCTG" }, 0.1, "TGTTSATTAAWWAGAYTCGTNKMGMTANWYYCTG").SetName("Threshold_018"),
        new TestCaseData(new[] { "caCtCtNTNgCaAtagTAAGTNGGaTc", "tNACtCNTnGCAAtaGNaAGTGgGcAC", "TACTTCNGNGGTATaGTAANTgGGAAC", "TACtTtnTNGaAaTAnCAAGagGgAAC", "TACTtTCTngCaAtAGCaAGtggGaaC", "TACTCTNTNgCAaTAgCAAaTGGgAaC", "TAATTtATNGCAATaGCAATTGGgAAC", "tActTtNtNGNaATaGCaAGTGGAtTC", "tACtNTNNNGCAAtagCAAgTGgGAac", "TACtTTntNgCAAtagCAaGTaGGAAN" }, 0.75, "TACTTTMTNGCAATAGCAAGTGGGAAC").SetName("Threshold_019"),
    };

    [TestCaseSource(nameof(ThresholdCases))]
    public void GenerateConsensus_Threshold_MatchesIndependentOracle(string[] rows, double threshold, string expected)
    {
        Assert.That(MotifFinder.GenerateConsensus(rows, threshold), Is.EqualTo(expected));
    }

    [Test]
    public void GenerateConsensus_DefaultThreshold_IdenticalToParameterlessOverload()
    {
        var rows = new[] { "ACGTTA", "ACGAAT", "TCGACA", "GCC-NA", "ACTTGA" };
        Assert.That(MotifFinder.GenerateConsensus(rows, 0.25), Is.EqualTo(MotifFinder.GenerateConsensus(rows)));
    }

    [Test]
    public void GenerateConsensus_Threshold_HandDerived()
    {
        // Column A,A,A,C,G (n = 5): threshold 0 -> {A,C,G} = V; 0.25 (> 1.25) -> A; 0.6 (> 3) -> none pass -> max A.
        var rows = new[] { "A", "A", "A", "C", "G" };
        Assert.That(MotifFinder.GenerateConsensus(rows, 0.0), Is.EqualTo("V"));
        Assert.That(MotifFinder.GenerateConsensus(rows, 0.1), Is.EqualTo("V"));
        Assert.That(MotifFinder.GenerateConsensus(rows, 0.2), Is.EqualTo("A"));
        Assert.That(MotifFinder.GenerateConsensus(rows, 0.6), Is.EqualTo("A"));
        Assert.That(MotifFinder.GenerateConsensus(new[] { "A", "C" }, 1.0), Is.EqualTo("M"), "tie fallback");
    }

    [Test]
    public void GenerateConsensus_Threshold_Guards()
    {
        Assert.Throws<ArgumentNullException>(() => MotifFinder.GenerateConsensus(null!, 0.25));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateConsensus(new[] { "A" }, -0.01));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateConsensus(new[] { "A" }, 1.01));
        Assert.Throws<ArgumentOutOfRangeException>(() => MotifFinder.GenerateConsensus(new[] { "A" }, double.NaN));
        Assert.Throws<ArgumentException>(() => MotifFinder.GenerateConsensus(new[] { "A", "AC" }, 0.25));
    }

    #endregion
}
