// ONCO-ASCAT-001 — ASCAT allele-specific segmentation with missing data (R NA): ascat.asmultipcf and ascat.aspcf NA path
// (B24 F59).
// Evidence: docs/Evidence/ONCO-ASCAT-001-Evidence.md (§ "Missing data — the NA path of ascat.asmultipcf / ascat.aspcf (F59)")
// TestSpec: tests/TestSpecs/ONCO-ASCAT-001.md (M-ANA-*, S-ANA-*, C-ANA-*)
// Source:  VanLoo-lab/ascat master 61ddf3b, ASCAT/R/ascat.asmultipcf.R (Select_sites / Select_sites2, madWinsMatrixWithNA,
//          logRaveraged mean(na.rm = TRUE), weight 0 for NA in the joint cost, getMadwithNA, NA/0 logR fill, prevlevel) and
//          ASCAT/R/ascat.aspcf.R (lrwins on !is.na(lr), Select_het = !homo & !is.na(baf) & !is.na(lr), na.rm in the gap
//          breakpoint and level means, pcfed[!is.na(towins)], !anyNA(dif), fillNA, prevlevel) + ascat.runAscat.R
//          (SNPposhet = SNPpos[names(bafsegmented), ], bafke = bafsegmented[bafpos][1]).
//
// Every expected value is the output of the ORIGINAL R code (R 4.3.3): the cohorts are generated by the MINSTD Simulate() of
// OncologyAnalyzer_AscatAsMultiPcf_Tests (verbatim in R), then NaN (= R NA) is written by the deterministic rules below;
// ascat.asmultipcf(obj, ascat.gg, penalty = 70) and ascat.aspcf(obj, ascat.gg, penalty = 70) on the same object; runASCAT via
// ascat.runAscat(gamma = 1). Tracks are run-length encoded: logR runs over all probes (1-based start, length, value), BAF
// runs over the heterozygous probes that HAVE a segmented BAF, plus the 1-based heterozygous probes without one.

namespace Seqeron.Genomics.Tests.Unit.Oncology;

using static OncologyAnalyzer_AscatAsMultiPcf_Tests;

[TestFixture]
public class OncologyAnalyzer_AscatMissingData_Tests
{
    public readonly record struct Run(int Start, int Length, double Value)
    {
        public static implicit operator Run((int Start, int Length, double Value) t) => new(t.Start, t.Length, t.Value);
    }

    public sealed record Track(Run[] LogR, Run[] PresentBaf, int[] MissingHet);

    /// <summary>NaN rule: probes (1-based index, chromosome, 1-based heterozygous counter, homozygous) → NaN for the given
    /// samples / tracks.</summary>
    public sealed record NaRule(int[] Samples, bool LogR, bool Baf, Func<int, string, int, bool, bool> Applies);

    public sealed record NaCohort(string Id, Cohort Cohort, NaRule[] Rules);

    private static Block Bl(string chrom, int n, bool hom, double[] r, double[] b) => new(chrom, n, hom, r, b);

    private static NaRule Mod(int[] s, bool lr, bool baf, int a, int b) => new(s, lr, baf, (i, _, _, _) => i * a % b == 0);

    private static NaRule Range(int[] s, bool lr, bool baf, int from, int to) => new(s, lr, baf, (i, _, _, _) => i >= from && i <= to);

    private static NaRule Chr(int[] s, bool lr, bool baf, string chr) => new(s, lr, baf, (_, c, _, _) => c == chr);

    private static NaRule HetEvery(int[] s, bool lr, bool baf, int a) => new(s, lr, baf, (_, _, hc, hom) => !hom && hc % a == 0);

    // N1 (2 samples) — scattered NA: S1 logR at i·37 ≡ 0 (mod 11), S1 BAF at i·29 ≡ 0 (mod 23), S2 BAF at i·53 ≡ 0 (mod 17).
    private static readonly NaCohort N1 = new("N1", new Cohort(2, 611, 0.3, new[]
    {
        Bl("1", 300, false, new[] { 0.0, 0.0 }, new[] { 0.5, 0.5 }), Bl("1", 300, false, new[] { 0.0, 0.8 }, new[] { 0.5, 0.75 }),
        Bl("1", 60, true, new[] { 0.0, 0.8 }, new[] { 0.5, 0.75 }), Bl("1", 240, false, new[] { -1.0, 0.8 }, new[] { 0.85, 0.75 }),
        Bl("2", 128, false, new[] { 0.5, -0.5 }, new[] { 0.7, 0.5 }), Bl("3", 4, false, new[] { 0.3, 0.3 }, new[] { 0.6, 0.6 }),
    }), new[] { Mod(new[] { 0 }, true, false, 37, 11), Mod(new[] { 1 }, false, true, 53, 17), Mod(new[] { 0 }, false, true, 29, 23) });

    // N2 (3 samples) — a whole-chromosome NA run: S2 logR + BAF on all of chr2; S1 logR on all of the 5-probe chr3; S3 logR on
    // probes 1340–1350 inside the forced homozygous stretch of chr4 (ascat.aspcf re-segmentation window with NA).
    private static readonly NaCohort N2 = new("N2", new Cohort(3, 622, 0.25, new[]
    {
        Bl("1", 400, false, new[] { 0.0, 0.0, 0.0 }, new[] { 0.5, 0.5, 0.5 }),
        Bl("1", 300, false, new[] { 1.0, 1.0, 0.0 }, new[] { 0.8, 0.8, 0.5 }),
        Bl("1", 300, false, new[] { -0.8, -0.8, -0.8 }, new[] { 0.9, 0.9, 0.9 }),
        Bl("2", 200, false, new[] { 0.4, 0.4, -0.6 }, new[] { 0.7, 0.7, 0.85 }),
        Bl("3", 5, false, new[] { 0.4, -0.4, 0.0 }, new[] { 0.7, 0.8, 0.5 }),
        Bl("4", 120, false, new[] { 0.0, 0.0, 0.0 }, new[] { 0.5, 0.5, 0.5 }),
        Bl("4", 60, true, new[] { 0.0, 0.0, -1.2 }, new[] { 0.5, 0.5, 0.5 }),
        Bl("4", 120, false, new[] { 0.0, 0.0, -1.2 }, new[] { 0.5, 0.5, 0.95 }),
    }), new[] { Chr(new[] { 1 }, true, true, "2"), Chr(new[] { 0 }, true, false, "3"), Range(new[] { 2 }, true, false, 1340, 1350) });

    // N3 (2 samples) — NA BAF at heterozygous probes: S1 BAF on probes 301–450, S2 BAF at every 3rd heterozygous probe; all
    // of chr5 missing in both samples (no selected site: one logR level, NaN → prevlevel); chr6 probes 1011–1012 missing in
    // both (a single selected site: R winsorises its BAF across the samples); logR missing in both samples at 860–865
    // (selected sites without a segmented BAF); S1 logR missing on all of chr7 (a zero-weight logR track).
    private static readonly NaCohort N3 = new("N3", new Cohort(2, 633, 0.3, new[]
    {
        Bl("1", 300, false, new[] { 0.0, 0.0 }, new[] { 0.5, 0.5 }), Bl("1", 300, false, new[] { 0.6, 0.6 }, new[] { 0.75, 0.75 }),
        Bl("1", 200, false, new[] { 0.6, -0.6 }, new[] { 0.75, 0.85 }), Bl("2", 200, false, new[] { 0.3, 0.3 }, new[] { 0.6, 0.6 }),
        Bl("5", 10, false, new[] { 0.0, 0.0 }, new[] { 0.5, 0.5 }), Bl("6", 3, false, new[] { 0.2, 0.2 }, new[] { 0.6, 0.6 }),
        Bl("7", 8, false, new[] { 0.1, 0.1 }, new[] { 0.5, 0.5 }),
    }), new[]
    {
        Range(new[] { 0 }, false, true, 301, 450), HetEvery(new[] { 1 }, false, true, 3), Chr(new[] { 0, 1 }, true, true, "5"),
        Range(new[] { 0, 1 }, true, true, 1011, 1012), Range(new[] { 0, 1 }, true, false, 860, 865), Chr(new[] { 0 }, true, false, "7"),
    });

    private static readonly Dictionary<string, NaCohort> Cohorts = new[] { N1, N2, N3 }.ToDictionary(c => c.Id);

    /// <summary>Simulate (OncologyAnalyzer_AscatAsMultiPcf_Tests) + the NaN rules (R applyNA in the Evidence file).</summary>
    private static (List<IReadOnlyList<OncologyAnalyzer.AlleleSpecificLocus>> Samples, List<bool> Het) SimulateWithNa(NaCohort c)
    {
        var (samples, het) = Simulate(c.Cohort);
        var data = samples.Select(s => s.ToArray()).ToArray();
        foreach (NaRule rule in c.Rules)
        {
            int hetCounter = 0;
            for (int i = 0; i < het.Count; i++)
            {
                if (het[i])
                {
                    hetCounter++;
                }

                if (!rule.Applies(i + 1, data[0][i].Chromosome, hetCounter, !het[i]))
                {
                    continue;
                }

                foreach (int s in rule.Samples)
                {
                    data[s][i] = data[s][i] with
                    {
                        LogR = rule.LogR ? double.NaN : data[s][i].LogR,
                        BAF = rule.Baf ? double.NaN : data[s][i].BAF,
                    };
                }
            }
        }

        return (data.Select(d => (IReadOnlyList<OncologyAnalyzer.AlleleSpecificLocus>)d).ToList(), het);
    }

    private static IReadOnlyList<OncologyAnalyzer.AspcfSegmentation> Segment(NaCohort c, bool multi)
    {
        var (samples, het) = SimulateWithNa(c);
        return multi
            ? OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(samples, het)
            : samples.Select(s => OncologyAnalyzer.SegmentAlleleSpecificAspcf(s, het)).ToList();
    }

    // ---- R reference tracks (ascat.asmultipcf / ascat.aspcf, R 4.3.3) ----

    private static readonly Track[] N1MultiExpected =
    {
        new Track(new Run[] { (1, 660, 0.0058229316198994702), (661, 240, -1.002698511725536), (901, 128, 0.50822513881281606), (1029, 4, 0.29196956497243121) },
                  new Run[] { (1, 423, 0.5), (424, 168, 0.8506822639211018), (592, 82, 0.71148492054091883), (674, 2, 0.57752132500872078) },
                  new int[] { 782 }),
        new Track(new Run[] { (1, 300, -0.0055432574396067904), (301, 600, 0.80375984331628303), (901, 128, -0.49936956123972526), (1029, 4, 0.31049443537392396) },
                  new Run[] { (1, 205, 0.5), (206, 386, 0.75068916347118009), (592, 82, 0.5), (674, 2, 0.62719313242807662) },
                  new int[] { 782 }),
    };

    private static readonly Track[] N1SingleExpected =
    {
        new Track(new Run[] { (1, 661, 0.0039065673471196374), (662, 239, -1.0020415691356497), (901, 128, 0.50822513881281606), (1029, 4, 0.29196956497243121) },
                  new Run[] { (1, 372, 0.5), (373, 146, 0.84995800657323461), (519, 73, 0.71179942722451928), (592, 2, 0.57752132500872078) },
                  new int[] { 11, 33, 46, 55, 66, 69, 92, 99, 110, 121, 138, 143, 154, 161, 165, 176, 184, 198, 209, 220, 230, 264, 276, 286, 297, 308, 341, 352, 374, 385, 396, 407, 414, 418, 429, 437, 440, 460, 462, 473, 483, 484, 517, 528, 539, 550, 552, 561, 572, 575, 583, 598, 667, 671, 682, 693, 713, 736, 748, 759, 770, 781, 782, 792, 814, 825, 828, 836, 858, 869, 874, 880, 891, 897, 902, 920, 943, 946, 966, 968, 989, 990, 1001 }),
        new Track(new Run[] { (1, 300, -0.0055432574396067904), (301, 600, 0.80375984331628303), (901, 128, -0.49936956123972526), (1029, 4, 0.31049443537392396) },
                  new Run[] { (1, 196, 0.5), (197, 365, 0.75068916347118031), (562, 80, 0.5), (642, 2, 0.62719313242807662) },
                  new int[] { 51, 85, 102, 153, 170, 204, 221, 238, 255, 306, 323, 357, 374, 425, 442, 476, 493, 510, 544, 561, 578, 595, 714, 731, 748, 765, 782, 799, 833, 867, 884, 901, 1020 }),
    };

    private static readonly Track[] N2MultiExpected =
    {
        new Track(new Run[] { (1, 400, -0.00065774684080749108), (401, 300, 1.0050153782254467), (701, 300, -0.79875059011861871), (1001, 205, 0.39326268876402765), (1206, 300, 0.00070767962779275887) },
                  new Run[] { (1, 306, 0.5), (307, 228, 0.79770673322957897), (535, 236, 0.89990248709162701), (771, 159, 0.69737285518587711), (930, 4, 0.7109647508179604), (934, 186, 0.5) },
                  Array.Empty<int>()),
        new Track(new Run[] { (1, 400, -0.0018672053226582717), (401, 300, 1.0037517374588263), (701, 500, -0.80803486571804073), (1201, 5, -0.40645974532070561), (1206, 300, -0.0026563736836688469) },
                  new Run[] { (1, 306, 0.5), (307, 228, 0.79405256974900462), (535, 236, 0.89553514134691803), (771, 4, 0.81109912629988945), (775, 186, 0.5) },
                  new int[] { 1001, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1013, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1031, 1032, 1033, 1034, 1035, 1038, 1039, 1041, 1042, 1043, 1045, 1046, 1047, 1048, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1061, 1062, 1063, 1065, 1066, 1068, 1069, 1071, 1073, 1075, 1076, 1078, 1080, 1081, 1082, 1083, 1084, 1086, 1087, 1088, 1090, 1091, 1092, 1093, 1094, 1096, 1097, 1098, 1099, 1100, 1103, 1106, 1107, 1108, 1109, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1119, 1120, 1121, 1122, 1123, 1125, 1126, 1127, 1128, 1130, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1144, 1145, 1148, 1149, 1150, 1151, 1152, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1176, 1177, 1179, 1182, 1183, 1184, 1185, 1186, 1188, 1190, 1191, 1192, 1193, 1194, 1195, 1197, 1198, 1199, 1200 }),
        new Track(new Run[] { (1, 700, 0.0019984949228479842), (701, 300, -0.81171127567240564), (1001, 200, -0.59697782746189165), (1201, 5, -0.075319896263685057), (1206, 120, 0.0050280731124934166), (1326, 180, -1.1935310995154069) },
                  new Run[] { (1, 534, 0.5), (535, 236, 0.89369437808698082), (771, 159, 0.85347109356889705), (930, 4, 0.55970170462172908), (934, 87, 0.5), (1021, 99, 0.94395515022681264) },
                  Array.Empty<int>()),
    };

    private static readonly Track[] N2SingleExpected =
    {
        new Track(new Run[] { (1, 400, -0.00065774684080749108), (401, 302, 0.99340377114776091), (703, 298, -0.79908893441132689), (1001, 204, 0.39326268876402765), (1205, 301, 0.00070767962779275887) },
                  new Run[] { (1, 306, 0.5), (307, 229, 0.79833194281703523), (536, 235, 0.89972811585049661), (771, 159, 0.69737285518587688), (930, 186, 0.5) },
                  new int[] { 1202, 1203, 1204, 1205 }),
        new Track(new Run[] { (1, 400, -0.0018672053226582717), (401, 302, 0.9918183975176571), (703, 399, -0.80810098834931809), (1102, 104, -0.40645974532070561), (1206, 300, -0.0026563736836688469) },
                  new Run[] { (1, 306, 0.5), (307, 229, 0.7941307858339457), (536, 235, 0.89589076299860504), (771, 4, 0.81109912629988945), (775, 186, 0.5) },
                  new int[] { 1001, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1013, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1031, 1032, 1033, 1034, 1035, 1038, 1039, 1041, 1042, 1043, 1045, 1046, 1047, 1048, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1061, 1062, 1063, 1065, 1066, 1068, 1069, 1071, 1073, 1075, 1076, 1078, 1080, 1081, 1082, 1083, 1084, 1086, 1087, 1088, 1090, 1091, 1092, 1093, 1094, 1096, 1097, 1098, 1099, 1100, 1103, 1106, 1107, 1108, 1109, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1119, 1120, 1121, 1122, 1123, 1125, 1126, 1127, 1128, 1130, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1144, 1145, 1148, 1149, 1150, 1151, 1152, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1176, 1177, 1179, 1182, 1183, 1184, 1185, 1186, 1188, 1190, 1191, 1192, 1193, 1194, 1195, 1197, 1198, 1199, 1200 }),
        new Track(new Run[] { (1, 700, 0.0019984949228479842), (701, 300, -0.81171127567240564), (1001, 200, -0.59697782746189165), (1201, 5, -0.075319896263685057), (1206, 119, 0.0062553147564054484), (1325, 1, -0.14101368251303845), (1326, 180, -1.1935310995154069) },
                  new Run[] { (1, 534, 0.5), (535, 236, 0.89369437808698116), (771, 159, 0.85347109356889783), (930, 4, 0.55970170462172908), (934, 86, 0.5), (1020, 100, 0.94050187956023712) },
                  Array.Empty<int>()),
    };

    private static readonly Track[] N3MultiExpected =
    {
        new Track(new Run[] { (1, 300, 0.00049532969970969858), (301, 500, 0.59962352680248365), (801, 210, 0.31009444573346467), (1011, 11, 0.17073517468326502) },
                  new Run[] { (1, 213, 0.5), (214, 316, 0.75308566919396691), (530, 133, 0.60639015417843589), (663, 7, 0.52306794231907372) },
                  new int[] { 303, 307, 310, 314, 318, 322, 328, 331, 334, 340, 343, 346, 353, 357, 360, 363, 366, 369, 374, 378, 385, 390, 397, 401, 406, 412, 415, 421, 425, 429, 434, 437, 443, 446, 450, 860, 861, 864, 865, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1011, 1012 }),
        new Track(new Run[] { (1, 300, -0.0058868771837497511), (301, 300, 0.59623057817926806), (601, 200, -0.61343562403341545), (801, 210, 0.30588847131780961), (1011, 3, 0.11173156151162998), (1014, 8, 0.11348520024376232) },
                  new Run[] { (1, 213, 0.5), (214, 174, 0.74940146958023701), (388, 142, 0.84676782900796854), (530, 133, 0.5), (663, 7, 0.6010211217144954) },
                  new int[] { 303, 307, 310, 314, 318, 322, 328, 331, 334, 340, 343, 346, 353, 357, 360, 363, 366, 369, 374, 378, 385, 390, 397, 401, 406, 412, 415, 421, 425, 429, 434, 437, 443, 446, 450, 860, 861, 864, 865, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1011, 1012 }),
    };

    private static readonly Track[] N3SingleExpected =
    {
        new Track(new Run[] { (1, 299, 0.00043346297987877715), (300, 501, 0.5984645845911597), (801, 206, 0.31009444573346467), (1007, 15, 0.17073517468326502) },
                  new Run[] { (1, 212, 0.5), (213, 247, 0.75240329628503222), (460, 133, 0.60517316746549288) },
                  new int[] { 301, 302, 303, 304, 306, 307, 308, 309, 310, 311, 313, 314, 316, 317, 318, 319, 321, 322, 323, 324, 328, 329, 330, 331, 332, 333, 334, 337, 339, 340, 341, 342, 343, 344, 345, 346, 348, 351, 353, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 371, 372, 374, 376, 377, 378, 380, 382, 385, 386, 389, 390, 391, 394, 397, 398, 400, 401, 402, 404, 406, 410, 411, 412, 413, 414, 415, 419, 420, 421, 422, 423, 425, 426, 428, 429, 432, 433, 434, 435, 436, 437, 438, 441, 443, 444, 445, 446, 447, 449, 450, 860, 861, 864, 865, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1011, 1012, 1014, 1015, 1016, 1017, 1018, 1020, 1021 }),
        new Track(new Run[] { (1, 300, -0.0058868771837497511), (301, 300, 0.59623057817926806), (601, 200, -0.61343562403341545), (801, 206, 0.30588847131780961), (1007, 7, 0.11173156151162998), (1014, 8, 0.11348520024376232) },
                  new Run[] { (1, 142, 0.5), (143, 140, 0.7494014695802369), (283, 94, 0.84676782900796843), (377, 89, 0.5), (466, 4, 0.6010211217144954) },
                  new int[] { 4, 11, 14, 18, 21, 26, 31, 35, 38, 45, 49, 52, 55, 60, 65, 71, 74, 77, 82, 87, 93, 98, 101, 105, 110, 114, 121, 127, 130, 134, 140, 145, 149, 153, 158, 161, 166, 169, 172, 176, 183, 186, 190, 193, 196, 199, 208, 212, 215, 219, 223, 226, 229, 234, 238, 241, 244, 247, 253, 257, 261, 265, 269, 273, 276, 279, 284, 288, 293, 296, 300, 303, 307, 310, 314, 318, 322, 328, 331, 334, 340, 343, 346, 353, 357, 360, 363, 366, 369, 374, 378, 385, 390, 397, 401, 406, 412, 415, 421, 425, 429, 434, 437, 443, 446, 450, 455, 459, 463, 466, 469, 472, 475, 483, 487, 490, 493, 500, 505, 508, 512, 517, 521, 524, 527, 531, 535, 539, 544, 548, 554, 560, 563, 567, 570, 575, 578, 582, 591, 595, 603, 606, 611, 617, 621, 625, 630, 638, 641, 645, 648, 653, 657, 660, 663, 669, 676, 680, 683, 687, 690, 695, 699, 702, 705, 708, 711, 714, 717, 723, 727, 733, 736, 741, 745, 748, 751, 754, 757, 761, 765, 769, 774, 780, 786, 789, 793, 800, 804, 809, 812, 817, 821, 826, 834, 837, 846, 849, 853, 858, 860, 861, 864, 865, 866, 871, 874, 878, 881, 885, 889, 895, 899, 903, 906, 909, 914, 919, 922, 926, 930, 935, 939, 943, 946, 951, 956, 962, 969, 972, 977, 980, 984, 988, 993, 996, 1002, 1003, 1004, 1005, 1006, 1007, 1009, 1011, 1012, 1014, 1017, 1021 }),
    };

    private static readonly Dictionary<string, Track[]> Expected = new()
    {
        ["N1Multi"] = N1MultiExpected, ["N1Single"] = N1SingleExpected,
        ["N2Multi"] = N2MultiExpected, ["N2Single"] = N2SingleExpected,
        ["N3Multi"] = N3MultiExpected, ["N3Single"] = N3SingleExpected,
    };

    private static IEnumerable<TestCaseData> ReferenceTracks()
    {
        foreach (string id in new[] { "N1", "N2", "N3" })
        {
            yield return new TestCaseData(id, true).SetName($"AsMultiPcf_{id}_MissingData_MatchesR");
            yield return new TestCaseData(id, false).SetName($"Aspcf_{id}_MissingData_MatchesR");
        }
    }

    // M-ANA-1..6 — per probe: identical breakpoints, bit-identical values (B24 F66) and identical NaN (NA) positions of
    // Tumor_LogR_segmented and the mirrored Tumor_BAF_segmented, for both segmenters on all three NA cohorts.
    [TestCaseSource(nameof(ReferenceTracks))]
    public void Segmentation_WithMissingData_MatchesAscat(string id, bool multi)
    {
        NaCohort cohort = Cohorts[id];
        var (_, het) = SimulateWithNa(cohort);
        var result = Segment(cohort, multi);
        Track[] expected = Expected[id + (multi ? "Multi" : "Single")];
        Assert.That(result, Has.Count.EqualTo(expected.Length));

        Assert.Multiple(() =>
        {
            for (int s = 0; s < expected.Length; s++)
            {
                int n = het.Count;
                var logR = new double[n];
                foreach (Run run in expected[s].LogR)
                {
                    Array.Fill(logR, run.Value, run.Start - 1, run.Length);
                }

                var baf = new double[n];
                Array.Fill(baf, double.NaN);
                var missing = new HashSet<int>(expected[s].MissingHet);
                var present = Enumerable.Range(0, n).Where(i => het[i] && !missing.Contains(i + 1)).ToArray();
                foreach (Run run in expected[s].PresentBaf)
                {
                    for (int k = run.Start - 1; k < run.Start - 1 + run.Length; k++)
                    {
                        baf[present[k]] = run.Value;
                    }
                }

                Assert.That(present, Has.Length.EqualTo(expected[s].PresentBaf.Sum(r => r.Length)), $"S{s + 1}: BAF site count.");
                for (int i = 0; i < n; i++)
                {
                    Assert.That(result[s].SegmentedLogR[i], Is.EqualTo(logR[i]), $"S{s + 1} probe {i + 1}: logR.");
                    if (double.IsNaN(baf[i]))
                    {
                        Assert.That(double.IsNaN(result[s].SegmentedBaf[i]), Is.True, $"S{s + 1} probe {i + 1}: BAF NA.");
                    }
                    else
                    {
                        Assert.That(result[s].SegmentedBaf[i], Is.EqualTo(baf[i]), $"S{s + 1} probe {i + 1}: BAF.");
                    }
                }

                // Breakpoints: identical runs of segmented logR (exact equality inside a run).
                for (int i = 1; i < n; i++)
                {
                    Assert.That(result[s].SegmentedLogR[i] == result[s].SegmentedLogR[i - 1], Is.EqualTo(logR[i] == logR[i - 1]),
                        $"S{s + 1} probe {i + 1}: breakpoint.");
                }
            }
        });
    }

    // ---- runASCAT on the NA segmentations (ascat.runAscat(gamma = 1), R 4.3.3) ----

    private static TestCaseData Fit(string id, int sample, double rho, double psi, double ploidy, double goodness, (int, int)[] segRaw) =>
        new TestCaseData(id, sample, rho, psi, ploidy, goodness, segRaw).SetName($"RunAscat_{id}_S{sample + 1}_MissingData_MatchesR");

    private static IEnumerable<TestCaseData> ReferenceFits()
    {
        yield return Fit("N1Multi", 0, 0.83999999999999997, 2.3500000000000001, 2.0164113785557989, 98.219103302540461, new[] { (1, 1), (1, 0), (3, 1), (2, 1) });
        yield return Fit("N1Single", 0, 0.82999999999999996, 2.3500000000000001, 2.0191693290734825, 98.181043565032127, new[] { (1, 1), (1, 0), (3, 1), (2, 1) });
        yield return Fit("N2Multi", 0, 0.87, 2.5, 2.7333333333333334, 98.861411975697138, new[] { (1, 1), (4, 1), (1, 0), (2, 1), (2, 1), (2, 1) });
        yield return Fit("N2Multi", 1, 0.85999999999999999, 2.3999999999999999, 2.4597701149425286, 98.795411325665384, new[] { (1, 1), (4, 1), (1, 0), (1, 0), (2, 0), (1, 1) });
        yield return Fit("N2Multi", 2, 0.78000000000000003, 3.8500000000000001, 2.9912985274431056, 94.452785755767849, new[] { (2, 2), (2, 0), (2, 0), (2, 2), (2, 2), (1, 0) });
        yield return Fit("N2Single", 0, 0.87, 2.5, 2.7386666666666666, 98.803098962869726, new[] { (1, 1), (4, 1), (1, 0), (2, 1), (3, 0), (3, 0), (2, 1) });
        yield return Fit("N2Single", 1, 0.85999999999999999, 2.4500000000000002, 2.4659003831417623, 98.700388417295329, new[] { (1, 1), (4, 1), (1, 0), (1, 0), (2, 0), (2, 0), (1, 1) });
        yield return Fit("N2Single", 2, 0.78000000000000003, 3.8500000000000001, 2.9906291834002676, 94.632119541459076, new[] { (2, 2), (2, 0), (2, 0), (2, 2), (2, 2), (3, 0), (1, 0) });
        yield return Fit("N3Multi", 0, 0.23999999999999999, 2.1499999999999999, 4.7448648648648648, 98.948037031988221, new[] { (1, 1), (7, 0), (3, 1), (4, 0), (3, 0), (2, 1) });
        yield return Fit("N3Multi", 1, 0.73999999999999999, 2.7999999999999998, 3.660024906600249, 97.462835219860082, new[] { (2, 1), (4, 1), (2, 0), (2, 2), (4, 0), (3, 0), (2, 1) });
        yield return Fit("N3Single", 0, 0.23999999999999999, 2.1499999999999999, 4.405025125628141, 99.862958600947522, new[] { (1, 1), (6, 0), (3, 1), (4, 0), (3, 0), (3, 0), (3, 0) });
        yield return Fit("N3Single", 1, 0.73999999999999999, 2.7999999999999998, 3.5922233300099702, 97.697217899672339, new[] { (2, 1), (4, 1), (2, 0), (2, 2), (4, 0), (3, 0), (3, 0), (2, 1) });
    }

    // M-ANA-7..18 — runASCAT on the NA segmentations: heterozygous probes without a segmented BAF are not in bafsegmented
    // (SNPposhet), and a segment's BAF is its first probe WITH a segmented BAF (bafke). R gives no solution for N1 S2 (both
    // segmenters), which is not locked here.
    [TestCaseSource(nameof(ReferenceFits))]
    public void FitPurityPloidyFromAspcf_WithMissingData_MatchesRunAscat(
        string id, int sample, double rho, double psi, double ploidy, double goodness, (int Major, int Minor)[] segRaw)
    {
        NaCohort cohort = Cohorts[id[..2]];
        var fit = OncologyAnalyzer.FitPurityPloidyFromAspcf(Segment(cohort, id.EndsWith("Multi", StringComparison.Ordinal))[sample]);

        Assert.Multiple(() =>
        {
            Assert.That(fit.Purity, Is.EqualTo(rho).Within(1e-12), "runASCAT purity.");
            Assert.That(fit.Psi, Is.EqualTo(psi).Within(1e-12), "runASCAT psi.");
            Assert.That(fit.Ploidy, Is.EqualTo(ploidy).Within(1e-12), "ASCAT ploidy.");
            Assert.That(fit.GoodnessOfFit, Is.EqualTo(goodness).Within(1e-9), "runASCAT goodnessOfFit.");
            Assert.That(fit.Segments.Select(s => (s.MajorCopyNumber, s.MinorCopyNumber)), Is.EqualTo(segRaw), "seg_raw.");
        });
    }

    // S-ANA-1 — complete data is unchanged by the NA path: the NaN-aware helpers reduce to the former ones (the F53/F37
    // R-locked suites stay green); here: a NaN-free cohort gives a BAF at exactly the heterozygous probes.
    [Test]
    public void Segmentation_CompleteData_HasBafAtEveryHeterozygousProbe()
    {
        var clean = N1 with { Rules = Array.Empty<NaRule>() };
        var (_, het) = SimulateWithNa(clean);
        foreach (bool multi in new[] { true, false })
        {
            foreach (var seg in Segment(clean, multi))
            {
                Assert.That(Enumerable.Range(0, het.Count).All(i => double.IsNaN(seg.SegmentedBaf[i]) == !het[i]), Is.True);
            }
        }
    }

    // S-ANA-2 — no NaN logR level survives; in ascat.asmultipcf a part without any selected site (chr5, all missing) takes
    // the previous level (prevlevel) and has no BAF (ascat.aspcf instead fills it by fillNA from both neighbours — locked by
    // M-ANA above).
    [Test]
    public void Segmentation_WholeChromosomeMissing_TakesPreviousLevelAndNoBaf()
    {
        foreach (bool multi in new[] { true, false })
        {
            var seg = Segment(N3, multi);
            Assert.Multiple(() =>
            {
                Assert.That(seg.SelectMany(s => s.SegmentedLogR).Any(double.IsNaN), Is.False, "No NaN logR level.");
                for (int i = 1000; i < 1010 && multi; i++) // chr5, all missing
                {
                    Assert.That(seg[0].SegmentedLogR[i], Is.EqualTo(seg[0].SegmentedLogR[999]), "chr5 = prevlevel (last chr2 level).");
                    Assert.That(double.IsNaN(seg[0].SegmentedBaf[i]) && double.IsNaN(seg[1].SegmentedBaf[i]), Is.True, "chr5: no BAF.");
                }

                Assert.That(Enumerable.Range(1000, 10).All(i => double.IsNaN(seg[0].SegmentedBaf[i])), Is.True, "chr5: no BAF.");
            });
        }
    }

    // C-ANA-1 — NaN (R NA) is accepted in logR and heterozygous BAF; infinities and out-of-range BAF still throw.
    [Test]
    public void Segmentation_NonFiniteInput_NaNAcceptedInfinityThrows()
    {
        var (samples, het) = SimulateWithNa(N1);
        var allHet = het.Select(_ => true).ToList();
        IReadOnlyList<OncologyAnalyzer.AlleleSpecificLocus> With(int i, double logR, double baf) =>
            samples[1].Select((l, k) => k == i ? l with { LogR = logR, BAF = baf } : l).ToList();

        Assert.Multiple(() =>
        {
            Assert.DoesNotThrow(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(new[] { samples[0], With(0, double.NaN, double.NaN) }, allHet));
            Assert.DoesNotThrow(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(With(0, double.NaN, double.NaN), allHet));
            foreach (double bad in new[] { double.PositiveInfinity, double.NegativeInfinity })
            {
                Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(new[] { samples[0], With(0, bad, 0.5) }, allHet));
                Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(new[] { samples[0], With(0, 0.0, bad) }, allHet));
                Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(With(0, bad, 0.5), allHet));
                Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(With(0, 0.0, bad), allHet));
            }

            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(With(0, double.NaN, 0.5), 70.0),
                "The all-heterozygous fastAspcf overload (not the ascat.aspcf driver) still requires complete data.");
        });
    }
}
