// ONCO-ASCAT-001 — ASCAT male X non-PAR germline re-genotyping in ascat.aspcf / ascat.asmultipcf (B24 F58)
// Evidence: docs/Evidence/ONCO-ASCAT-001-Evidence.md (§ "Male X non-PAR re-genotyping (F58)")
// TestSpec: tests/TestSpecs/ONCO-ASCAT-001.md (M-MALEX-*, S-MALEX-*, C-MALEX-*)
// Source:  VanLoo-lab/ascat master, ASCAT/R/ascat.aspcf.R (ascat.aspcf: set.seed(seed); nonPAR block) and
//          ASCAT/R/ascat.asmultipcf.R (same block on the first germline); R 4.3.3 base::rank (ties.method = "random" =
//          sort.list(order(x, stats::runif(n)))) and src/main/random.c (do_sample without replacement, R_unif_index).
//
// Every expected value below is the output of the ORIGINAL R code (R 4.3.3, sourced ascat.aspcf.R + ascat.asmultipcf.R):
// ascat.aspcf / ascat.asmultipcf(ASCATobj with gender = "XY", X_nonPAR = c(2699521, 154931043) [hg19], Germline_BAF or
// ascat.gg, out.dir = NA, seed; asmultipcf penalty = 10) on the deterministic tracks generated by Simulate() — the MINSTD
// generator is reproduced verbatim in R, so both sides see bit-identical input. Selected = 1 per X non-PAR probe (in input
// order) that ASCAT re-genotyped heterozygous (row names of Tumor_BAF_segmented). Segments = runs of equal
// Tumor_LogR_segmented within a chromosome; BAF = 1 − Tumor_BAF_segmented of the first heterozygous probe of the segment (NaN = none).

namespace Seqeron.Genomics.Tests.Unit.Oncology;

[TestFixture]
public class OncologyAnalyzer_AscatMaleXNonPar_Tests
{
    private static readonly (long Start, long End) XNonPar = OncologyAnalyzer.AscatSexModel.XNonParHg19;

    // ---- Deterministic male track generator (identical R implementation in the Evidence file) ----

    /// <summary>Kind: 'A' autosome/PAR (germline het unless u &lt; pHom), 'H' forced homozygous autosome, 'X' hemizygous
    /// male X (germline BAF exactly 0/1 with probability 0.4, else within 0.05 of 0/1; tumour BAF = b ± noise).</summary>
    public sealed record Block(string Chrom, int N, long Start, long Step, char Kind, double[] R, double[] B);

    public sealed record Track(int Samples, int Seed, double PHom, bool UseGermlineBaf, int RSeed, Block[] Blocks);

    public readonly record struct Seg(string Chr, long Start, long End, double LogR, double Baf, int N, int NHet);

    public sealed record Expected(string Selected, Seg[][] Samples);

    private static Block Bl(string chrom, int n, long start, long step, char kind, params double[] rb)
    {
        int s = rb.Length / 2;
        return new Block(chrom, n, start, step, kind, rb[..s], rb[s..]);
    }

    private static Block[] XBlocks(double[] r1, double[] r2, double[] b1, double[] b2)
    {
        double[] zero = new double[r1.Length], half = Enumerable.Repeat(0.5, r1.Length).ToArray();
        return new[]
        {
            new Block("X", 30, 100000, 80000, 'A', zero, half),
            new Block("X", 300, 3000000, 400000, 'X', r1, b1),
            new Block("X", 100, 123000000, 300000, 'X', r2, b2),
            new Block("X", 20, 155000000, 10000, 'A', zero, half),
        };
    }

    private static double[] V(params double[] v) => v;

    // M1: Germline_BAF branch, seed 1; 159 exact 0/1 ties all inside the k = 281 selected (autosomal het fraction 0.7033).
    private static readonly Track M1 = new(1, 11, 0.3, true, 1, new[]
    {
        Bl("1", 250, 1000, 1000, 'A', 0, 0.5), Bl("1", 150, 251000, 1000, 'A', -0.6, 0.8), Bl("2", 200, 1000, 1000, 'A', 0.3, 0.65),
    }.Concat(XBlocks(V(-0.5), V(-1.2), V(0.95), V(0.97))).ToArray());

    // M2: Germline_BAF branch, seed 7777; k = 147 < 167 exact ties (DIST = 0), so the runif tie-break decides the selection.
    private static readonly Track M2 = new(1, 22, 0.6, true, 7777, new[]
    {
        Bl("1", 300, 1000, 1000, 'A', 0, 0.5), Bl("1", 60, 301000, 1000, 'H', 0, 0.5), Bl("2", 250, 1000, 1000, 'A', 0.5, 0.7),
    }.Concat(XBlocks(V(-0.4), V(-0.4), V(0.9), V(0.9))).ToArray());

    // M3: no Germline_BAF (ascat.gg genotypes) ⇒ sample(nonPAR_index, k), seed 42.
    private static readonly Track M3 = new(1, 33, 0.35, false, 42, new[]
    {
        Bl("1", 300, 1000, 1000, 'A', 0, 0.5), Bl("2", 200, 1000, 1000, 'A', -0.5, 0.85),
    }.Concat(XBlocks(V(-0.5), V(0.3), V(0.95), V(0.75))).ToArray());

    // M4: Germline_BAF branch with a time-type seed, as ASCAT's default seed = as.integer(Sys.time()) produces (1760090000).
    private static readonly Track M4 = new(1, 44, 0.3, true, 1760090000, new[]
    {
        Bl("1", 300, 1000, 1000, 'A', 0, 0.5), Bl("2", 200, 1000, 1000, 'A', 0.4, 0.7),
    }.Concat(XBlocks(V(-0.5), V(-0.9), V(0.95), V(0.95))).ToArray());

    // K1: asmultipcf, 2 samples, Germline_BAF branch, seed 1, an S1-only X non-PAR step.
    private static readonly Track K1 = new(2, 55, 0.3, true, 1, new[]
    {
        Bl("1", 250, 1000, 1000, 'A', 0, 0, 0.5, 0.5), Bl("1", 150, 251000, 1000, 'A', -0.6, 0, 0.8, 0.5),
        Bl("2", 200, 1000, 1000, 'A', 0.3, 0.3, 0.65, 0.65),
    }.Concat(XBlocks(V(-0.5, -0.5), V(-1.2, -0.5), V(0.95, 0.95), V(0.97, 0.95))).ToArray());

    // K2: asmultipcf, 3 samples, Germline_BAF branch, seed 2024; k = 123 < 146 exact ties.
    private static readonly Track K2 = new(3, 66, 0.7, true, 2024, new[]
    {
        Bl("1", 200, 1000, 1000, 'A', 0, 0, 0, 0.5, 0.5, 0.5), Bl("1", 200, 201000, 1000, 'A', 0.5, 0.5, 0, 0.7, 0.7, 0.5),
        Bl("2", 150, 1000, 1000, 'A', -0.4, -0.4, -0.4, 0.8, 0.8, 0.8),
    }.Concat(XBlocks(V(-0.5, -0.5, -0.5), V(-0.5, 0.2, -0.5), V(0.95, 0.95, 0.95), V(0.95, 0.8, 0.95))).ToArray());

    // K3: asmultipcf, 2 samples, no Germline_BAF ⇒ sample(), seed 99.
    private static readonly Track K3 = new(2, 77, 0.3, false, 99, new[]
    {
        Bl("1", 300, 1000, 1000, 'A', 0, 0, 0.5, 0.5), Bl("2", 200, 1000, 1000, 'A', 0.4, -0.4, 0.7, 0.8),
    }.Concat(XBlocks(V(-0.5, -0.5), V(-1.1, -0.5), V(0.95, 0.95), V(0.97, 0.95))).ToArray());

    /// <summary>
    /// Per probe: 3 MINSTD draws for the germline (ug, g1, g2), then per sample 9 draws (4 × logR noise, BAF orientation,
    /// 4 × BAF noise). Germline BAF: het 0.5 + 0.1·(g1 + g2 − 1); hom g1 &lt; 0.5 ? 0.05·g2 : 1 − 0.05·g2; hemizygous X as
    /// hom but exactly 0/1 when g2 &lt; 0.4. Genotype (ASCAT gg without ascat.gg) = germline BAF in [0.3, 0.7].
    /// </summary>
    private static (List<IReadOnlyList<OncologyAnalyzer.AlleleSpecificLocus>> Samples, List<bool> Het, List<double> Gbaf) Simulate(Track t)
    {
        double s = t.Seed;
        double U()
        {
            s = (s * 48271.0) % 2147483647.0;
            return s / 2147483647.0;
        }

        var samples = new List<List<OncologyAnalyzer.AlleleSpecificLocus>>();
        for (int k = 0; k < t.Samples; k++)
        {
            samples.Add(new List<OncologyAnalyzer.AlleleSpecificLocus>());
        }

        var het = new List<bool>();
        var gbaf = new List<double>();
        foreach (Block block in t.Blocks)
        {
            for (int p = 0; p < block.N; p++)
            {
                double ug = U(), g1 = U(), g2 = U();
                bool hom = block.Kind != 'A' || ug < t.PHom;
                double g = block.Kind == 'X'
                    ? (g1 < 0.5 ? (g2 < 0.4 ? 0.0 : 0.05 * g2) : (g2 < 0.4 ? 1.0 : 1.0 - 0.05 * g2))
                    : hom ? (g1 < 0.5 ? 0.05 * g2 : 1.0 - 0.05 * g2) : 0.5 + 0.1 * (g1 + g2 - 1.0);
                long position = block.Start + p * block.Step;
                for (int k = 0; k < t.Samples; k++)
                {
                    double a1 = U(), a2 = U(), a3 = U(), a4 = U(), us = U(), c1 = U(), c2 = U(), c3 = U(), c4 = U();
                    double x = block.R[k] + 0.2 * ((((a1 + a2) + a3) + a4) - 2.0);
                    double y;
                    if (hom && block.Kind != 'X')
                    {
                        y = us < 0.5 ? 0.0 : 1.0;
                    }
                    else
                    {
                        double b0 = us < 0.5 ? 1.0 - block.B[k] : block.B[k];
                        y = Math.Min(1.0, Math.Max(0.0, b0 + 0.1 * ((((c1 + c2) + c3) + c4) - 2.0)));
                    }

                    samples[k].Add(new OncologyAnalyzer.AlleleSpecificLocus(block.Chrom, position, x, y));
                }

                gbaf.Add(g);
                het.Add(!(g < 0.3 || g > 0.7));
            }
        }

        return (samples.Cast<IReadOnlyList<OncologyAnalyzer.AlleleSpecificLocus>>().ToList(), het, gbaf);
    }

    private static OncologyAnalyzer.AscatMaleXGenotyping MaleX(Track t, List<double> gbaf) =>
        new(OncologyAnalyzer.AscatSexModel.MaleWithXNonPar(OncologyAnalyzer.ReferenceGenome.GRCh37), t.RSeed, t.UseGermlineBaf ? gbaf : null);

    // asmultipcf cohorts run with penalty = 10 (raw joint cost), so the X non-PAR step and per-sample refinement show.
    private const double AsMultiPcfPenalty = 10.0;

    private static IReadOnlyList<OncologyAnalyzer.AspcfSegmentation> Run(Track t)
    {
        var (samples, het, gbaf) = Simulate(t);
        if (t.Samples == 1)
        {
            return new[] { OncologyAnalyzer.SegmentAlleleSpecificAspcf(samples[0], het, MaleX(t, gbaf)) };
        }

        return OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(
            samples, het, AsMultiPcfPenalty, new OncologyAnalyzer.AsMultiPcfOptions { MaleXGenotyping = MaleX(t, gbaf) });
    }

    private static string SelectedBits(OncologyAnalyzer.AspcfSegmentation seg)
    {
        var bits = new System.Text.StringBuilder();
        for (int i = 0; i < seg.Loci.Count; i++)
        {
            var l = seg.Loci[i];
            if (l.Chromosome == "X" && l.Position >= XNonPar.Start && l.Position <= XNonPar.End)
            {
                bits.Append(seg.GermlineHeterozygous[i] ? '1' : '0');
            }
        }

        return bits.ToString();
    }

    // ---- R reference (R 4.3.3, ASCAT master 61ddf3b) ----

    private static readonly Expected M1Expected = new(
        "1111010011101100110110011010111101110010111110111111001110010111111111000111100011111101110111011001110110100101100011011000111110001101101111011011101111111011011111101011101111011111111111111111110111010101111111111100111011111001101110110111001100111010011101101101111111101111011011011101111110110101111011010001010011111110111011111011111110011011110110100000001110111001101011110111111111111100",
        new Seg[][]
        {
            new Seg[]
            {
                new("1", 1000, 250000, 0.0016626419525885235, 0.5, 250, 168),
                new("1", 251000, 400000, -0.59374205546907244, 0.80887080111384613, 150, 107),
                new("2", 1000, 200000, 0.30151708418434348, 0.65619889922410479, 200, 147),
                new("X", 100000, 2020000, -0.018082781923042066, 0.5, 25, 19),
                new("X", 2100000, 2420000, -0.010880623781532341, 0.5, 5, 5),
                new("X", 3000000, 122600000, -0.50107644206118296, 0.94968027488401707, 300, 214),
                new("X", 123000000, 123000000, -0.90630309325936387, double.NaN, 1, 0),
                new("X", 123300000, 152700000, -1.1901351690867303, 0.95723963302410753, 99, 67),
                new("X", 155000000, 155190000, -0.0065728673974856985, 0.5, 20, 14),
            },
        });

    private static readonly Expected M2Expected = new(
        "0010010100000110000010000100000001000111100001100001001100000000101000111100010001100000011000100011101000100110000010101010000000000000100000101100000101111010101011111011010011101000001001110100011010010010001010010010001011000101100001000100000110101111000011100010100101110101000010100001011010100100010100001010100110010000101000000010101001100010000011100010010001111101100001110101001000010000",
        new Seg[][]
        {
            new Seg[]
            {
                new("1", 1000, 360000, -2.007415881284332e-06, 0.5, 360, 124),
                new("2", 1000, 250000, 0.5091657321108346, 0.68754126202435284, 250, 100),
                new("X", 100000, 1940000, -0.035747894859289711, 0.5, 24, 9),
                new("X", 2020000, 2420000, 0.018693985255447826, 0.5, 6, 2),
                new("X", 3000000, 152700000, -0.39763309711992423, 0.90062591532378466, 400, 147),
                new("X", 155000000, 155040000, 0.025890613974021096, 0.5, 5, 3),
                new("X", 155050000, 155190000, 0.013426553532524593, 0.5, 15, 9),
            },
        });

    private static readonly Expected M3Expected = new(
        "1111110001011101010100011011011111111001111000101010011111011110010000110111010011011000101010101101011000111111110101000101011101000001011011011101110111011110110010000010100000011111111100101100111011001111100111100111101111111101000011000111110101110110011011011111101001001010001110110011010111101010001000101111111011111110101110001001100000010011101110011101111111110011110000001110011111110101",
        new Seg[][]
        {
            new Seg[]
            {
                new("1", 1000, 300000, 0.00011606396119237465, 0.5, 300, 170),
                new("2", 1000, 200000, -0.50259951696805638, 0.84259573034850921, 200, 127),
                new("X", 100000, 1940000, 0.027892508238814392, 0.5, 24, 15),
                new("X", 2020000, 2420000, -0.024977243284218607, 0.5, 6, 3),
                new("X", 3000000, 122600000, -0.504694109871065, 0.94221486451383951, 300, 178),
                new("X", 123000000, 152700000, 0.29058851586495921, 0.75205321123860791, 100, 60),
                new("X", 155000000, 155190000, 0.032974981718219339, 0.5, 20, 15),
            },
        });

    private static readonly Expected M4Expected = new(
        "1111001111100100110111111010111000000111110110110001001111111110011111111111111101110110111100110101111111111100110001101111110111111101111010011011111111111001010111101110001010111011110111111001111111111011000111011101111110110101100110100110001110100011010111111111101011111100010110111111001111011111111111110100101000101111101010111011111100111011001101110110111010111111101111001100010001101011",
        new Seg[][]
        {
            new Seg[]
            {
                new("1", 1000, 300000, -0.0014008036072990556, 0.5, 300, 201),
                new("2", 1000, 200000, 0.40486731070925824, 0.70169451550675421, 200, 145),
                new("X", 100000, 2020000, -0.0094734391688711186, 0.5, 25, 17),
                new("X", 2100000, 2420000, -0.040751007348648741, 0.5, 5, 4),
                new("X", 3000000, 122600000, -0.48314770205030888, 0.94222380265697081, 300, 210),
                new("X", 123000000, 155040000, -0.86000717543021532, 0.95080450796524907, 105, 70),
                new("X", 155050000, 155190000, -0.022762996800909603, 0.5, 15, 10),
            },
        });

    private static readonly Expected K1Expected = new(
        "1111011111011101111100110111101111111000000100100001011111111110111011011110011111111011001111011111111001111111111010110011011101111011101001111011011001111111111111010101010001111101111010111100100110111000011011110111111011101100110111111100111101100111111011110101110101110100111111111111100110111100110111100010111111011100101011111011111010111111100100101001110110111111111111110110111111000110",
        new Seg[][]
        {
            new Seg[]
            {
                new("1", 1000, 250000, -0.0056612790581124289, 0.5, 250, 183),
                new("1", 251000, 400000, -0.59699503755491612, 0.79989260436133847, 150, 107),
                new("2", 1000, 200000, 0.29533357747752853, 0.6497881900647785, 200, 134),
                new("X", 100000, 2420000, -0.0028774364926902455, 0.5, 30, 20),
                new("X", 3000000, 122600000, -0.49449837066194274, 0.94510651915841204, 300, 213),
                new("X", 123000000, 152700000, -1.1950872407560642, 0.95205503915779299, 100, 70),
                new("X", 155000000, 155190000, 0.02319127442463826, 0.5, 20, 13),
            },
            new Seg[]
            {
                new("1", 1000, 400000, 0.0073888739395834846, 0.5, 400, 290),
                new("2", 1000, 200000, 0.3052299522097362, 0.64991722467921498, 200, 134),
                new("X", 100000, 2420000, -0.0013039636990539566, 0.5, 30, 20),
                new("X", 3000000, 152700000, -0.49738498197793263, 0.94471087454973668, 400, 283),
                new("X", 155000000, 155190000, -0.012520555189121773, 0.5, 20, 13),
            },
        });

    private static readonly Expected K2Expected = new(
        "0111100000000000010000001001001100010000100001001010010010100001010010000010001101010001001010010100000001001000100011000100100000000100000000011010100100010000001000010110111101001010001110101001110000000101110000000100000100000000001000000001100000111011000010111100000010000110010000000110011000001001000110000100000001100000110001000000000011010100001010111001000010100001011100001111001000100001",
        new Seg[][]
        {
            new Seg[]
            {
                new("1", 1000, 200000, 0.0003760916368924485, 0.5, 200, 67),
                new("1", 201000, 400000, 0.50572514801692459, 0.70212434518249189, 200, 53),
                new("2", 1000, 150000, -0.38578970044562116, 0.80796569759035985, 150, 49),
                new("X", 100000, 2420000, -0.047741041938343262, 0.5, 30, 13),
                new("X", 3000000, 155190000, -0.47758816394620868, 0.92228256006814846, 420, 129),
            },
            new Seg[]
            {
                new("1", 1000, 200000, -0.0012141176775163577, 0.5, 200, 67),
                new("1", 201000, 400000, 0.4913606567323956, 0.70010047530228037, 200, 53),
                new("2", 1000, 150000, -0.40580779533793271, 0.80627188077013356, 150, 49),
                new("X", 100000, 2420000, -0.012861447240937558, 0.5, 30, 13),
                new("X", 3000000, 122600000, -0.50221791725709009, 0.94926523871116486, 300, 90),
                new("X", 123000000, 155190000, 0.15783404434775036, 0.77452630218579932, 120, 39),
            },
            new Seg[]
            {
                new("1", 1000, 400000, -0.008451731696702415, 0.5, 400, 120),
                new("2", 1000, 150000, -0.41184865547274957, 0.78094707594259249, 150, 49),
                new("X", 100000, 2420000, 0.0074346531838029566, 0.5, 30, 13),
                new("X", 3000000, 155190000, -0.47112963571310135, 0.92847036171457376, 420, 129),
            },
        });

    private static readonly Expected K3Expected = new(
        "1010101110101110001101001000111000010111111101110101110111010101111111111110111111111111111011110111111101101010011111110010101101110100011101000011001001101101101011111001101001111000110111110001111111011111110101011100111001011111111100110111111101101111111111111111111111001111111111011011011000011111111101111110101011001011010011101101111111111111110111101111111110111011111111011111100011001111",
        new Seg[][]
        {
            new Seg[]
            {
                new("1", 1000, 300000, -0.004694502421667723, 0.5, 300, 215),
                new("2", 1000, 200000, 0.39876659286709809, 0.69762241957600191, 200, 144),
                new("X", 100000, 2420000, 0.022493046312201628, 0.5, 30, 22),
                new("X", 3000000, 122600000, -0.48315902092920571, 0.94486920083657611, 300, 209),
                new("X", 123000000, 152700000, -1.1229922483139636, 0.95411648230706114, 100, 78),
                new("X", 155000000, 155190000, -0.016595012702324899, 0.5, 20, 14),
            },
            new Seg[]
            {
                new("1", 1000, 300000, -0.0074741996906111949, 0.5, 300, 215),
                new("2", 1000, 200000, -0.39482088465421505, 0.7999183697910186, 200, 144),
                new("X", 100000, 2420000, 0.03458234041676965, 0.5, 30, 22),
                new("X", 3000000, 152700000, -0.49347274589979684, 0.94429149209630703, 400, 287),
                new("X", 155000000, 155190000, 0.011291417130870481, 0.5, 20, 14),
            },
        });

    private static IEnumerable<TestCaseData> ReferenceRuns()
    {
        yield return new TestCaseData(M1, M1Expected).SetName("MaleX_Aspcf_M1_GermlineBaf_Seed1_MatchesAscat");
        yield return new TestCaseData(M2, M2Expected).SetName("MaleX_Aspcf_M2_GermlineBaf_TieBreakByRunif_MatchesAscat");
        yield return new TestCaseData(M3, M3Expected).SetName("MaleX_Aspcf_M3_NoGermlineBaf_Sample_MatchesAscat");
        yield return new TestCaseData(M4, M4Expected).SetName("MaleX_Aspcf_M4_TimeTypeSeed_MatchesAscat");
        yield return new TestCaseData(K1, K1Expected).SetName("MaleX_AsMultiPcf_K1_TwoSamples_MatchesAscat");
        yield return new TestCaseData(K2, K2Expected).SetName("MaleX_AsMultiPcf_K2_ThreeSamples_TieBreak_MatchesAscat");
        yield return new TestCaseData(K3, K3Expected).SetName("MaleX_AsMultiPcf_K3_NoGermlineBaf_Sample_MatchesAscat");
    }

    // M-MALEX-1..7 — re-genotyped X non-PAR probes bit-identical to R; segment extents, probe and heterozygous counts identical;
    // segment logR and BAF ≤ 1e-12 of R.
    [TestCaseSource(nameof(ReferenceRuns))]
    public void MaleXNonParRegenotyping_MatchesAscat(Track track, Expected expected)
    {
        var result = Run(track);

        Assert.That(result, Has.Count.EqualTo(expected.Samples.Length), "One segmentation per sample.");
        Assert.Multiple(() =>
        {
            for (int s = 0; s < expected.Samples.Length; s++)
            {
                Assert.That(SelectedBits(result[s]), Is.EqualTo(expected.Selected), $"Sample {s + 1}: re-genotyped X non-PAR probes.");
                var actual = result[s].Segments;
                var exp = expected.Samples[s];
                Assert.That(actual.Select(a => (a.Chromosome, a.Start, a.End, a.LocusCount, a.HeterozygousLocusCount)),
                    Is.EqualTo(exp.Select(e => (e.Chr, e.Start, e.End, e.N, e.NHet))), $"Sample {s + 1} breakpoints.");
                if (actual.Count != exp.Length)
                {
                    continue;
                }

                for (int i = 0; i < exp.Length; i++)
                {
                    Assert.That(actual[i].MeanLogR, Is.EqualTo(exp[i].LogR).Within(1e-12), $"Sample {s + 1} segment {i + 1} logR.");
                    if (double.IsNaN(exp[i].Baf))
                    {
                        Assert.That(actual[i].HasBaf, Is.False, $"Sample {s + 1} segment {i + 1}: no heterozygous probe.");
                    }
                    else
                    {
                        Assert.That(actual[i].MeanBAF, Is.EqualTo(exp[i].Baf).Within(1e-12), $"Sample {s + 1} segment {i + 1} BAF.");
                    }
                }
            }
        });
    }

    // M-MALEX-8 — the selected count is round(m · h_auto): M1 m = 400, h_auto = 422/600 ⇒ round(281.33) = 281 (R: 281).
    [Test]
    public void MaleXNonParRegenotyping_SelectedCount_IsAutosomeMatchedFraction()
    {
        Assert.That(M1Expected.Selected.Count(c => c == '1'), Is.EqualTo(281));
        Assert.That(SelectedBits(Run(M1)[0]).Count(c => c == '1'), Is.EqualTo(281));
    }

    // S-MALEX-1 — a female model, or a male without X non-PAR, leaves the genotypes and the segmentation unchanged
    // (ascat.aspcf: !is.null(X_nonPAR) && gender == "XY").
    [TestCase(false)]
    [TestCase(true)]
    public void MaleXNonParRegenotyping_Inactive_EqualsDefaultOverload(bool maleWithoutNonPar)
    {
        var (samples, het, gbaf) = Simulate(M1);
        var model = maleWithoutNonPar ? OncologyAnalyzer.AscatSexModel.Male : OncologyAnalyzer.AscatSexModel.Female;
        var plain = OncologyAnalyzer.SegmentAlleleSpecificAspcf(samples[0], het);
        var withSpec = OncologyAnalyzer.SegmentAlleleSpecificAspcf(samples[0], het, new OncologyAnalyzer.AscatMaleXGenotyping(model, 1, gbaf));

        Assert.Multiple(() =>
        {
            Assert.That(withSpec.GermlineHeterozygous, Is.EqualTo(plain.GermlineHeterozygous));
            Assert.That(withSpec.SegmentedLogR, Is.EqualTo(plain.SegmentedLogR));
            Assert.That(withSpec.Segments, Is.EqualTo(plain.Segments));
        });
    }

    // S-MALEX-2 — with ≤ 5 known non-PAR probes ASCAT leaves the genotypes alone (length(nonPAR_index) > 5).
    [Test]
    public void MaleXNonParRegenotyping_FiveNonParProbes_Unchanged()
    {
        var loci = new List<OncologyAnalyzer.AlleleSpecificLocus>();
        var het = new List<bool>();
        for (int i = 0; i < 20; i++)
        {
            loci.Add(new("1", 1000 + i, 0.0, 0.5));
            het.Add(true);
        }

        for (int i = 0; i < 5; i++)
        {
            loci.Add(new("X", 5_000_000 + i, -0.5, 0.0));
            het.Add(false);
        }

        var spec = new OncologyAnalyzer.AscatMaleXGenotyping(OncologyAnalyzer.AscatSexModel.MaleWithXNonPar(OncologyAnalyzer.ReferenceGenome.GRCh37), 1);
        var result = OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, het, spec);
        Assert.That(result.GermlineHeterozygous, Is.EqualTo(het));
    }

    // S-MALEX-3 — the same seed reproduces the draw; ASCAT's default seed is as.integer(Sys.time()) (Unix seconds).
    [Test]
    public void MaleXNonParRegenotyping_SeedReproducible_DefaultSeedIsUnixSeconds()
    {
        long before = DateTimeOffset.UtcNow.ToUnixTimeSeconds();
        var spec = new OncologyAnalyzer.AscatMaleXGenotyping(OncologyAnalyzer.AscatSexModel.MaleWithXNonPar(OncologyAnalyzer.ReferenceGenome.GRCh37));
        long after = DateTimeOffset.UtcNow.ToUnixTimeSeconds();

        Assert.Multiple(() =>
        {
            Assert.That((long)spec.Seed, Is.InRange(before, after));
            string first = SelectedBits(Run(M3)[0]);
            Assert.That(SelectedBits(Run(M3)[0]), Is.EqualTo(first));
            Assert.That(SelectedBits(Run(M3 with { RSeed = 43 })[0]), Is.Not.EqualTo(M3Expected.Selected));
        });
    }

    // C-MALEX-1 — argument contract.
    [Test]
    public void MaleXNonParRegenotyping_InvalidArguments_Throw()
    {
        var (samples, het, gbaf) = Simulate(M1);
        var male = OncologyAnalyzer.AscatSexModel.MaleWithXNonPar(OncologyAnalyzer.ReferenceGenome.GRCh37);
        var allHom = het.Select(_ => false).ToList();

        Assert.Multiple(() =>
        {
            Assert.Throws<ArgumentNullException>(() => _ = new OncologyAnalyzer.AscatMaleXGenotyping(null!, 1));
            Assert.Throws<ArgumentException>(() => _ = new OncologyAnalyzer.AscatMaleXGenotyping(male, 1, new[] { 0.5, 1.2 }));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(samples[0], het, (OncologyAnalyzer.AscatMaleXGenotyping)null!));
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(
                samples[0], het, new OncologyAnalyzer.AscatMaleXGenotyping(male, 1, gbaf.Take(10).ToList())));
            // sample(nonPAR_index, NA) fails in R when no autosomal probe is heterozygous.
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(
                samples[0], allHom, new OncologyAnalyzer.AscatMaleXGenotyping(male, 1)));
        });
    }

    // S-MALEX-4 — with germline BAF and no heterozygous autosome, rank(DIST) <= NA selects nothing: every non-PAR probe homozygous.
    [Test]
    public void MaleXNonParRegenotyping_NoAutosomalHet_WithGermlineBaf_AllNonParHomozygous()
    {
        var (samples, het, gbaf) = Simulate(M1);
        var allHom = het.Select(_ => false).ToList();
        var loci = samples[0].Select(l => l with { BAF = 0.5 }).ToList();
        var result = OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, allHom,
            new OncologyAnalyzer.AscatMaleXGenotyping(OncologyAnalyzer.AscatSexModel.MaleWithXNonPar(OncologyAnalyzer.ReferenceGenome.GRCh37), 1, gbaf));
        Assert.That(result.GermlineHeterozygous, Has.None.True);
    }
}
