// ONCO-ASCAT-001 — ASCAT sex-chromosome model: male haploid X (non-PAR) / Y (B24 F38)
// Evidence: docs/Evidence/ONCO-ASCAT-001-Evidence.md (§ "Sex-chromosome model (F38)")
// TestSpec: tests/TestSpecs/ONCO-ASCAT-001.md (M-ASCAT-X*, S-ASCAT-X*, C-ASCAT-X*)
// Source:  VanLoo-lab/ascat master, ASCAT/R/ascat.runAscat.R (runASCAT: haploidchrs / nullchrs / diploidprobes,
//          seg_raw nAraw/nBraw; diploidprobes_fixnonPAR) and ASCAT/R/ascat.loadData.R (gender default "XX";
//          X_nonPAR per genomeVersion: hg19 c(2699521, 154931043), hg38 c(2781480, 155701382), CHM13 c(2394411, 153925834)).
//
// Every expected value below is the output of the ORIGINAL R code (R 4.3.3, sourced ascat.aspcf.R + ascat.runAscat.R,
// GenomicRanges 1.54.1 for diploidprobes_fixnonPAR, plots stubbed): ascat.aspcf(ASCATobj, ascat.gg, penalty = 70)
// with X_nonPAR = NULL (so the aspcf-side random re-genotyping of male non-PAR probes is not exercised), then
// ASCATobj$gender / ASCATobj$X_nonPAR set and ascat.runAscat(gamma = 1). The genomes are generated by Simulate(),
// reproduced verbatim in R (MINSTD, exact in IEEE doubles), so both sides see bit-identical input.

namespace Seqeron.Genomics.Tests.Unit.Oncology;

[TestFixture]
public class OncologyAnalyzer_AscatSexChromosome_Tests
{
    // Pos0 < 0: position = 1000 · (global 1-based probe index); otherwise Pos0 + Step · (index within the block).
    public readonly record struct Block(string Chrom, int N, double R, double B, bool ForceHom, long Pos0 = -1, long Step = 0);

    public sealed record Genome(string Name, int Seed, double PHom, Block[] Blocks)
    {
        public override string ToString() => Name;
    }

    private static readonly OncologyAnalyzer.AscatSexModel Male = OncologyAnalyzer.AscatSexModel.Male;
    private static readonly OncologyAnalyzer.AscatSexModel Female = OncologyAnalyzer.AscatSexModel.Female;

    // M2: custom X non-PAR [890000, 1090000] cutting through the PAR1 segment (873000–907000: overlap 17001/34001 > 0.5
    //     ⇒ haploid) and the PAR2 segment (1078000–1122000: overlap 12001/45001 ≤ 0.5 ⇒ diploid).
    private static readonly OncologyAnalyzer.AscatSexModel M2Model =
        new(OncologyAnalyzer.AscatGender.XY, (890_000L, 1_090_000L));

    // M3: ASCAT's hg19 X non-PAR (genomeVersion = "hg19").
    private static readonly OncologyAnalyzer.AscatSexModel M3Model =
        OncologyAnalyzer.AscatSexModel.MaleWithXNonPar(OncologyAnalyzer.ReferenceGenome.GRCh37);

    // M1: rho 0.7 / psi 2.4 autosomes (as G1 of the F36/F37 suite); X: 120 probes 1 copy (homozygous) + 80 probes
    //     2 copies; Y: 60 probes 1 copy + 40 probes deleted. Whole X haploid (X_nonPAR = NULL).
    private static readonly Genome M1 = new("M1", 11, 0.3, new Block[]
    {
        new("1", 150, -0.189, 0.5, false), new("1", 100, 0.2439, 0.6296, false), new("1", 30, 0.2439, 0.6296, true),
        new("1", 50, -1.926, 0.5, true), new("1", 30, 0.2439, 0.6296, true), new("1", 100, 0.2439, 0.6296, false),
        new("2", 150, -0.8105, 0.7692, false), new("2", 150, 0.5765, 0.5, false), new("3", 120, -0.189, 0.85, true),
        new("4", 100, 0.5765, 0.7059, false), new("4", 100, -0.189, 0.5, false),
        new("X", 120, -1.189, 0.5, true), new("X", 80, -0.4235, 0.5, false), new("Y", 60, -1.189, 0.5, false),
        new("Y", 40, -2.926, 0.5, true),
    });

    // M2: rho 0.55 / psi 2.2 autosomes (G2); X: PAR1 2 copies, non-PAR 1 and 2 copies, PAR2 3 copies; Y 1 copy.
    private static readonly Genome M2 = new("M2", 22, 0.25, new Block[]
    {
        new("1", 200, -0.0772, 0.5, false), new("1", 40, -0.0772, 0.5, true), new("1", 40, 0.2733, 0.8235, true),
        new("1", 200, 0.2733, 0.8235, false), new("2", 150, -0.5412, 0.6897, false), new("2", 150, 0.2733, 0.6078, false),
        new("3", 12, 0.555, 0.5, false), new("4", 80, -0.5412, 0.6897, true),
        new("X", 40, -0.0772, 0.5, false), new("X", 100, -1.0772, 0.5, true), new("X", 60, -0.445, 0.5, true),
        new("X", 50, 0.2733, 0.6078, false), new("Y", 50, -1.0772, 0.5, true),
    });

    // M3: rho 0.9 / psi 3.3 autosomes (G3); X on hg19 coordinates: PAR1 (0.1–2.42 Mb), non-PAR 1 copy (3–152 Mb) and
    //     3 copies (153–154.18 Mb), PAR2 (155.0–155.145 Mb); Y 2 copies + deletion.
    private static readonly Genome M3 = new("M3", 33, 0.35, new Block[]
    {
        new("1", 150, 0.2615, 0.5, false), new("1", 150, 0.2615, 0.7368, false), new("2", 120, -0.6645, 0.95, false),
        new("2", 60, -0.6645, 0.95, true), new("2", 60, 0.2615, 0.9737, true), new("2", 60, -0.6645, 0.95, true),
        new("2", 100, -0.6645, 0.95, false), new("3", 200, 0.5682, 0.5957, false), new("3", 100, -0.1284, 0.6552, false),
        new("4", 100, -0.1284, 0.9655, true),
        new("X", 30, -0.6645, 0.5, false, 100_000, 80_000), new("X", 150, -1.6645, 0.5, true, 3_000_000, 1_000_000),
        new("X", 60, -0.179, 0.5, true, 153_000_000, 20_000), new("X", 30, -0.6645, 0.5, false, 155_000_000, 5_000),
        new("Y", 50, -0.7385, 0.5, true), new("Y", 30, -4.9864, 0.5, true),
    });

    /// <summary>
    /// Per probe: 10 MINSTD draws (genotype, 4 × logR noise, BAF orientation, 4 × BAF noise), exactly as the F36/F37
    /// generator; positions per <see cref="Block"/>.
    /// </summary>
    private static (List<OncologyAnalyzer.AlleleSpecificLocus> Loci, List<bool> Het) Simulate(Genome g)
    {
        double s = g.Seed;
        double U()
        {
            s = (s * 48271.0) % 2147483647.0;
            return s / 2147483647.0;
        }

        var loci = new List<OncologyAnalyzer.AlleleSpecificLocus>();
        var het = new List<bool>();
        foreach (Block block in g.Blocks)
        {
            for (int p = 0; p < block.N; p++)
            {
                double ug = U(), a1 = U(), a2 = U(), a3 = U(), a4 = U(), us = U(), c1 = U(), c2 = U(), c3 = U(), c4 = U();
                bool hom = block.ForceHom || ug < g.PHom;
                double x = block.R + 0.2 * ((((a1 + a2) + a3) + a4) - 2.0);
                double y;
                if (hom)
                {
                    y = us < 0.5 ? 0.0 : 1.0;
                }
                else
                {
                    double b0 = us < 0.5 ? 1.0 - block.B : block.B;
                    y = Math.Min(1.0, Math.Max(0.0, b0 + 0.1 * ((((c1 + c2) + c3) + c4) - 2.0)));
                }

                long pos = block.Pos0 < 0 ? (loci.Count + 1) * 1000L : block.Pos0 + p * block.Step;
                loci.Add(new OncologyAnalyzer.AlleleSpecificLocus(block.Chrom, pos, x, y));
                het.Add(!hom);
            }
        }

        return (loci, het);
    }

    private static OncologyAnalyzer.AspcfSegmentation Segment(Genome g)
    {
        var (loci, het) = Simulate(g);
        return OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, het, 70.0);
    }

    private static IReadOnlyList<OncologyAnalyzer.AlleleSpecificSegmentSummary> HetOnlySummaries(Genome g)
    {
        var (loci, het) = Simulate(g);
        return OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci.Where((_, i) => het[i]), 70.0);
    }

    private static void AssertFit(OncologyAnalyzer.PurityPloidyFit fit, double rho, double psi, double ploidy,
        double goodnessOfFit, (int Major, int Minor)[] segRaw)
    {
        Assert.Multiple(() =>
        {
            Assert.That(fit.Purity, Is.EqualTo(rho), "runASCAT purity.");
            Assert.That(fit.Psi, Is.EqualTo(psi), "runASCAT psi.");
            Assert.That(fit.Ploidy, Is.EqualTo(ploidy), "ASCAT ploidy = mean(nA + nB) over all probes.");
            Assert.That(fit.GoodnessOfFit, Is.EqualTo(goodnessOfFit), "runASCAT goodnessOfFit.");
            Assert.That(fit.Segments.Select(s => (s.MajorCopyNumber, s.MinorCopyNumber)), Is.EqualTo(segRaw),
                "seg_raw nMajor / nMinor per segment.");
        });
    }

    #region runASCAT gender / X_nonPAR on germline-aware segmentations (FitPurityPloidyFromAspcf)

    // runASCAT (gamma = 1, defaults) on the ascat.aspcf output: purity, psi, ploidy, goodnessOfFit, seg_raw (nMajor, nMinor).
    private static IEnumerable<TestCaseData> GermlineReferenceFits()
    {
        yield return new TestCaseData(M1, Male, 0.69999999999999996, 2.4500000000000002, 2.181159420289855, 99.937918942624279,
                new[] { (1, 1), (2, 1), (2, 1), (0, 0), (2, 1), (2, 1), (1, 0), (2, 2), (2, 0), (3, 1), (1, 1), (1, 0), (2, 0), (2, 0), (1, 0), (1, 0), (0, 0) })
            .SetName("RunAscatXY_M1_Germline_MatchesRunAscat");
        yield return new TestCaseData(M1, Female, 0.69999999999999996, 2.4500000000000002, 2.1775362318840581, 99.937918942624279,
                new[] { (1, 1), (2, 1), (2, 1), (0, 0), (2, 1), (2, 1), (1, 0), (2, 2), (2, 0), (3, 1), (1, 1), (1, 0), (1, 0), (1, 1), (1, 0), (1, 0), (0, 0) })
            .SetName("RunAscatXX_M1_Germline_MatchesRunAscat");
        yield return new TestCaseData(M2, M2Model, 0.53000000000000003, 2.3500000000000001, 2.0981228668941978, 99.634551649302338,
                new[] { (1, 1), (3, 0), (1, 0), (2, 1), (2, 2), (1, 0), (3, 0), (3, 0), (1, 0), (2, 0), (2, 1), (1, 0) })
            .SetName("RunAscatXY_M2_Germline_MatchesRunAscat");
        yield return new TestCaseData(M2, Female, 0.53000000000000003, 2.3500000000000001, 1.8805460750853242, 99.634551649302338,
                new[] { (1, 1), (3, 0), (1, 0), (2, 1), (2, 2), (1, 0), (1, 1), (1, 1), (0, 0), (1, 0), (2, 1), (0, 0) })
            .SetName("RunAscatXX_M2_Germline_MatchesRunAscat");
        yield return new TestCaseData(M2, Male, 0.53000000000000003, 2.3500000000000001, 2.1365187713310578, 99.634551649302338,
                new[] { (1, 1), (3, 0), (1, 0), (2, 1), (2, 2), (1, 0), (3, 0), (3, 0), (1, 0), (2, 0), (4, 0), (1, 0) })
            .SetName("RunAscatXY_M2_NoNonPar_WholeXHaploid_MatchesRunAscat");
        yield return new TestCaseData(M3, M3Model, 0.92000000000000004, 3.1499999999999999, 2.9482758620689653, 98.658353206884712,
                new[] { (2, 2), (3, 1), (2, 0), (4, 0), (2, 0), (3, 2), (2, 1), (3, 0), (1, 1), (1, 1), (1, 0), (3, 0), (1, 1), (2, 0), (0, 0) })
            .SetName("RunAscatXY_M3_Germline_MatchesRunAscat");
        yield return new TestCaseData(M3, Female, 0.92000000000000004, 3.1499999999999999, 2.9482758620689653, 98.658353206884712,
                new[] { (2, 2), (3, 1), (2, 0), (4, 0), (2, 0), (3, 2), (2, 1), (3, 0), (1, 1), (1, 1), (1, 0), (2, 1), (1, 1), (2, 0), (0, 0) })
            .SetName("RunAscatXX_M3_Germline_MatchesRunAscat");
        yield return new TestCaseData(M3, Male, 0.92000000000000004, 3.1499999999999999, 2.9482758620689653, 98.658353206884712,
                new[] { (2, 2), (3, 1), (2, 0), (4, 0), (2, 0), (3, 2), (2, 1), (3, 0), (2, 0), (2, 0), (1, 0), (3, 0), (2, 0), (2, 0), (0, 0) })
            .SetName("RunAscatXY_M3_NoNonPar_WholeXHaploid_MatchesRunAscat");
    }

    // M-ASCAT-X1..X8 — ascat.aspcf → runASCAT end to end for gender "XY" (whole-X haploid, custom X_nonPAR, hg19
    // X_nonPAR) and "XX" on three male genomes with X PAR + non-PAR probes and Y.
    [TestCaseSource(nameof(GermlineReferenceFits))]
    public void FitPurityPloidyFromAspcf_SexModel_MatchesRunAscat(Genome genome, OncologyAnalyzer.AscatSexModel model,
        double rho, double psi, double ploidy, double goodnessOfFit, (int Major, int Minor)[] segRaw)
    {
        AssertFit(OncologyAnalyzer.FitPurityPloidyFromAspcf(Segment(genome), model), rho, psi, ploidy, goodnessOfFit, segRaw);
    }

    #endregion

    #region runASCAT gender / X_nonPAR on segment summaries (FitPurityPloidy)

    // runASCAT on the heterozygous probes only (ascat.aspcf with every probe heterozygous) = the summary path.
    private static IEnumerable<TestCaseData> HetOnlyReferenceFits()
    {
        yield return new TestCaseData(M1, Male, 0.69999999999999996, 2.4500000000000002, 2.4579831932773111, 99.950135206703436,
                new[] { (1, 1), (2, 1), (1, 0), (2, 2), (3, 1), (1, 1), (2, 0), (1, 0) })
            .SetName("RunAscatXY_M1_HetOnlySummaries_MatchesRunAscat");
        yield return new TestCaseData(M1, Female, 0.69999999999999996, 2.4500000000000002, 2.4579831932773111, 99.950135206703436,
                new[] { (1, 1), (2, 1), (1, 0), (2, 2), (3, 1), (1, 1), (1, 1), (1, 0) })
            .SetName("RunAscatXX_M1_HetOnlySummaries_MatchesRunAscat");
        yield return new TestCaseData(M2, M2Model, 0.53000000000000003, 2.3500000000000001, 2.3914529914529914, 99.661294751227899,
                new[] { (1, 1), (3, 0), (1, 0), (2, 1), (2, 2), (3, 0), (2, 1) })
            .SetName("RunAscatXY_M2_HetOnlySummaries_MatchesRunAscat");
        yield return new TestCaseData(M2, Female, 0.53000000000000003, 2.3500000000000001, 2.3384615384615386, 99.661294751227899,
                new[] { (1, 1), (3, 0), (1, 0), (2, 1), (2, 2), (1, 1), (2, 1) })
            .SetName("RunAscatXX_M2_HetOnlySummaries_MatchesRunAscat");
        yield return new TestCaseData(M3, M3Model, 0.91000000000000003, 3.2000000000000002, 3.4351687388987568, 98.662279834887002,
                new[] { (2, 2), (3, 1), (2, 0), (3, 2), (2, 1), (2, 0) })
            .SetName("RunAscatXY_M3_HetOnlySummaries_MatchesRunAscat");
        yield return new TestCaseData(M3, Female, 0.91000000000000003, 3.2000000000000002, 3.4351687388987568, 98.662279834887002,
                new[] { (2, 2), (3, 1), (2, 0), (3, 2), (2, 1), (1, 1) })
            .SetName("RunAscatXX_M3_HetOnlySummaries_MatchesRunAscat");
    }

    // M-ASCAT-X9..X14 — the summary-level fit with a sex model reproduces runASCAT on the het-only genome
    // (M3: one X segment 100000–155135000 spanning PAR1, non-PAR and PAR2 is > 50 % non-PAR ⇒ haploid 2:0).
    [TestCaseSource(nameof(HetOnlyReferenceFits))]
    public void FitPurityPloidy_SexModel_MatchesRunAscat(Genome genome, OncologyAnalyzer.AscatSexModel model,
        double rho, double psi, double ploidy, double goodnessOfFit, (int Major, int Minor)[] segRaw)
    {
        AssertFit(OncologyAnalyzer.FitPurityPloidy(HetOnlySummaries(genome), model), rho, psi, ploidy, goodnessOfFit, segRaw);
    }

    #endregion

    #region Invariants

    private static IEnumerable<Genome> Genomes() => new[] { M1, M2, M3 };

    // S-ASCAT-X1 — XX is the default: the gender-less entry points are bit-identical to AscatSexModel.Female
    // (and the XX expectations above are R's runASCAT with gender = "XX": X and Y use the diploid equations).
    [TestCaseSource(nameof(Genomes))]
    public void GenderLessOverloads_EqualFemaleModel(Genome genome)
    {
        var seg = Segment(genome);
        var summaries = HetOnlySummaries(genome);
        var a = OncologyAnalyzer.FitPurityPloidyFromAspcf(seg);
        var b = OncologyAnalyzer.FitPurityPloidyFromAspcf(seg, Female);
        var c = OncologyAnalyzer.FitPurityPloidy(summaries);
        var d = OncologyAnalyzer.FitPurityPloidy(summaries, Female);
        var e = OncologyAnalyzer.EvaluatePurityPloidy(summaries, a.Purity, a.Psi);
        var f = OncologyAnalyzer.EvaluatePurityPloidy(summaries, Female, a.Purity, a.Psi);
        var g = OncologyAnalyzer.EvaluatePurityPloidyFromAspcf(seg, a.Purity, a.Psi);
        var h = OncologyAnalyzer.EvaluatePurityPloidyFromAspcf(seg, Female, a.Purity, a.Psi);

        Assert.Multiple(() =>
        {
            foreach (var (x, y, what) in new[] { (a, b, "FromAspcf"), (c, d, "summaries"), (e, f, "manual"), (g, h, "manual FromAspcf") })
            {
                Assert.That((y.Purity, y.Psi, y.Ploidy, y.GoodnessOfFit, y.IsNonAberrant),
                    Is.EqualTo((x.Purity, x.Psi, x.Ploidy, x.GoodnessOfFit, x.IsNonAberrant)), what);
                Assert.That(y.Segments, Is.EqualTo(x.Segments), what);
            }
        });
    }

    // S-ASCAT-X2 — the sex model never changes the fit (ASCAT: autoprobes = !(chr %in% sexchromosomes) for any gender):
    // purity, psi, GoF and the non-aberrant flag are identical; autosomal segments are identical; haploid X/Y segments
    // carry nB = 0.
    [TestCaseSource(nameof(Genomes))]
    public void MaleModel_ChangesOnlySexChromosomeSegments(Genome genome)
    {
        var seg = Segment(genome);
        var female = OncologyAnalyzer.FitPurityPloidyFromAspcf(seg, Female);
        var male = OncologyAnalyzer.FitPurityPloidyFromAspcf(seg, Male);

        Assert.Multiple(() =>
        {
            Assert.That((male.Purity, male.Psi, male.GoodnessOfFit, male.IsNonAberrant),
                Is.EqualTo((female.Purity, female.Psi, female.GoodnessOfFit, female.IsNonAberrant)));
            for (int i = 0; i < male.Segments.Count; i++)
            {
                string chr = male.Segments[i].Chromosome;
                if (chr is "X" or "Y")
                {
                    Assert.That(male.Segments[i].MinorCopyNumber, Is.Zero, $"Segment {i + 1} ({chr}): haploid ⇒ nB = 0.");
                }
                else
                {
                    Assert.That(male.Segments[i], Is.EqualTo(female.Segments[i]), $"Segment {i + 1}: autosome unchanged.");
                }
            }
        });
    }

    // S-ASCAT-X3 — rho_manual / psi_manual with a sex model at the fitted optimum reproduces the fit.
    [Test]
    public void EvaluateWithSexModel_AtOptimum_ReproducesFit()
    {
        var seg = Segment(M2);
        var fit = OncologyAnalyzer.FitPurityPloidyFromAspcf(seg, M2Model);
        var manual = OncologyAnalyzer.EvaluatePurityPloidyFromAspcf(seg, M2Model, fit.Purity, fit.Psi);
        var summaries = HetOnlySummaries(M3);
        var sFit = OncologyAnalyzer.FitPurityPloidy(summaries, M3Model);
        var sManual = OncologyAnalyzer.EvaluatePurityPloidy(summaries, M3Model, sFit.Purity, sFit.Psi);

        Assert.Multiple(() =>
        {
            Assert.That((manual.GoodnessOfFit, manual.Ploidy), Is.EqualTo((fit.GoodnessOfFit, fit.Ploidy)));
            Assert.That(manual.Segments, Is.EqualTo(fit.Segments));
            Assert.That((sManual.GoodnessOfFit, sManual.Ploidy), Is.EqualTo((sFit.GoodnessOfFit, sFit.Ploidy)));
            Assert.That(sManual.Segments, Is.EqualTo(sFit.Segments));
            Assert.That(OncologyAnalyzer.TryFitPurityPloidyFromAspcf(seg, M2Model, out var t1), Is.True);
            Assert.That(t1.Segments, Is.EqualTo(fit.Segments));
            Assert.That(OncologyAnalyzer.TryFitPurityPloidy(summaries, M3Model, out var t2), Is.True);
            Assert.That(t2.Segments, Is.EqualTo(sFit.Segments));
        });
    }

    // S-ASCAT-X4 — hand-computed haploid / diploid equations and the > 50 % non-PAR overlap rule. rho = 0.5, psi = 2,
    // gamma = 1, logR 0 ⇒ (1 − rho)·2 + rho·psi = 2: haploid nAraw = (0.5 − 1 + 2·2⁰)/0.5 = 3 ⇒ 3:0; diploid with
    // BAF 0.5: nA = nB = (0.5 − 1 + 0.5·2)/0.5 = 1 ⇒ 1:1. X segment [1, 10]: overlap with [6, 100] = 5/10 (not > 0.5)
    // ⇒ diploid; with [5, 100] = 6/10 ⇒ haploid; Y is haploid regardless of X_nonPAR; "chrX" is X.
    [Test]
    public void HaploidEquationAndNonParOverlapRule_HandComputed()
    {
        var summaries = new List<OncologyAnalyzer.AlleleSpecificSegmentSummary>
        {
            new("1", 1, 100, 0.0, 0.5, 10),
            new("X", 1, 10, 0.0, 0.5, 10),
            new("chrY", 1, 10, 0.0, 0.5, 10),
        };

        (int, int)[] Run(OncologyAnalyzer.AscatSexModel m) => OncologyAnalyzer.EvaluatePurityPloidy(summaries, m, 0.5, 2.0)
            .Segments.Select(s => (s.MajorCopyNumber, s.MinorCopyNumber)).ToArray();

        Assert.Multiple(() =>
        {
            Assert.That(Run(Female), Is.EqualTo(new[] { (1, 1), (1, 1), (1, 1) }), "XX: X and Y diploid.");
            Assert.That(Run(Male), Is.EqualTo(new[] { (1, 1), (3, 0), (3, 0) }), "XY, no X_nonPAR: X and Y haploid.");
            Assert.That(Run(new(OncologyAnalyzer.AscatGender.XY, (6L, 100L))), Is.EqualTo(new[] { (1, 1), (1, 1), (3, 0) }),
                "Overlap 5/10 = 0.5 is not > 0.5 ⇒ X segment diploid (PAR).");
            Assert.That(Run(new(OncologyAnalyzer.AscatGender.XY, (5L, 100L))), Is.EqualTo(new[] { (1, 1), (3, 0), (3, 0) }),
                "Overlap 6/10 > 0.5 ⇒ X segment haploid (non-PAR).");
            Assert.That(Run(new(OncologyAnalyzer.AscatGender.XY, (20L, 100L))), Is.EqualTo(new[] { (1, 1), (1, 1), (3, 0) }),
                "No overlap ⇒ diploid.");
            Assert.That(Run(new(OncologyAnalyzer.AscatGender.XX, (1L, 100L))), Is.EqualTo(new[] { (1, 1), (1, 1), (1, 1) }),
                "X_nonPAR is ignored for XX.");
            Assert.That(OncologyAnalyzer.EvaluatePurityPloidy(summaries, Male, 0.5, 2.0).Ploidy, Is.EqualTo(8.0 / 3.0),
                "Ploidy = probe-weighted mean total (2 + 3 + 3)/3.");
        });
    }

    // S-ASCAT-X5 — a deleted haploid segment: nAraw < 0 ⇒ nA + nB < 0 ⇒ 0:0 (negative-value correction).
    [Test]
    public void HaploidSegment_NegativeRawCopyNumber_IsZero()
    {
        var summaries = new List<OncologyAnalyzer.AlleleSpecificSegmentSummary>
        {
            new("1", 1, 100, 0.0, 0.5, 10),
            new("Y", 1, 10, -5.0, 0.5, 10), // nAraw = (0.5 − 1 + 2·2⁻⁵)/0.5 = −0.875
        };
        var fit = OncologyAnalyzer.EvaluatePurityPloidy(summaries, Male, 0.5, 2.0);
        Assert.That((fit.Segments[1].MajorCopyNumber, fit.Segments[1].MinorCopyNumber), Is.EqualTo((0, 0)));
    }

    // S-ASCAT-X6 — presets are ASCAT's ascat.loadData X_nonPAR constants.
    [Test]
    public void Presets_AreAscatConstants()
    {
        Assert.Multiple(() =>
        {
            Assert.That(OncologyAnalyzer.AscatSexModel.XNonParHg19, Is.EqualTo((2_699_521L, 154_931_043L)));
            Assert.That(OncologyAnalyzer.AscatSexModel.XNonParHg38, Is.EqualTo((2_781_480L, 155_701_382L)));
            Assert.That(OncologyAnalyzer.AscatSexModel.XNonParChm13, Is.EqualTo((2_394_411L, 153_925_834L)));
            var hg19 = OncologyAnalyzer.AscatSexModel.MaleWithXNonPar(OncologyAnalyzer.ReferenceGenome.GRCh37);
            var hg38 = OncologyAnalyzer.AscatSexModel.MaleWithXNonPar(OncologyAnalyzer.ReferenceGenome.GRCh38);
            Assert.That((hg19.Gender, hg19.XNonPar), Is.EqualTo((OncologyAnalyzer.AscatGender.XY, ((long, long)?)(2_699_521L, 154_931_043L))));
            Assert.That((hg38.Gender, hg38.XNonPar), Is.EqualTo((OncologyAnalyzer.AscatGender.XY, ((long, long)?)(2_781_480L, 155_701_382L))));
            Assert.That((Female.Gender, Female.XNonPar), Is.EqualTo((OncologyAnalyzer.AscatGender.XX, ((long, long)?)null)));
            Assert.That((Male.Gender, Male.XNonPar), Is.EqualTo((OncologyAnalyzer.AscatGender.XY, ((long, long)?)null)));
        });
    }

    // C-ASCAT-X1 — invalid arguments.
    [Test]
    public void SexModel_InvalidArguments_Throw()
    {
        var seg = Segment(M1);
        var summaries = HetOnlySummaries(M1);
        Assert.Multiple(() =>
        {
            Assert.Throws<ArgumentOutOfRangeException>(() => _ = new OncologyAnalyzer.AscatSexModel(OncologyAnalyzer.AscatGender.XY, (10L, 9L)));
            Assert.Throws<ArgumentOutOfRangeException>(() => _ = new OncologyAnalyzer.AscatSexModel((OncologyAnalyzer.AscatGender)7));
            Assert.Throws<ArgumentOutOfRangeException>(() => OncologyAnalyzer.AscatSexModel.MaleWithXNonPar((OncologyAnalyzer.ReferenceGenome)9));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.FitPurityPloidy(summaries, (OncologyAnalyzer.AscatSexModel)null!));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.TryFitPurityPloidy(summaries, null!, out _));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.EvaluatePurityPloidy(summaries, null!, 0.5, 2.0));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.FitPurityPloidyFromAspcf(seg, (OncologyAnalyzer.AscatSexModel)null!));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.TryFitPurityPloidyFromAspcf(seg, null!, out _));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.EvaluatePurityPloidyFromAspcf(seg, null!, 0.5, 2.0));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.FitPurityPloidy(null!, Male));
        });
    }

    #endregion
}
