// ONCO-ASCAT-001 — ASCAT joint multi-sample allele-specific segmentation, ascat.asmultipcf (B24 F53)
// Evidence: docs/Evidence/ONCO-ASCAT-001-Evidence.md (§ "Multi-sample ascat.asmultipcf (F53)")
// TestSpec: tests/TestSpecs/ONCO-ASCAT-001.md (M-AMPCF-*, S-AMPCF-*, C-AMPCF-*)
// Source:  VanLoo-lab/ascat master, ASCAT/R/ascat.asmultipcf.R (ascat.asmultipcf, ASmultiPCFcompact, compactASMulti,
//          runFastASMultiPCF, expandMulti, mirrorBafMatrix, madWinsMatrixWithNA, getMadwithNA) + ascat.aspcf.R (madWins,
//          medianFilter).
//
// Every expected value below is the output of the ORIGINAL R code (R 4.3.3, sourced ascat.aspcf.R + ascat.asmultipcf.R):
// ascat.asmultipcf(ASCATobj, ascat.gg = list(germlinegenotypes = !het), penalty, out.dir = NA, wsample, selectAlg, refine)
// on the deterministic cohorts generated by Simulate() — the MINSTD generator is reproduced verbatim in R, so both sides see
// bit-identical input. Segments = runs of equal Tumor_LogR_segmented within a chromosome; BAF = 1 − Tumor_BAF_segmented of
// the first heterozygous probe of the segment (NaN = none).

namespace Seqeron.Genomics.Tests.Unit.Oncology;

[TestFixture]
public class OncologyAnalyzer_AscatAsMultiPcf_Tests
{
    // ---- Deterministic multi-sample cohort generator (identical R implementation in the Evidence file) ----

    public sealed record Block(string Chrom, int N, bool ForceHom, double[] R, double[] B);

    public sealed record Cohort(int Samples, int Seed, double PHom, Block[] Blocks);

    public readonly record struct Seg(string Chr, long Start, long End, double LogR, double Baf, int N, int NHet);

    private static Block Bl(string chrom, int n, bool hom, double[] r, double[] b) => new(chrom, n, hom, r, b);

    // C1 (2 samples): S2-only breakpoint at probe 400, a forced 100-probe homozygous stretch, an S1-only breakpoint after
    // it (probe 900), a 128-probe chr2 (floor(128 + 0.01 − 0.01) = 127), a 4-probe chr3 (< 6 ⇒ no PCF) and a homozygous-only
    // chr4 with an S1-only deletion that the refinement removes (R quirk: NaN bestCost[1] for a zero-BAF-weight first block).
    private static readonly Cohort C1 = new(2, 101, 0.3, new[]
    {
        Bl("1", 400, false, new[] { 0.0, 0.0 }, new[] { 0.5, 0.5 }), Bl("1", 400, false, new[] { 0.0, 0.9 }, new[] { 0.5, 0.75 }),
        Bl("1", 100, true, new[] { 0.0, 0.9 }, new[] { 0.5, 0.75 }), Bl("1", 300, false, new[] { -1.0, 0.9 }, new[] { 0.85, 0.75 }),
        Bl("2", 128, false, new[] { 0.5, -0.5 }, new[] { 0.7, 0.5 }), Bl("3", 4, false, new[] { 0.3, 0.3 }, new[] { 0.6, 0.6 }),
        Bl("4", 150, true, new[] { 0.0, 0.0 }, new[] { 0.5, 0.5 }), Bl("4", 150, true, new[] { -1.5, 0.0 }, new[] { 0.5, 0.5 }),
    });

    // C2 (3 samples): a breakpoint shared by S1/S2 but not S3, a shared one, a 32-probe chr2, a 5-probe chr3 and an S3-only
    // breakpoint inside a forced 60-probe homozygous stretch on chr4.
    private static readonly Cohort C2 = new(3, 202, 0.25, new[]
    {
        Bl("1", 500, false, new[] { 0.0, 0.0, 0.0 }, new[] { 0.5, 0.5, 0.5 }),
        Bl("1", 300, false, new[] { 1.0, 1.0, 0.0 }, new[] { 0.8, 0.8, 0.5 }),
        Bl("1", 300, false, new[] { -0.8, -0.8, -0.8 }, new[] { 0.9, 0.9, 0.9 }),
        Bl("2", 32, false, new[] { 0.2, 0.2, 0.2 }, new[] { 0.6, 0.6, 0.6 }),
        Bl("3", 5, false, new[] { 0.4, -0.4, 0.0 }, new[] { 0.7, 0.8, 0.5 }),
        Bl("4", 120, false, new[] { 0.0, 0.0, 0.0 }, new[] { 0.5, 0.5, 0.5 }),
        Bl("4", 30, true, new[] { 0.0, 0.0, 0.0 }, new[] { 0.5, 0.5, 0.5 }),
        Bl("4", 30, true, new[] { 0.0, 0.0, -1.2 }, new[] { 0.5, 0.5, 0.95 }),
        Bl("4", 120, false, new[] { 0.0, 0.0, -1.2 }, new[] { 0.5, 0.5, 0.95 }),
    });

    // C3 (4 samples): sample-specific subsets of two joint breakpoints on chr1 and an S4-only deletion confined to a forced
    // 80-probe homozygous stretch on chr2.
    private static readonly Cohort C3 = new(4, 303, 0.35, new[]
    {
        Bl("1", 200, false, new[] { 0.0, 0.0, 0.0, 0.0 }, new[] { 0.5, 0.5, 0.5, 0.5 }),
        Bl("1", 200, false, new[] { 0.8, 0.8, 0.0, 0.0 }, new[] { 0.75, 0.75, 0.5, 0.5 }),
        Bl("1", 200, false, new[] { 0.8, -0.6, -0.6, 0.0 }, new[] { 0.75, 0.85, 0.85, 0.5 }),
        Bl("2", 110, false, new[] { 0.3, 0.3, 0.3, 0.3 }, new[] { 0.6, 0.6, 0.6, 0.6 }),
        Bl("2", 80, true, new[] { 0.3, 0.3, 0.3, -1.5 }, new[] { 0.6, 0.6, 0.6, 0.6 }),
        Bl("2", 110, false, new[] { 0.3, 0.3, 0.3, 0.3 }, new[] { 0.6, 0.6, 0.6, 0.6 }),
    });

    // C4 (2 samples, 6500 probes on one chromosome): exercises runFastASMultiPCF (windows of 5001 probes).
    private static readonly Cohort C4 = new(2, 404, 0.3, new[]
    {
        Bl("1", 2500, false, new[] { 0.0, 0.0 }, new[] { 0.5, 0.5 }), Bl("1", 2500, false, new[] { 0.6, 0.0 }, new[] { 0.7, 0.5 }),
        Bl("1", 1500, false, new[] { -0.7, -0.7 }, new[] { 0.85, 0.85 }),
    });

    // C5 (2 samples): an S2-only logR step of 0.4 over 300 + 300 probes, below the joint penalty unless S2 is up-weighted.
    private static readonly Cohort C5 = new(2, 505, 0.3, new[]
    {
        Bl("1", 300, false, new[] { 0.0, 0.0 }, new[] { 0.5, 0.5 }), Bl("1", 300, false, new[] { 0.0, 0.4 }, new[] { 0.5, 0.5 }),
        Bl("2", 200, false, new[] { 0.5, 0.5 }, new[] { 0.7, 0.7 }),
    });

    /// <summary>
    /// Per probe: one MINSTD draw for the shared germline genotype (homozygous when forced or u &lt; pHom), then per sample 9
    /// draws (4 × logR noise, BAF orientation, 4 × BAF noise): logR = r + 0.2·(Σ4u − 2); heterozygous BAF = b (or 1 − b) +
    /// 0.1·(Σ4u − 2) clamped to [0, 1]; homozygous BAF = 0 or 1. Position = 1000·index (1-based).
    /// </summary>
    internal static (List<IReadOnlyList<OncologyAnalyzer.AlleleSpecificLocus>> Samples, List<bool> Het) Simulate(Cohort c)
    {
        double s = c.Seed;
        double U()
        {
            s = (s * 48271.0) % 2147483647.0;
            return s / 2147483647.0;
        }

        var samples = new List<List<OncologyAnalyzer.AlleleSpecificLocus>>();
        for (int k = 0; k < c.Samples; k++)
        {
            samples.Add(new List<OncologyAnalyzer.AlleleSpecificLocus>());
        }

        var het = new List<bool>();
        foreach (Block block in c.Blocks)
        {
            for (int p = 0; p < block.N; p++)
            {
                bool hom = U() < c.PHom || block.ForceHom;
                long position = (het.Count + 1) * 1000L;
                for (int k = 0; k < c.Samples; k++)
                {
                    double a1 = U(), a2 = U(), a3 = U(), a4 = U(), us = U(), c1 = U(), c2 = U(), c3 = U(), c4 = U();
                    double x = block.R[k] + 0.2 * ((((a1 + a2) + a3) + a4) - 2.0);
                    double y;
                    if (hom)
                    {
                        y = us < 0.5 ? 0.0 : 1.0;
                    }
                    else
                    {
                        double b0 = us < 0.5 ? 1.0 - block.B[k] : block.B[k];
                        y = Math.Min(1.0, Math.Max(0.0, b0 + 0.1 * ((((c1 + c2) + c3) + c4) - 2.0)));
                    }

                    samples[k].Add(new OncologyAnalyzer.AlleleSpecificLocus(block.Chrom, position, x, y));
                }

                het.Add(!hom);
            }
        }

        return (samples.Cast<IReadOnlyList<OncologyAnalyzer.AlleleSpecificLocus>>().ToList(), het);
    }

    private static IReadOnlyList<OncologyAnalyzer.AspcfSegmentation> Run(
        Cohort c, double penalty = 70.0, OncologyAnalyzer.AsMultiPcfOptions? options = null)
    {
        var (samples, het) = Simulate(c);
        return OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(samples, het, penalty, options);
    }

    // ---- R reference segments (ascat.asmultipcf, R 4.3.3) ----

    private static readonly Seg[][] C1Expected =
    {
        new Seg[]
        {
            new("1", 1000, 900000, -0.0035079782944365005, 0.5, 900, 553),
            new("1", 901000, 1200000, -1.0084784589495874, 0.85304683089890254, 300, 205),
            new("2", 1201000, 1328000, 0.50814733313979688, 0.69246685861715029, 128, 96),
            new("3", 1329000, 1332000, 0.24486127923934781, 0.65009589176629479, 4, 4),
            new("4", 1333000, 1632000, -0.7425429726108953, double.NaN, 300, 0),
        },
        new Seg[]
        {
            new("1", 1000, 400000, -0.0041329180112261851, 0.5, 400, 282),
            new("1", 401000, 1200000, 0.90336865831300095, 0.74913854753480213, 800, 476),
            new("2", 1201000, 1328000, -0.49056492982851452, 0.5, 128, 96),
            new("3", 1329000, 1332000, 0.19977037154593053, 0.60420341140320677, 4, 4),
            new("4", 1333000, 1632000, 0.0036442948913407965, double.NaN, 300, 0),
        },
    };

    private static readonly Seg[][] C1nrExpected =
    {
        new Seg[]
        {
            new("1", 1000, 400000, -0.00010239578625298828, 0.5, 400, 282),
            new("1", 401000, 900000, -0.0062324443009833105, 0.5, 500, 271),
            new("1", 901000, 1200000, -1.0084784589495874, 0.85304683089890254, 300, 205),
            new("2", 1201000, 1328000, 0.50814733313979688, 0.69246685861715029, 128, 96),
            new("3", 1329000, 1332000, 0.24486127923934781, 0.65009589176629479, 4, 4),
            new("4", 1333000, 1482000, -0.0022084940452478598, double.NaN, 150, 0),
            new("4", 1483000, 1632000, -1.4828774511765428, double.NaN, 150, 0),
        },
        new Seg[]
        {
            new("1", 1000, 400000, -0.0041329180112261851, 0.5, 400, 282),
            new("1", 401000, 900000, 0.90326602607689144, 0.75241978728249526, 500, 271),
            new("1", 901000, 1200000, 0.90353971203984995, 0.74480090864882742, 300, 205),
            new("2", 1201000, 1328000, -0.49056492982851452, 0.5, 128, 96),
            new("3", 1329000, 1332000, 0.19977037154593053, 0.60420341140320677, 4, 4),
            new("4", 1333000, 1482000, 0.00023363734792622071, double.NaN, 150, 0),
            new("4", 1483000, 1632000, 0.0070549524347553721, double.NaN, 150, 0),
        },
    };

    private static readonly Seg[][] C2Expected =
    {
        new Seg[]
        {
            new("1", 1000, 500000, 0.0037425933650427463, 0.5, 500, 366),
            new("1", 501000, 800000, 1.001968491793285, 0.79264022524132671, 300, 223),
            new("1", 801000, 1100000, -0.80428976437525046, 0.90314622314139936, 300, 224),
            new("2", 1101000, 1132000, 0.22471087799335873, 0.60982327795313218, 32, 27),
            new("3", 1133000, 1137000, 0.40407078881006259, 0.68139044493501555, 5, 5),
            new("4", 1138000, 1437000, 0.0074059859002347343, 0.5, 300, 171),
        },
        new Seg[]
        {
            new("1", 1000, 500000, 0.0057280394344255536, 0.5, 500, 366),
            new("1", 501000, 800000, 0.99516479153892246, 0.79606093540056111, 300, 223),
            new("1", 801000, 1100000, -0.79845895331808947, 0.90417390372062412, 300, 224),
            new("2", 1101000, 1132000, 0.18172511291654089, 0.60998114681301652, 32, 27),
            new("3", 1133000, 1137000, -0.37596693509070528, 0.86535280573431073, 5, 5),
            new("4", 1138000, 1437000, -0.002327148230898727, 0.5, 300, 171),
        },
        new Seg[]
        {
            new("1", 1000, 800000, -0.0093757128442524523, 0.5, 800, 589),
            new("1", 801000, 1100000, -0.7971835536276225, 0.89875231728410665, 300, 224),
            new("2", 1101000, 1132000, 0.18565117050225435, 0.5, 32, 27),
            new("3", 1133000, 1137000, -0.0082730656155725214, 0.5, 5, 5),
            new("4", 1138000, 1287000, -0.012775391387182937, 0.5, 150, 89),
            new("4", 1288000, 1437000, -1.196190509667088, 0.93537601136955018, 150, 82),
        },
    };

    private static readonly Seg[][] C3Expected =
    {
        new Seg[]
        {
            new("1", 1000, 200000, -0.0047087978896260254, 0.5, 200, 132),
            new("1", 201000, 600000, 0.79662602974037922, 0.75180379660286378, 400, 251),
            new("2", 601000, 900000, 0.29650479308042588, 0.59790587347366653, 300, 139),
        },
        new Seg[]
        {
            new("1", 1000, 200000, -0.0070917407786900821, 0.5, 200, 132),
            new("1", 201000, 400000, 0.80210242751385208, 0.74793695372381774, 200, 129),
            new("1", 401000, 600000, -0.58192585775625227, 0.84510008427923078, 200, 122),
            new("2", 601000, 900000, 0.30691734452246872, 0.60482673499046735, 300, 139),
        },
        new Seg[]
        {
            new("1", 1000, 400000, 0.0027213252157537861, 0.5, 400, 261),
            new("1", 401000, 600000, -0.59793919000585527, 0.84924140577939478, 200, 122),
            new("2", 601000, 900000, 0.29911427389882239, 0.5, 300, 139),
        },
        new Seg[]
        {
            new("1", 1000, 600000, 0.0012561635084401333, 0.5, 600, 383),
            new("2", 601000, 710000, 0.28353982637801201, 0.5, 110, 71),
            new("2", 711000, 790000, -1.4862779954524143, double.NaN, 80, 0),
            new("2", 791000, 900000, 0.29939998304612764, 0.5, 110, 68),
        },
    };

    private static readonly Seg[][] C3nrExpected =
    {
        new Seg[]
        {
            new("1", 1000, 200000, -0.0047087978896260254, 0.5, 200, 132),
            new("1", 201000, 400000, 0.79451167820231605, 0.75906517642481131, 200, 129),
            new("1", 401000, 600000, 0.79874038127844249, 0.74412578023375542, 200, 122),
            new("2", 601000, 710000, 0.29232517725176671, 0.5889222616496349, 110, 71),
            new("2", 711000, 790000, 0.29397722469944376, double.NaN, 80, 0),
            new("2", 791000, 900000, 0.30252264045889021, 0.6072858211134643, 110, 68),
        },
        new Seg[]
        {
            new("1", 1000, 200000, -0.0070917407786900821, 0.5, 200, 132),
            new("1", 201000, 400000, 0.80210242751385208, 0.74793695372381774, 200, 129),
            new("1", 401000, 600000, -0.58192585775625227, 0.84510008427923078, 200, 122),
            new("2", 601000, 710000, 0.30238163381587196, 0.60580275634862468, 110, 71),
            new("2", 711000, 790000, 0.31742243130687736, double.NaN, 80, 0),
            new("2", 791000, 900000, 0.30381299211313195, 0.60380765386650903, 110, 68),
        },
        new Seg[]
        {
            new("1", 1000, 200000, -0.00067039745332225797, 0.5, 200, 132),
            new("1", 201000, 400000, 0.00611304788482983, 0.5, 200, 129),
            new("1", 401000, 600000, -0.59793919000585527, 0.84924140577939478, 200, 122),
            new("2", 601000, 710000, 0.29891322458958952, 0.5, 110, 71),
            new("2", 711000, 790000, 0.29822470231364701, double.NaN, 80, 0),
            new("2", 791000, 900000, 0.29996228436091005, 0.5, 110, 68),
        },
        new Seg[]
        {
            new("1", 1000, 200000, -0.007826041947969254, 0.5, 200, 132),
            new("1", 201000, 400000, 0.010220623001093335, 0.5, 200, 129),
            new("1", 401000, 600000, 0.0013739094721963196, 0.5, 200, 122),
            new("2", 601000, 710000, 0.28353982637801201, 0.5, 110, 71),
            new("2", 711000, 790000, -1.4862779954524143, double.NaN, 80, 0),
            new("2", 791000, 900000, 0.29939998304612764, 0.5, 110, 68),
        },
    };

    private static readonly Seg[][] C5Expected =
    {
        new Seg[]
        {
            new("1", 1000, 600000, -0.0047449430058453916, 0.5, 600, 421),
            new("2", 601000, 800000, 0.49299772765207928, 0.7010805669414939, 200, 147),
        },
        new Seg[]
        {
            new("1", 1000, 600000, 0.20267949105008173, 0.5, 600, 421),
            new("2", 601000, 800000, 0.50260665065264643, 0.6981619651176878, 200, 147),
        },
    };

    private static readonly Seg[][] C5wExpected =
    {
        new Seg[]
        {
            new("1", 1000, 600000, -0.0047449430058453916, 0.5, 600, 421),
            new("2", 601000, 800000, 0.49299772765207928, 0.7010805669414939, 200, 147),
        },
        new Seg[]
        {
            new("1", 1000, 300000, 0.0061123649639911138, 0.5, 300, 216),
            new("1", 301000, 600000, 0.39924661713617232, 0.5, 300, 205),
            new("2", 601000, 800000, 0.50260665065264643, 0.6981619651176878, 200, 147),
        },
    };

    private static readonly Seg[][] C4Expected =
    {
        new Seg[]
        {
            new("1", 1000, 2500000, -0.002090602734466364, 0.5, 2500, 1773),
            new("1", 2501000, 5000000, 0.60023476820319643, 0.70090115242445417, 2500, 1735),
            new("1", 5001000, 6500000, -0.6981083370367569, 0.84726898447979471, 1500, 1066),
        },
        new Seg[]
        {
            new("1", 1000, 5000000, 0.0027533982463150276, 0.5, 5000, 3508),
            new("1", 5001000, 6500000, -0.69936202158314575, 0.85006924339295897, 1500, 1066),
        },
    };

    private static readonly Seg[][] C4fExpected =
    {
        new Seg[]
        {
            new("1", 1000, 2501000, -0.001834272311738148, 0.5, 2501, 1774),
            new("1", 2502000, 5000000, 0.60021925919307018, 0.70092710756023235, 2499, 1734),
            new("1", 5001000, 6500000, -0.6981083370367569, 0.84726898447979471, 1500, 1066),
        },
        new Seg[]
        {
            new("1", 1000, 5000000, 0.0027533982463150276, 0.5, 5000, 3508),
            new("1", 5001000, 6500000, -0.69936202158314575, 0.85006924339295897, 1500, 1066),
        },
    };

    private static OncologyAnalyzer.AsMultiPcfOptions Opt(
        double[]? weights = null, bool refine = true, OncologyAnalyzer.AsMultiPcfAlgorithm algorithm = OncologyAnalyzer.AsMultiPcfAlgorithm.Exact) =>
        new() { SampleWeights = weights, Refine = refine, Algorithm = algorithm };

    private static IEnumerable<TestCaseData> ReferenceRuns()
    {
        yield return new TestCaseData(C1, 70.0, null, C1Expected).SetName("AsMultiPcf_C1_TwoSamples_PrivateBreakpoints_MatchesAscat");
        yield return new TestCaseData(C1, 70.0, Opt(refine: false), C1nrExpected).SetName("AsMultiPcf_C1_NoRefine_CommonBreakpoints_MatchesAscat");
        yield return new TestCaseData(C1, 70.0, Opt(new[] { 1.0, 0.5, 2.0, 1.0 }), C1Expected).SetName("AsMultiPcf_C1_PerTrackWeights_MatchesAscat");
        yield return new TestCaseData(C2, 70.0, null, C2Expected).SetName("AsMultiPcf_C2_ThreeSamples_MatchesAscat");
        yield return new TestCaseData(C3, 70.0, null, C3Expected).SetName("AsMultiPcf_C3_FourSamples_HomozygousStretch_MatchesAscat");
        yield return new TestCaseData(C3, 70.0, Opt(refine: false), C3nrExpected).SetName("AsMultiPcf_C3_NoRefine_MatchesAscat");
        yield return new TestCaseData(C3, 70.0, Opt(new[] { 1.0, 2.0, 0.5, 1.0 }), C3Expected).SetName("AsMultiPcf_C3_SampleWeights_MatchesAscat");
        yield return new TestCaseData(C3, 25.0, null, C3Expected).SetName("AsMultiPcf_C3_Penalty25_MatchesAscat");
        yield return new TestCaseData(C3, 0.001, null, C3Expected).SetName("AsMultiPcf_C3_Penalty0001_ClimbsLadderTo25_MatchesAscat");
        yield return new TestCaseData(C5, 70.0, null, C5Expected).SetName("AsMultiPcf_C5_WeakPrivateStep_NotCalled_MatchesAscat");
        yield return new TestCaseData(C5, 70.0, Opt(new[] { 1.0, 4.0 }), C5wExpected).SetName("AsMultiPcf_C5_UpWeightedSample_StepCalled_MatchesAscat");
        yield return new TestCaseData(C4, 70.0, null, C4Expected).SetName("AsMultiPcf_C4_6500Probes_Exact_MatchesAscat");
        yield return new TestCaseData(C4, 70.0, Opt(algorithm: OncologyAnalyzer.AsMultiPcfAlgorithm.Fast), C4fExpected).SetName("AsMultiPcf_C4_6500Probes_Fast_MatchesAscat");
        yield return new TestCaseData(C4, 70.0, Opt(new[] { 1.0, 3.0 }, algorithm: OncologyAnalyzer.AsMultiPcfAlgorithm.Fast), C4fExpected).SetName("AsMultiPcf_C4_Fast_Weighted_MatchesAscat");
    }

    // M-AMPCF-1..14 — breakpoints (segment extents, probe and heterozygous counts) identical to R; per-sample segment logR
    // and BAF bit-identical to R (R long-double mean(), B24 F66; previously ≤ 7.8e-16).
    [TestCaseSource(nameof(ReferenceRuns))]
    public void SegmentAlleleSpecificAsMultiPcf_MatchesAscatAsMultiPcf(
        Cohort cohort, double penalty, OncologyAnalyzer.AsMultiPcfOptions? options, Seg[][] expected)
    {
        var result = Run(cohort, penalty, options);

        Assert.That(result, Has.Count.EqualTo(expected.Length), "One segmentation per sample.");
        Assert.Multiple(() =>
        {
            for (int s = 0; s < expected.Length; s++)
            {
                var actual = result[s].Segments;
                Assert.That(actual.Select(a => (a.Chromosome, a.Start, a.End, a.LocusCount, a.HeterozygousLocusCount)),
                    Is.EqualTo(expected[s].Select(e => (e.Chr, e.Start, e.End, e.N, e.NHet))), $"Sample {s + 1} breakpoints.");
                if (actual.Count != expected[s].Length)
                {
                    continue;
                }

                for (int i = 0; i < expected[s].Length; i++)
                {
                    Assert.That(actual[i].MeanLogR, Is.EqualTo(expected[s][i].LogR), $"Sample {s + 1} segment {i + 1} logR.");
                    if (double.IsNaN(expected[s][i].Baf))
                    {
                        Assert.That(actual[i].HasBaf, Is.False, $"Sample {s + 1} segment {i + 1}: no heterozygous probe.");
                    }
                    else
                    {
                        Assert.That(actual[i].MeanBAF, Is.EqualTo(expected[s][i].Baf), $"Sample {s + 1} segment {i + 1} BAF.");
                    }
                }
            }
        });
    }

    // S-AMPCF-1 — refinement keeps a breakpoint only in the samples that support it: C1 S1 has no break at probe 400 and S2
    // none at probe 900, while without refinement both carry the joint breakpoints.
    [Test]
    public void SegmentAlleleSpecificAsMultiPcf_Refine_RemovesUnsupportedBreakpointsPerSample()
    {
        var refined = Run(C1);
        var joint = Run(C1, options: Opt(refine: false));

        static long[] Ends(OncologyAnalyzer.AspcfSegmentation s) => s.Segments.Where(x => x.Chromosome == "1").Select(x => x.End).ToArray();
        Assert.Multiple(() =>
        {
            Assert.That(Ends(joint[0]), Is.EqualTo(new long[] { 400000, 900000, 1200000 }));
            Assert.That(Ends(joint[1]), Is.EqualTo(new long[] { 400000, 900000, 1200000 }));
            Assert.That(Ends(refined[0]), Is.EqualTo(new long[] { 900000, 1200000 }), "S1: no change at probe 400.");
            Assert.That(Ends(refined[1]), Is.EqualTo(new long[] { 400000, 1200000 }), "S2: no change at probe 900.");
        });
    }

    // S-AMPCF-2 — R quirk kept: on a chromosome without heterozygous probes the refinement's first compact block has BAF
    // weight 0, so bestAver = 0/0 = NaN, bestCost[1] = NaN and which.min can never keep the only joint breakpoint — the
    // S1-only deletion on homozygous-only chr4 (C1) is found jointly but merged away by refine = TRUE, exactly as in R.
    [Test]
    public void SegmentAlleleSpecificAsMultiPcf_HomozygousOnlyChromosome_RefineMergesAsInR()
    {
        var refined = Run(C1);
        var joint = Run(C1, options: Opt(refine: false));

        Assert.Multiple(() =>
        {
            Assert.That(refined[0].Segments.Count(s => s.Chromosome == "4"), Is.EqualTo(1));
            Assert.That(joint[0].Segments.Where(s => s.Chromosome == "4").Select(s => s.LocusCount), Is.EqualTo(new[] { 150, 150 }));
            Assert.That(joint[0].Segments[^1].MeanLogR, Is.EqualTo(-1.4828774511765428));
        });
    }

    // S-AMPCF-3 — output shape: one germline for all samples; BAF only at heterozygous probes; segments tile the probes;
    // null genotypes = every probe heterozygous.
    [Test]
    public void SegmentAlleleSpecificAsMultiPcf_OutputShapeAndDefaultGenotypes()
    {
        var (samples, het) = Simulate(C2);
        var result = OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(samples, het);
        var allHet = OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(samples, samples[0].Select(_ => true).ToList());
        var defaulted = OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(samples);

        Assert.Multiple(() =>
        {
            foreach (var seg in result)
            {
                Assert.That(seg.Segments.Sum(s => s.LocusCount), Is.EqualTo(1437));
                Assert.That(seg.GermlineHeterozygous, Is.EqualTo(het));
                for (int i = 0; i < het.Count; i++)
                {
                    Assert.That(double.IsNaN(seg.SegmentedBaf[i]), Is.EqualTo(!het[i]), $"Probe {i + 1}: BAF only where heterozygous.");
                }
            }

            for (int s = 0; s < 3; s++)
            {
                Assert.That(defaulted[s].SegmentedLogR, Is.EqualTo(allHet[s].SegmentedLogR), $"Sample {s + 1} logR.");
                Assert.That(defaulted[s].SegmentedBaf, Is.EqualTo(allHet[s].SegmentedBaf), $"Sample {s + 1} BAF.");
            }
        });
    }

    // C-AMPCF-1 — R fails on one sample and on a single-probe chromosome (Tumor_LogR[chr[[k]], ] drops to a vector:
    // "incorrect number of subscripts on matrix"); both are rejected, as are inconsistent inputs.
    [Test]
    public void SegmentAlleleSpecificAsMultiPcf_InvalidArguments_Throw()
    {
        var (samples, het) = Simulate(C5);
        var twoSamples = samples;
        var shifted = samples[1].Select(l => l with { Position = l.Position + 1 }).ToList();
        var singleProbeChr = samples.Select(s => (IReadOnlyList<OncologyAnalyzer.AlleleSpecificLocus>)s
            .Append(new OncologyAnalyzer.AlleleSpecificLocus("3", 999_000_000, 0.0, 0.5)).ToList()).ToList();

        Assert.Multiple(() =>
        {
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(null!));
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(new[] { samples[0] }, het),
                "One sample: R fails; use SegmentAlleleSpecificAspcf.");
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(singleProbeChr),
                "Single-probe chromosome: R fails.");
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(new[] { samples[0], shifted }, het),
                "Different probe sets.");
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(twoSamples, het.Take(10).ToList()));
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(
                twoSamples, het, 70.0, Opt(new[] { 1.0, 1.0, 1.0 })), "wsample length must be S or 2S.");
            Assert.Throws<ArgumentOutOfRangeException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(
                twoSamples, het, 70.0, Opt(new[] { 1.0, -1.0 })));
            Assert.Throws<ArgumentOutOfRangeException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(twoSamples, het, 0.0));
            Assert.Throws<ArgumentOutOfRangeException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(twoSamples, het, double.NaN));
            var badBaf = samples[1].Select((l, i) => i == 0 ? l with { BAF = 1.5 } : l).ToList();
            var allHet = het.Select(_ => true).ToList();
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(new[] { samples[0], badBaf }, allHet));
            var badLogR = samples[1].Select((l, i) => i == 0 ? l with { LogR = double.PositiveInfinity } : l).ToList();
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAsMultiPcf(new[] { samples[0], badLogR }, het),
                "Infinite logR (NaN = R NA is accepted since B24 F59).");
        });
    }
}
