// ONCO-ASCAT-001 — ASCAT with germline-homozygous probes (B24 F36 / F37)
// Evidence: docs/Evidence/ONCO-ASCAT-001-Evidence.md (§ "Germline-homozygous probes (F36/F37)")
// TestSpec: tests/TestSpecs/ONCO-ASCAT-001.md (M-ASPCF-G*, S-ASPCF-G*, C-ASPCF-G*, M-ASCAT-G*, S-ASCAT-G*, C-ASCAT-G*)
// Source:  VanLoo-lab/ascat master, ASCAT/R/ascat.aspcf.R (ascat.aspcf with ascat.gg, predictGermlineHomozygousStretches,
//          exactPcf, fillNA) and ASCAT/R/ascat.runAscat.R (runASCAT, make_segments).
//
// Every expected value below is the output of the ORIGINAL R code (R 4.3.3, sourced ascat.aspcf.R + ascat.runAscat.R,
// plots stubbed): ascat.aspcf(ASCATobj, ascat.gg = list(germlinegenotypes = !het), penalty = 70) followed by
// ascat.runAscat(gamma = 1), on the deterministic genomes generated by Simulate() — the generator is reproduced
// verbatim in R (MINSTD, exact in IEEE doubles), so both sides see bit-identical input.

namespace Seqeron.Genomics.Tests.Unit.Oncology;

[TestFixture]
public class OncologyAnalyzer_AscatGermlineHomozygous_Tests
{
    // ---- Deterministic genome generator (identical R implementation in the Evidence file) ----

    public readonly record struct Block(string Chrom, int N, double R, double B, bool ForceHom);

    public sealed record Genome(int Seed, double PHom, Block[] Blocks);

    // G1: rho 0.7 / psi 2.4 model levels; a 110-probe germline-homozygous stretch on chr1 carrying a 50-probe
    //     homozygous deletion (found only by the homozygous-stretch resegmentation); chr3 has no heterozygous probe.
    private static readonly Genome G1 = new(11, 0.3, new Block[]
    {
        new("1", 150, -0.189, 0.5, false), new("1", 100, 0.2439, 0.6296, false), new("1", 30, 0.2439, 0.6296, true),
        new("1", 50, -1.926, 0.5, true), new("1", 30, 0.2439, 0.6296, true), new("1", 100, 0.2439, 0.6296, false),
        new("2", 150, -0.8105, 0.7692, false), new("2", 150, 0.5765, 0.5, false), new("3", 120, -0.189, 0.85, true),
        new("4", 100, 0.5765, 0.7059, false), new("4", 100, -0.189, 0.5, false),
    });

    // G2: rho 0.55 / psi 2.2; a copy-number breakpoint inside an 80-probe homozygous gap (placed by the
    //     "find best breakpoint" search), a 12-probe chromosome, a homozygous-only chr4 and an X chromosome.
    private static readonly Genome G2 = new(22, 0.25, new Block[]
    {
        new("1", 200, -0.0772, 0.5, false), new("1", 40, -0.0772, 0.5, true), new("1", 40, 0.2733, 0.8235, true),
        new("1", 200, 0.2733, 0.8235, false), new("2", 150, -0.5412, 0.6897, false), new("2", 150, 0.2733, 0.6078, false),
        new("3", 12, 0.555, 0.5, false), new("4", 80, -0.5412, 0.6897, true), new("X", 100, -0.0772, 0.5, false),
        new("X", 30, -0.0772, 0.5, true),
    });

    // G3: rho 0.9 / psi 3.3; a 60-probe focal gain inside a 180-probe homozygous stretch on chr2 and a
    //     homozygous-only chr4.
    private static readonly Genome G3 = new(33, 0.35, new Block[]
    {
        new("1", 150, 0.2615, 0.5, false), new("1", 150, 0.2615, 0.7368, false), new("2", 120, -0.6645, 0.95, false),
        new("2", 60, -0.6645, 0.95, true), new("2", 60, 0.2615, 0.9737, true), new("2", 60, -0.6645, 0.95, true),
        new("2", 100, -0.6645, 0.95, false), new("3", 200, 0.5682, 0.5957, false), new("3", 100, -0.1284, 0.6552, false),
        new("4", 100, -0.1284, 0.9655, true),
    });

    /// <summary>
    /// Per probe: 10 MINSTD draws (genotype, 4 × logR noise, BAF orientation, 4 × BAF noise). Homozygous when forced or
    /// u &lt; pHom; logR = r + 0.2·(Σ4u − 2); heterozygous BAF = b (or 1 − b) + 0.1·(Σ4u − 2) clamped to [0, 1];
    /// homozygous BAF = 0 or 1. Position = 1000·index (1-based).
    /// </summary>
    private static (List<OncologyAnalyzer.AlleleSpecificLocus> Loci, List<bool> Het) Simulate(Genome g)
    {
        double s = g.Seed;
        double U()
        {
            s = (s * 48271.0) % 2147483647.0;
            return s / 2147483647.0;
        }

        var loci = new List<OncologyAnalyzer.AlleleSpecificLocus>();
        var het = new List<bool>();
        foreach (Block block in g.Blocks)
        {
            for (int p = 0; p < block.N; p++)
            {
                double ug = U(), a1 = U(), a2 = U(), a3 = U(), a4 = U(), us = U(), c1 = U(), c2 = U(), c3 = U(), c4 = U();
                bool hom = block.ForceHom || ug < g.PHom;
                double x = block.R + 0.2 * ((((a1 + a2) + a3) + a4) - 2.0);
                double y;
                if (hom)
                {
                    y = us < 0.5 ? 0.0 : 1.0;
                }
                else
                {
                    double b0 = us < 0.5 ? 1.0 - block.B : block.B;
                    y = Math.Min(1.0, Math.Max(0.0, b0 + 0.1 * ((((c1 + c2) + c3) + c4) - 2.0)));
                }

                loci.Add(new OncologyAnalyzer.AlleleSpecificLocus(block.Chrom, (loci.Count + 1) * 1000L, x, y));
                het.Add(!hom);
            }
        }

        return (loci, het);
    }

    private static OncologyAnalyzer.AspcfSegmentation Segment(Genome g)
    {
        var (loci, het) = Simulate(g);
        return OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, het, 70.0);
    }

    // ascat.aspcf → runASCAT logR segments (rle(Tumor_LogR_segmented) ∪ chromosome ends): chromosome, first/last
    // position, segmented logR, mirrored BAF of the first heterozygous probe (1 − Tumor_BAF_segmented; NaN = none),
    // probes, heterozygous probes.
    private static readonly (string Chr, long Start, long End, double LogR, double Baf, int N, int NHet)[] G1Segments =
    {
        ("1", 1000, 150000, -0.19385270614527136, 0.5, 150, 107),
        ("1", 151000, 245000, 0.2405441543168986, 0.6299699648404341, 95, 62),
        ("1", 246000, 280000, 0.21081138990811338, 0.6299699648404341, 35, 4),
        ("1", 281000, 330000, -1.9130208073104829, double.NaN, 50, 0),
        ("1", 331000, 365000, 0.23960437852093222, 0.6299699648404341, 35, 4),
        ("1", 366000, 460000, 0.2311332163909311, 0.6299699648404341, 95, 64),
        ("2", 461000, 610000, -0.79657733976813527, 0.77505063473397717, 150, 111),
        ("2", 611000, 760000, 0.57502905570336726, 0.5, 150, 106),
        ("3", 761000, 880000, -0.20494605301240432, double.NaN, 120, 0),
        ("4", 881000, 980000, 0.57682047059401897, 0.71354613520597998, 100, 69),
        ("4", 981000, 1080000, -0.18645282337695956, 0.5, 100, 81),
    };

    private static readonly (string Chr, long Start, long End, double LogR, double Baf, int N, int NHet)[] G2Segments =
    {
        ("1", 1000, 240000, -0.09355753590715625, 0.5, 240, 140),
        ("1", 241000, 480000, 0.26831592601223347, 0.8228777282217784, 240, 149),
        ("2", 481000, 631000, -0.51724094008631627, 0.68932599622440272, 151, 114),
        ("2", 632000, 780000, 0.27412671315816517, 0.61727785352114861, 149, 108),
        ("3", 781000, 792000, 0.55024300414071259, 0.5493282840258108, 12, 10),
        ("4", 793000, 872000, -0.56556928611219359, double.NaN, 80, 0),
        ("X", 873000, 1002000, -0.090707545593108632, 0.5, 130, 79),
    };

    private static readonly (string Chr, long Start, long End, double LogR, double Baf, int N, int NHet)[] G3Segments =
    {
        ("1", 1000, 148000, 0.25479450774650791, 0.5, 148, 93),
        ("1", 149000, 300000, 0.26247512106003162, 0.73657895755554126, 152, 97),
        ("2", 301000, 480000, -0.64138213949877865, 0.94639238907269108, 180, 80),
        ("2", 481000, 540000, 0.26558251092493651, double.NaN, 60, 0),
        ("2", 541000, 700000, -0.68090084141173901, 0.94639238907269108, 160, 67),
        ("3", 701000, 900000, 0.55418826441307945, 0.5, 200, 120),
        ("3", 901000, 1000000, -0.13290215040636347, 0.65069964961947069, 100, 68),
        ("4", 1001000, 1100000, -0.14432520419504735, double.NaN, 100, 0),
    };

    private static IEnumerable<TestCaseData> ReferenceGenomes()
    {
        yield return new TestCaseData(G1, G1Segments).SetName("AspcfGermline_G1_HomozygousDeletionInStretch_MatchesAscat");
        yield return new TestCaseData(G2, G2Segments).SetName("AspcfGermline_G2_BreakpointInHomozygousGap_MatchesAscat");
        yield return new TestCaseData(G3, G3Segments).SetName("AspcfGermline_G3_FocalGainInHomozygousStretch_MatchesAscat");
    }

    #region SegmentAlleleSpecificAspcf with germline genotypes (F36)

    // M-ASPCF-G1..G3 — the complete ascat.aspcf on mixed heterozygous / homozygous input reproduces R segment for
    // segment (logR levels ≤ 1e-14; R mean() accumulates in long double, so the last bit may differ).
    [TestCaseSource(nameof(ReferenceGenomes))]
    public void SegmentAlleleSpecificAspcf_Germline_MatchesAscatAspcf(
        Genome genome, (string Chr, long Start, long End, double LogR, double Baf, int N, int NHet)[] expected)
    {
        var seg = Segment(genome);

        Assert.That(seg.Segments, Has.Count.EqualTo(expected.Length), "ascat.aspcf → runASCAT logR segment count.");
        Assert.Multiple(() =>
        {
            for (int i = 0; i < expected.Length; i++)
            {
                var s = seg.Segments[i];
                var e = expected[i];
                Assert.That((s.Chromosome, s.Start, s.End, s.LocusCount, s.HeterozygousLocusCount),
                    Is.EqualTo((e.Chr, e.Start, e.End, e.N, e.NHet)), $"Segment {i + 1} extent.");
                Assert.That(s.MeanLogR, Is.EqualTo(e.LogR).Within(1e-14), $"Segment {i + 1} ascat.aspcf logR level.");
                if (double.IsNaN(e.Baf))
                {
                    Assert.That(s.HasBaf, Is.False, $"Segment {i + 1}: no heterozygous probe ⇒ no BAF (ASCAT NA).");
                }
                else
                {
                    Assert.That(s.MeanBAF, Is.EqualTo(e.Baf).Within(1e-15), $"Segment {i + 1} ascat.aspcf BAF.");
                }
            }
        });
    }

    // S-ASPCF-G1 — per-locus outputs: every locus carries its segment's logR level; BAF only at heterozygous loci.
    [Test]
    public void SegmentAlleleSpecificAspcf_Germline_PerLocusTracksAreConsistent()
    {
        var (loci, het) = Simulate(G1);
        var seg = OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, het);

        Assert.Multiple(() =>
        {
            Assert.That(seg.Loci, Has.Count.EqualTo(1080));
            Assert.That(seg.SegmentedLogR, Has.Count.EqualTo(1080));
            Assert.That(seg.Segments.Sum(s => s.LocusCount), Is.EqualTo(1080), "Segments tile all loci.");
            Assert.That(seg.Segments.Sum(s => s.HeterozygousLocusCount), Is.EqualTo(het.Count(h => h)), "608 heterozygous loci.");
            for (int i = 0; i < loci.Count; i++)
            {
                Assert.That(double.IsNaN(seg.SegmentedBaf[i]), Is.EqualTo(!het[i]), $"Locus {i + 1}: BAF only where heterozygous.");
            }

            int k = 0;
            foreach (var s in seg.Segments)
            {
                for (int j = 0; j < s.LocusCount; j++, k++)
                {
                    Assert.That(seg.SegmentedLogR[k], Is.EqualTo(s.MeanLogR), $"Locus {k + 1} carries its segment level.");
                }
            }
        });
    }

    // S-ASPCF-G2 — all heterozygous: the germline-aware overload reproduces the het-only overload bit for bit
    // (logR levels, BAF, extents), so existing callers keep their (R-verified, F13) behaviour.
    [TestCaseSource(nameof(ReferenceGenomes))]
    public void SegmentAlleleSpecificAspcf_AllHeterozygous_EqualsHetOnlyOverload(
        Genome genome, (string Chr, long Start, long End, double LogR, double Baf, int N, int NHet)[] _)
    {
        var (loci, het) = Simulate(genome);
        var hetLoci = loci.Where((_, i) => het[i]).ToList();

        var legacy = OncologyAnalyzer.SegmentAlleleSpecificAspcf(hetLoci, 70.0);
        var germline = OncologyAnalyzer.SegmentAlleleSpecificAspcf(hetLoci, hetLoci.Select(_ => true).ToList(), 70.0);

        Assert.That(germline.Segments, Has.Count.EqualTo(legacy.Count));
        Assert.Multiple(() =>
        {
            for (int i = 0; i < legacy.Count; i++)
            {
                var a = legacy[i];
                var b = germline.Segments[i];
                Assert.That((b.Chromosome, b.Start, b.End, b.LocusCount, b.HeterozygousLocusCount),
                    Is.EqualTo((a.Chromosome, a.Start, a.End, a.LocusCount, a.LocusCount)), $"Segment {i + 1} extent.");
                Assert.That(b.MeanLogR, Is.EqualTo(a.MeanLogR), $"Segment {i + 1} logR bit-identical.");
                Assert.That(b.MeanBAF, Is.EqualTo(a.MeanBAF), $"Segment {i + 1} BAF bit-identical.");
            }
        });
    }

    // S-ASPCF-G3 — dropping the homozygous probes changes the logR segmentation (the homozygous deletion of G1 and
    // the focal gain of G3 vanish), i.e. homozygous probes carry copy-number information ASCAT uses.
    [Test]
    public void SegmentAlleleSpecificAspcf_DroppingHomozygousProbes_LosesTheHomozygousDeletion()
    {
        var (loci, het) = Simulate(G1);
        var hetOnly = OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci.Where((_, i) => het[i]), 70.0);
        var germline = OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, het, 70.0);

        Assert.Multiple(() =>
        {
            Assert.That(hetOnly.Any(s => s.MeanLogR < -1.0), Is.False, "Het-only input cannot see the homozygous deletion.");
            Assert.That(germline.Segments.Single(s => s.MeanLogR < -1.0).Start, Is.EqualTo(281000L),
                "ascat.aspcf resegments the homozygous stretch: deletion at probes 281–330.");
        });
    }

    // C-ASPCF-G1 — invalid arguments.
    [Test]
    public void SegmentAlleleSpecificAspcf_Germline_InvalidArguments_Throw()
    {
        var loci = new List<OncologyAnalyzer.AlleleSpecificLocus> { new("1", 1000, 0.0, 0.5), new("1", 2000, 0.1, double.NaN) };
        var het = new List<bool> { true, false };
        Assert.Multiple(() =>
        {
            Assert.DoesNotThrow(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, het), "Homozygous BAF is ignored (may be NaN).");
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(null!, het));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, (IReadOnlyList<bool>)null!));
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, new List<bool> { true }),
                "One genotype per locus.");
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, new List<bool> { true, true }),
                "A heterozygous locus needs a BAF in [0, 1].");
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(
                new[] { new OncologyAnalyzer.AlleleSpecificLocus("1", 1, double.PositiveInfinity, 0.0) }, new List<bool> { false }),
                "LogR must be finite at every locus.");
            Assert.Throws<ArgumentOutOfRangeException>(() => OncologyAnalyzer.SegmentAlleleSpecificAspcf(loci, het, 0.0));
        });
    }

    #endregion

    #region FitPurityPloidyFromAspcf — runASCAT with homozygous segments (F37)

    // runASCAT (gamma = 1, defaults) on the ascat.aspcf output: purity, psi, ploidy = mean(nA + nB) over ALL probes,
    // goodnessOfFit, and seg_raw (nMajor, nMinor) per logR segment.
    private static IEnumerable<TestCaseData> ReferenceFits()
    {
        yield return new TestCaseData(G1, 0.7, 2.45, 2.4722222222222223, 99.937918942624279,
                new[] { (1, 1), (2, 1), (2, 1), (0, 0), (2, 1), (2, 1), (1, 0), (2, 2), (2, 0), (3, 1), (1, 1) })
            .SetName("RunAscatGermline_G1_MatchesRunAscat");
        yield return new TestCaseData(G2, 0.53, 2.35, 2.1816367265469063, 99.634551649302338,
                new[] { (1, 1), (3, 0), (1, 0), (2, 1), (2, 2), (1, 0), (1, 1) })
            .SetName("RunAscatGermline_G2_MatchesRunAscat");
        yield return new TestCaseData(G3, 0.92, 3.15, 3.3818181818181818, 98.658353206884712,
                new[] { (2, 2), (3, 1), (2, 0), (4, 0), (2, 0), (3, 2), (2, 1), (3, 0) })
            .SetName("RunAscatGermline_G3_MatchesRunAscat");
    }

    // M-ASCAT-G1..G3 — ascat.aspcf → runASCAT end to end on genomes with homozygous segments.
    [TestCaseSource(nameof(ReferenceFits))]
    public void FitPurityPloidyFromAspcf_MatchesRunAscat(
        Genome genome, double rho, double psi, double ploidy, double goodnessOfFit, (int Major, int Minor)[] segRaw)
    {
        var fit = OncologyAnalyzer.FitPurityPloidyFromAspcf(Segment(genome));

        Assert.Multiple(() =>
        {
            Assert.That(fit.Purity, Is.EqualTo(rho).Within(1e-12), "runASCAT purity.");
            Assert.That(fit.Psi, Is.EqualTo(psi).Within(1e-12), "runASCAT psi.");
            Assert.That(fit.Ploidy, Is.EqualTo(ploidy).Within(1e-14), "ASCAT ploidy = mean(nA + nB) over all probes.");
            Assert.That(fit.GoodnessOfFit, Is.EqualTo(goodnessOfFit).Within(1e-9), "runASCAT goodnessOfFit.");
            Assert.That(fit.IsNonAberrant, Is.False, "runASCAT nonaberrant = FALSE.");
            Assert.That(fit.Segments.Select(s => (s.MajorCopyNumber, s.MinorCopyNumber)), Is.EqualTo(segRaw),
                "seg_raw nMajor / nMinor per logR segment.");
        });
    }

    // S-ASCAT-G1 — a segment without heterozygous probes (BAF NA ⇒ bafke = 0): the whole total copy number is on the
    // major allele (R seg_raw: G1 chr3 2:0 with nAraw 2.01204 / nBraw 0, the homozygous deletion 0:0; G3 4:0, 3:0).
    [Test]
    public void FitPurityPloidyFromAspcf_HomozygousOnlySegments_CarryTotalOnMajorAllele()
    {
        var seg = Segment(G1);
        var fit = OncologyAnalyzer.FitPurityPloidyFromAspcf(seg);

        Assert.Multiple(() =>
        {
            for (int i = 0; i < seg.Segments.Count; i++)
            {
                if (!seg.Segments[i].HasBaf)
                {
                    Assert.That(fit.Segments[i].MinorCopyNumber, Is.Zero, $"Segment {i + 1}: no BAF ⇒ nB = 0 (ASCAT bafke = 0).");
                }
            }

            var chr3 = fit.Segments.Single(s => s.Chromosome == "3");
            Assert.That((chr3.MajorCopyNumber, chr3.MinorCopyNumber), Is.EqualTo((2, 0)), "Homozygous-only chr3: total 2 on nA.");
        });
    }

    // S-ASCAT-G2 — Ploidy averages over all probes (ASCAT ascat.runAscat ploidy = mean(nA + nB)); the heterozygous-probe
    // mean is R's mean over het probes: 2.6134868421052633 (G1), 2.2716666666666665 (G2), 3.539047619047619 (G3).
    [TestCase(0, 2.6134868421052633)]
    [TestCase(1, 2.2716666666666665)]
    [TestCase(2, 3.539047619047619)]
    public void FitPurityPloidyFromAspcf_PloidyAveragesAllProbes_NotHeterozygousOnly(int genomeIndex, double hetMean)
    {
        var genome = new[] { G1, G2, G3 }[genomeIndex];
        var seg = Segment(genome);
        var fit = OncologyAnalyzer.FitPurityPloidyFromAspcf(seg);

        double hetWeighted = seg.Segments.Zip(fit.Segments)
            .Sum(p => (double)(p.Second.MajorCopyNumber + p.Second.MinorCopyNumber) * p.First.HeterozygousLocusCount)
            / seg.Segments.Sum(s => s.HeterozygousLocusCount);
        double allWeighted = OncologyAnalyzer.EstimatePloidy(fit.Segments, seg.Segments.Select(s => s.LocusCount));

        Assert.Multiple(() =>
        {
            Assert.That(hetWeighted, Is.EqualTo(hetMean).Within(1e-14), "R mean(nA + nB) over heterozygous probes.");
            Assert.That(fit.Ploidy, Is.EqualTo(allWeighted), "Ploidy = all-probe (LocusCount) weighted mean.");
            Assert.That(fit.Ploidy, Is.Not.EqualTo(hetWeighted).Within(1e-6), "All-probe ploidy differs from the het-only mean.");
        });
    }

    // S-ASCAT-G3 — rho_manual / psi_manual at the fitted optimum reproduces the fit (GoF, segments, ploidy).
    [Test]
    public void EvaluatePurityPloidyFromAspcf_AtOptimum_ReproducesFit()
    {
        var seg = Segment(G3);
        var fit = OncologyAnalyzer.FitPurityPloidyFromAspcf(seg);
        var manual = OncologyAnalyzer.EvaluatePurityPloidyFromAspcf(seg, fit.Purity, fit.Psi);

        Assert.Multiple(() =>
        {
            Assert.That(manual.GoodnessOfFit, Is.EqualTo(fit.GoodnessOfFit), "Same distance ⇒ same GoF.");
            Assert.That(manual.Ploidy, Is.EqualTo(fit.Ploidy));
            Assert.That(manual.Segments, Is.EqualTo(fit.Segments));
            Assert.That(OncologyAnalyzer.TryFitPurityPloidyFromAspcf(seg, out var tried), Is.True);
            Assert.That((tried.Purity, tried.Psi), Is.EqualTo((fit.Purity, fit.Psi)));
        });
    }

    // S-ASCAT-G4 — all heterozygous: the germline-aware fit equals FitPurityPloidy on the het-only summaries
    // (make_segments over het probes = one fitting segment per summary here; ploidy over all = over het probes).
    [TestCaseSource(nameof(ReferenceGenomes))]
    public void FitPurityPloidyFromAspcf_AllHeterozygous_EqualsSummaryFit(
        Genome genome, (string Chr, long Start, long End, double LogR, double Baf, int N, int NHet)[] _)
    {
        var (loci, het) = Simulate(genome);
        var hetLoci = loci.Where((_, i) => het[i]).ToList();
        var legacy = OncologyAnalyzer.FitPurityPloidy(OncologyAnalyzer.SegmentAlleleSpecificAspcf(hetLoci, 70.0));
        var germline = OncologyAnalyzer.FitPurityPloidyFromAspcf(
            OncologyAnalyzer.SegmentAlleleSpecificAspcf(hetLoci, hetLoci.Select(_ => true).ToList(), 70.0));

        Assert.Multiple(() =>
        {
            Assert.That((germline.Purity, germline.Psi), Is.EqualTo((legacy.Purity, legacy.Psi)));
            Assert.That(germline.GoodnessOfFit, Is.EqualTo(legacy.GoodnessOfFit));
            Assert.That(germline.Ploidy, Is.EqualTo(legacy.Ploidy));
            Assert.That(germline.Segments, Is.EqualTo(legacy.Segments));
        });
    }

    // C-ASCAT-G1 — invalid arguments.
    [Test]
    public void FitPurityPloidyFromAspcf_InvalidArguments_Throw()
    {
        var homOnly = OncologyAnalyzer.SegmentAlleleSpecificAspcf(
            Enumerable.Range(0, 20).Select(i => new OncologyAnalyzer.AlleleSpecificLocus("1", i * 1000L, 0.1 * (i % 3), 0.0)),
            Enumerable.Repeat(false, 20).ToList());
        var xOnly = OncologyAnalyzer.SegmentAlleleSpecificAspcf(
            Enumerable.Range(0, 20).Select(i => new OncologyAnalyzer.AlleleSpecificLocus("X", i * 1000L, 0.1 * (i % 3), 0.3)),
            Enumerable.Repeat(true, 20).ToList());
        var seg = Segment(G2);

        Assert.Multiple(() =>
        {
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.FitPurityPloidyFromAspcf(null!));
            Assert.Throws<ArgumentNullException>(() => OncologyAnalyzer.EvaluatePurityPloidyFromAspcf(null!, 0.5, 2.0));
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.FitPurityPloidyFromAspcf(homOnly),
                "No heterozygous probe ⇒ nothing to fit.");
            Assert.Throws<ArgumentException>(() => OncologyAnalyzer.FitPurityPloidyFromAspcf(xOnly),
                "Sex-chromosome probes are excluded from the fit.");
            Assert.Throws<ArgumentOutOfRangeException>(() => OncologyAnalyzer.FitPurityPloidyFromAspcf(seg, purityStep: 0.0));
            Assert.Throws<ArgumentOutOfRangeException>(() => OncologyAnalyzer.EvaluatePurityPloidyFromAspcf(seg, 1.5, 2.0));
        });
    }

    #endregion
}
