// CHROM-CENT-001 — Higher-order repeat (HOR) structure detection
// Evidence: docs/Evidence/CHROM-CENT-001-Evidence.md
// TestSpec: tests/TestSpecs/CHROM-CENT-001.md
// Sources:
//   HOR definition + identities: McNulty SM, Sullivan BA (2018), "Alpha satellite DNA biology"
//     (Chromosome Res 26:115-138; PMC6121732): "A defined number of individual monomers … that are
//     50-70% identical in sequence are arranged tandemly to form a HOR unit"; "HOR within a given
//     array are 97-100% identical"; "HOR unit length is determined by where the next monomer shows
//     nearly total sequence identity to the first monomer in the HOR".
//   Inter-HOR <5% divergence: Rosandić et al. (2024, PMC11050224); Alkan et al. (2007).
//   Monomer 171 bp: Willard HF (1985); review PMC6121732.

using NUnit.Framework;
using Seqeron.Genomics.Chromosome;
using System;
using System.Linq;

namespace Seqeron.Genomics.Tests;

/// <summary>
/// Tests for the opt-in higher-order repeat (HOR) structure detection added to CHROM-CENT-001:
/// <see cref="ChromosomeAnalyzer.DetectHigherOrderRepeat"/>.
/// <para>
/// Construction strategy (so expected values are hand-derivable, not read back from the code): all
/// monomers share ONE fixed high-complexity (non-repetitive, 4-letter, no homopolymer runs ≥ 2)
/// background of length 171. A distinct monomer is made by overwriting a set of scattered positions,
/// each with a base GUARANTEED to differ from the background at that position. Because the background
/// is high-complexity and the only differences between two such monomers are isolated point
/// substitutions, the optimal global alignment is gapless, so the aligner's percent identity equals
/// the Hamming identity (171 − #differing positions)/171 × 100 exactly. HOR copies are built as EXACT
/// repeats of a unit, so inter-HOR identity is 100%.
/// </para>
/// </summary>
[TestFixture]
public class ChromosomeAnalyzer_HigherOrderRepeat_Tests
{
    private const int MonomerLength = 171; // ChromosomeAnalyzer.AlphaSatelliteMonomerLength

    // A fixed, high-complexity 171-base background shared by every test monomer. Generated by a
    // deterministic LCG that never repeats a base twice in a row, so it has no homopolymer runs and no
    // short tandem periodicity for the aligner to exploit with gaps.
    private static readonly char[] Background = BuildBackground();

    private static char[] BuildBackground()
    {
        const char no = '\0';
        var bases = new[] { 'A', 'C', 'G', 'T' };
        var chars = new char[MonomerLength];
        long state = 123456789L; // fixed seed → deterministic fixture
        char prev = no;
        for (int i = 0; i < MonomerLength; i++)
        {
            state = (1103515245L * state + 12345L) & 0x7fffffff; // standard LCG
            char b = bases[(int)(state % 4)];
            if (b == prev) b = bases[(int)((state + 1) % 4)]; // forbid runs of length ≥ 2
            chars[i] = b;
            prev = b;
        }
        return chars;
    }

    /// <summary>
    /// Builds a 171-bp monomer = the shared background with the given positions overwritten by a base
    /// guaranteed different from the background there (cyclic A→C→G→T→A successor of the background
    /// base). Differences between two such monomers are therefore isolated point substitutions.
    /// </summary>
    private static string Monomer(int[] substitutedPositions)
    {
        var chars = (char[])Background.Clone();
        foreach (int p in substitutedPositions)
            chars[p] = NextBase(Background[p]);
        return new string(chars);
    }

    private static char NextBase(char b) => b switch
    {
        'A' => 'C', 'C' => 'G', 'G' => 'T', _ => 'A'
    };

    /// <summary>Scattered positions spaced 2 apart starting at <paramref name="start"/>.</summary>
    private static int[] Scattered(int start, int count) =>
        Enumerable.Range(0, count).Select(k => start + 2 * k).ToArray();

    /// <summary>
    /// Exact gapless percent identity of two background-derived monomers. Two monomers differ at a
    /// position iff exactly one of them substituted it (the substituted base differs from the
    /// background, and the two substitution sets only ever use the SAME successor base at a shared
    /// position, so shared substituted positions still match). Hence #differing = |A △ B| and
    /// identity = (171 − |A △ B|)/171 × 100.
    /// </summary>
    private static double ExactIdentity(int[] subsA, int[] subsB)
    {
        int symmetricDiff = subsA.Except(subsB).Count() + subsB.Except(subsA).Count();
        return (MonomerLength - symmetricDiff) / (double)MonomerLength * 100.0;
    }

    private static string Concat(params string[] parts) => string.Concat(parts);

    // Three distinct monomer "flavours" A, B, C with pairwise-disjoint scattered substitution sets, so
    // every distinct pair has the maximal symmetric difference 2×60 = 120 ⇒ identity (171−120)/171 =
    // 51/171 ≈ 29.8%? No — we choose 36 substitutions per flavour, disjoint ⇒ symdiff 72 ⇒
    // (171−72)/171 = 99/171 ≈ 57.9%, squarely in the 50-70% intra-HOR band (PMC6121732).
    private static readonly int[] SubsA = Scattered(0, 36);   // even positions 0..70
    private static readonly int[] SubsB = Scattered(1, 36);   // odd positions 1..71  (disjoint from A)
    private static readonly int[] SubsC = Scattered(72, 36);  // even positions 72..142 (disjoint from A,B)

    #region DetectHigherOrderRepeat — canonical

    [Test]
    public void DetectHigherOrderRepeat_ThreeMonomerUnitRepeatedFiveTimes_DetectsPeriod3CopyNumber5()
    {
        // M-HOR-1: A 3-monomer HOR unit (A,B,C distinct, ≈57.9% mutually identical) tandemly repeated
        // 5× with EXACT inter-HOR copies. Expected, hand-derived from the construction:
        //   - HOR period (monomers/unit) = 3 (smallest k with k-periodic monomers ≥95% identical; here
        //     k=3 gives 100%, while k=1,2 compare DISTINCT monomers ≈57.9% ⇒ rejected)
        //   - HOR copy number = ⌊15 / 3⌋ = 5;  HOR unit length = 3 × 171 = 513 bp;  Monomer count = 15
        //   - Mean inter-HOR identity = 100.0% (copies are exact)
        //   - Mean intra-HOR identity ≈ 57.9% (in 50-70 band) and < inter-HOR
        Assert.That(ExactIdentity(SubsA, SubsB), Is.GreaterThan(50.0).And.LessThan(70.0), "fixture A↔B in band");
        Assert.That(ExactIdentity(SubsA, SubsC), Is.GreaterThan(50.0).And.LessThan(70.0), "fixture A↔C in band");
        Assert.That(ExactIdentity(SubsB, SubsC), Is.GreaterThan(50.0).And.LessThan(70.0), "fixture B↔C in band");

        string a = Monomer(SubsA), b = Monomer(SubsB), c = Monomer(SubsC);
        string unit = Concat(a, b, c);
        string array = Concat(unit, unit, unit, unit, unit); // 5 exact HOR copies, 15 monomers, 2565 bp
        Assert.That(array.Length, Is.EqualTo(2565), "fixture sanity: 15 × 171 bp");

        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat(array);

        Assert.Multiple(() =>
        {
            Assert.That(result.HasHigherOrderStructure, Is.True,
                "A 3-monomer unit repeated 5× is a higher-order repeat");
            Assert.That(result.MonomersPerUnit, Is.EqualTo(3),
                "Smallest period with ≥95% k-periodic identity is 3 (k=1,2 compare distinct monomers ≈57.9%)");
            Assert.That(result.HorCopyNumber, Is.EqualTo(5),
                "15 monomers / period 3 = 5 complete HOR copies");
            Assert.That(result.HorUnitLengthBp, Is.EqualTo(513),
                "HOR unit length = 3 monomers × 171 bp");
            Assert.That(result.MonomerCount, Is.EqualTo(15),
                "2565 bp / 171 bp = 15 monomers");
            Assert.That(result.MeanInterHorIdentity, Is.EqualTo(100.0).Within(1e-9),
                "Inter-HOR copies are exact ⇒ 100% identity");
            Assert.That(result.MeanIntraHorIdentity, Is.GreaterThan(50.0).And.LessThan(70.0),
                "Distinct monomers within a unit are 50-70% identical (PMC6121732)");
            Assert.That(result.MeanInterHorIdentity, Is.GreaterThan(result.MeanIntraHorIdentity),
                "Hallmark of HOR organisation: inter-HOR ≫ intra-HOR identity");
        });
    }

    [Test]
    public void DetectHigherOrderRepeat_ThreeMonomerUnit_MeanIntraHorIdentityIsExact()
    {
        // M-HOR-2: Mean intra-HOR identity = mean of the three exact pairwise identities, each derived
        // from the substitution sets (gapless alignment over a high-complexity background).
        string a = Monomer(SubsA), b = Monomer(SubsB), c = Monomer(SubsC);
        string array = Concat(a, b, c, a, b, c, a, b, c, a, b, c, a, b, c);

        double expectedIntra =
            (ExactIdentity(SubsA, SubsB) + ExactIdentity(SubsA, SubsC) + ExactIdentity(SubsB, SubsC)) / 3.0;

        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat(array);

        Assert.That(result.MeanIntraHorIdentity, Is.EqualTo(expectedIntra).Within(1e-9),
            "Mean intra-HOR identity is the mean of the three exact pairwise monomer identities (≈57.9%)");
    }

    [Test]
    public void DetectHigherOrderRepeat_MonomericArrayNoHor_ReportsPeriod1NoStructure()
    {
        // M-HOR-3: A purely MONOMERIC array — 12 distinct monomers, no two ≥95% identical and no
        // periodicity — has no HOR organisation. Each monomer substitutes an INDEPENDENT pseudo-random
        // ~half of the positions (per-monomer fixed seed), so any two monomers differ at ≈ half their
        // positions ⇒ ≈ 50% pairwise identity, far below the 95% inter-HOR bar. The fixture is
        // self-validating: it first asserts every pair is < 95% identical, so no spurious period exists.
        var subSets = new int[12][];
        for (int m = 0; m < 12; m++)
        {
            var rng = new Random(1000 + m); // fixed per-monomer seed ⇒ deterministic
            subSets[m] = Enumerable.Range(0, MonomerLength).Where(_ => rng.Next(2) == 0).ToArray();
        }
        for (int i = 0; i < 12; i++)
            for (int j = i + 1; j < 12; j++)
                Assert.That(ExactIdentity(subSets[i], subSets[j]), Is.LessThan(95.0),
                    $"fixture: monomers {i},{j} must be < 95% identical so no HOR period exists");

        var monomers = subSets.Select(Monomer).ToArray();
        string array = string.Concat(monomers);
        Assert.That(array.Length, Is.EqualTo(12 * 171), "fixture sanity: 12 monomers");

        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat(array);

        Assert.Multiple(() =>
        {
            Assert.That(result.HasHigherOrderStructure, Is.False,
                "No two monomers are ≥95% identical ⇒ no HOR organisation");
            Assert.That(result.MonomersPerUnit, Is.EqualTo(1),
                "No multi-monomer HOR ⇒ period reported as 1");
            Assert.That(result.HorCopyNumber, Is.EqualTo(12),
                "With period 1 every monomer is its own unit ⇒ copy number = monomer count");
            Assert.That(result.MonomerCount, Is.EqualTo(12));
            Assert.That(result.MeanInterHorIdentity, Is.NaN,
                "No HOR period ⇒ inter-HOR identity is undefined (NaN)");
        });
    }

    [Test]
    public void DetectHigherOrderRepeat_HomogeneousSingleMonomerArray_ReportsPeriod1NotHor()
    {
        // M-HOR-4: A homogeneous repeat of ONE monomer (every copy identical) is a single-monomer
        // (1-mer) array, NOT a multi-monomer HOR. The smallest qualifying period is k=1 (adjacent
        // monomers are 100% identical), so MonomersPerUnit = 1 and HasHigherOrderStructure = false.
        string m = Monomer(SubsA);
        string array = string.Concat(Enumerable.Repeat(m, 8)); // 8 identical monomers

        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat(array);

        Assert.Multiple(() =>
        {
            Assert.That(result.MonomersPerUnit, Is.EqualTo(1),
                "Adjacent monomers are identical ⇒ smallest high-identity period is 1");
            Assert.That(result.HasHigherOrderStructure, Is.False,
                "A 1-monomer homogeneous repeat is not a multi-monomer HOR");
            Assert.That(result.HorCopyNumber, Is.EqualTo(8));
            Assert.That(result.MeanInterHorIdentity, Is.EqualTo(100.0).Within(1e-9),
                "All copies identical ⇒ 100% k=1 periodic identity");
        });
    }

    [Test]
    public void DetectHigherOrderRepeat_TwoMonomerUnit_DetectsPeriod2()
    {
        // M-HOR-5: A 2-monomer HOR (dimeric) repeated 6× ⇒ period 2, copy number 6, unit length 342.
        // A and B are distinct (≈57.9% identical, < 95% ⇒ k=1 rejected); copies are exact (100%).
        string a = Monomer(SubsA), b = Monomer(SubsB);
        string unit = Concat(a, b);
        string array = string.Concat(Enumerable.Repeat(unit, 6)); // 12 monomers

        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat(array);

        Assert.Multiple(() =>
        {
            Assert.That(result.HasHigherOrderStructure, Is.True);
            Assert.That(result.MonomersPerUnit, Is.EqualTo(2), "Dimeric HOR ⇒ period 2");
            Assert.That(result.HorCopyNumber, Is.EqualTo(6), "12 monomers / 2 = 6 copies");
            Assert.That(result.HorUnitLengthBp, Is.EqualTo(342), "2 × 171 bp");
            Assert.That(result.MeanInterHorIdentity, Is.EqualTo(100.0).Within(1e-9));
            Assert.That(result.MeanInterHorIdentity, Is.GreaterThan(result.MeanIntraHorIdentity));
        });
    }

    #endregion

    #region DetectHigherOrderRepeat — edge cases

    [Test]
    public void DetectHigherOrderRepeat_EmptySequence_ReturnsNoStructure()
    {
        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat("");

        Assert.Multiple(() =>
        {
            Assert.That(result.HasHigherOrderStructure, Is.False);
            Assert.That(result.MonomersPerUnit, Is.EqualTo(1));
            Assert.That(result.MonomerCount, Is.EqualTo(0));
            Assert.That(result.HorCopyNumber, Is.EqualTo(0));
            Assert.That(result.MeanInterHorIdentity, Is.NaN);
            Assert.That(result.MeanIntraHorIdentity, Is.NaN);
        });
    }

    [Test]
    public void DetectHigherOrderRepeat_NullSequence_ReturnsNoStructure()
    {
        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat(null!);

        Assert.Multiple(() =>
        {
            Assert.That(result.HasHigherOrderStructure, Is.False);
            Assert.That(result.MonomerCount, Is.EqualTo(0));
        });
    }

    [Test]
    public void DetectHigherOrderRepeat_FewerThanTwoMonomers_ReturnsNoStructure()
    {
        // One monomer (171 bp) cannot exhibit any periodicity.
        string oneMonomer = Monomer(SubsA);

        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat(oneMonomer);

        Assert.Multiple(() =>
        {
            Assert.That(result.HasHigherOrderStructure, Is.False);
            Assert.That(result.MonomersPerUnit, Is.EqualTo(1));
            Assert.That(result.MonomerCount, Is.EqualTo(1));
        });
    }

    [Test]
    public void DetectHigherOrderRepeat_TrailingPartialMonomer_IsIgnored()
    {
        // M-HOR-EDGE: A 3-monomer unit ×5 plus a 50-bp partial trailing monomer is split into 15 full
        // monomers; the partial tail is dropped. Period and copy number are unchanged from M-HOR-1.
        string a = Monomer(SubsA), b = Monomer(SubsB), c = Monomer(SubsC);
        string unit = Concat(a, b, c);
        string array = string.Concat(Enumerable.Repeat(unit, 5)) + new string('A', 50);

        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat(array);

        Assert.Multiple(() =>
        {
            Assert.That(result.MonomerCount, Is.EqualTo(15), "Trailing 50-bp partial monomer is ignored");
            Assert.That(result.MonomersPerUnit, Is.EqualTo(3));
            Assert.That(result.HorCopyNumber, Is.EqualTo(5));
        });
    }

    [Test]
    public void DetectHigherOrderRepeat_NonAcgtTrailingPartialMonomer_IsIgnored()
    {
        // M-HOR-NONACGT: A 3-monomer unit ×5 followed by an 80-bp run of non-ACGT 'N' bases. The N run
        // is shorter than one 171-bp monomer, so it forms a trailing partial monomer that is dropped by
        // the floor split (Length/monomerLength). Period, copy number and the identities are therefore
        // identical to the clean M-HOR-1 array — the non-ACGT tail cannot affect a HOR built only from
        // the 15 full monomers preceding it. (Sequences are not required to be pure ACGT; the aligner
        // simply treats N as a non-matching residue, and here it never reaches a full monomer.)
        string a = Monomer(SubsA), b = Monomer(SubsB), c = Monomer(SubsC);
        string unit = Concat(a, b, c);
        string array = string.Concat(Enumerable.Repeat(unit, 5)) + new string('N', 80);

        var result = ChromosomeAnalyzer.DetectHigherOrderRepeat(array);

        Assert.Multiple(() =>
        {
            Assert.That(result.MonomerCount, Is.EqualTo(15),
                "2645 bp / 171 bp = 15 full monomers; the 80-bp non-ACGT tail is a dropped partial monomer");
            Assert.That(result.MonomersPerUnit, Is.EqualTo(3), "Period unchanged by the ignored N tail");
            Assert.That(result.HorCopyNumber, Is.EqualTo(5));
            Assert.That(result.HasHigherOrderStructure, Is.True);
            Assert.That(result.MeanInterHorIdentity, Is.EqualTo(100.0).Within(1e-9),
                "The 15 full monomers are exact HOR copies ⇒ 100% inter-HOR identity");
        });
    }

    [Test]
    public void DetectHigherOrderRepeat_InvalidMonomerLength_Throws()
    {
        Assert.Throws<ArgumentOutOfRangeException>(
            () => ChromosomeAnalyzer.DetectHigherOrderRepeat("ACGTACGT", monomerLength: 0));
    }

    [Test]
    public void DetectHigherOrderRepeat_MixedCaseInput_MatchesUppercase()
    {
        string a = Monomer(SubsA), b = Monomer(SubsB), c = Monomer(SubsC);
        string unit = Concat(a, b, c);
        string array = string.Concat(Enumerable.Repeat(unit, 5));

        var upper = ChromosomeAnalyzer.DetectHigherOrderRepeat(array);
        var lower = ChromosomeAnalyzer.DetectHigherOrderRepeat(array.ToLowerInvariant());

        Assert.Multiple(() =>
        {
            Assert.That(lower.MonomersPerUnit, Is.EqualTo(upper.MonomersPerUnit));
            Assert.That(lower.HorCopyNumber, Is.EqualTo(upper.HorCopyNumber));
            Assert.That(lower.MeanInterHorIdentity, Is.EqualTo(upper.MeanInterHorIdentity).Within(1e-9));
            Assert.That(lower.MeanIntraHorIdentity, Is.EqualTo(upper.MeanIntraHorIdentity).Within(1e-9));
        });
    }

    #endregion
}
