using Seqeron.Mcp.Annotation.Tools;
using Seqeron.Mcp.Tests.Contracts;
using NUnit.Framework;

namespace Seqeron.Mcp.Annotation.Tests;

/// <summary>
/// Pins the Seqeron.Mcp.Annotation server's public MCP tool surface. Assertions live in
/// <see cref="ToolRegistrationContractTestsBase"/>; this fixture supplies the tool class and the
/// documented tool-name set.
/// </summary>
[TestFixture]
public sealed class ToolRegistrationContractTests : ToolRegistrationContractTestsBase
{
    protected override Type ToolsType => typeof(AnnotationTools);

    protected override string[] ExpectedToolNames { get; } =
    {
        "align_mirna_to_target",
        "analyze_target_context",
        "annotate_histone_modifications",
        "annotate_regulatory_elements",
        "annotate_svs",
        "annotate_variant_on_transcripts",
        "annotate_variants",
        "assemble_breakpoint_sequence",
        "build_coexpression_network",
        "calculate_conservation",
        "calculate_tpm",
        "call_variants",
        "call_variants_from_alignment",
        "can_pair",
        "classify_mutation",
        "classify_variant",
        "cluster_discordant_pairs",
        "cluster_genes_by_expression",
        "cluster_split_reads",
        "coding_potential",
        "codon_usage",
        "compare_seed_regions",
        "cpg_observed_expected",
        "create_mirna",
        "detect_alternative_splicing",
        "detect_differential_splicing",
        "detect_isoform_switching",
        "differential_expression",
        "enrichment_score",
        "epigenetic_age",
        "filter_svs",
        "find_acceptor_sites",
        "find_accessible_regions",
        "find_branch_points",
        "find_conserved_elements",
        "find_cpg_islands",
        "find_cpg_sites",
        "find_deletions",
        "find_discordant_pairs",
        "find_dmrs",
        "find_dominant_isoforms",
        "find_donor_sites",
        "find_indels",
        "find_insertions",
        "find_methylation_sites",
        "find_microhomology",
        "find_mirna_target_sites",
        "find_orfs",
        "find_pre_mirna_hairpins",
        "find_promoter_motifs",
        "find_repetitive_elements",
        "find_retained_intron_candidates",
        "find_ribosome_binding_sites",
        "find_similar_mirnas",
        "find_skipped_exon_events",
        "find_snps",
        "find_snps_direct",
        "find_split_reads",
        "format_vcf_info",
        "generate_seed_variants",
        "genotype_sv",
        "group_by_seed_family",
        "identify_cnvs",
        "impact_level",
        "is_within_coding_region",
        "is_wobble_pair",
        "log2_transform",
        "longest_orfs_per_frame",
        "maxent_score",
        "merge_overlapping_svs",
        "methylation_from_bisulfite",
        "methylation_profile",
        "mirna_seed_sequence",
        "normalize_variant",
        "over_representation_analysis",
        "parse_gff3",
        "parse_vcf_variant",
        "pearson_correlation",
        "perform_pca",
        "predict_chromatin_state",
        "predict_gene_structure",
        "predict_genes",
        "predict_imprinted_genes",
        "predict_introns",
        "predict_pathogenicity",
        "predict_tf_binding_change",
        "predict_variant_effect",
        "quantile_normalize",
        "rna_reverse_complement",
        "rnaseq_quality_metrics",
        "segment_copy_number",
        "simulate_bisulfite_conversion",
        "site_accessibility",
        "titv_ratio",
        "to_gff3",
        "variant_statistics",
        "variants_to_vcf",
    };
}
