using System.Text.Json.Serialization;
using Seqeron.Mcp.Annotation.Tools;

namespace Seqeron.Mcp.Annotation.Json;

/// <summary>
/// Source-generated JSON serialization context aggregator for the
/// Seqeron.Mcp.Annotation server. Tool authors add
/// [JsonSerializable(typeof(...))] entries here as DTOs are introduced.
/// </summary>
[JsonSourceGenerationOptions(WriteIndented = false)]
[JsonSerializable(typeof(string))]
// Shared DTOs
[JsonSerializable(typeof(OrfDto))]
[JsonSerializable(typeof(LongestOrfFrame))]
[JsonSerializable(typeof(GeneAnnotationDto))]
[JsonSerializable(typeof(GenomicFeatureDto))]
[JsonSerializable(typeof(RibosomeBindingSite))]
[JsonSerializable(typeof(PromoterMotif))]
[JsonSerializable(typeof(RepetitiveElement))]
// Tool input collections
[JsonSerializable(typeof(IReadOnlyList<GeneAnnotationDto>))]
[JsonSerializable(typeof(List<GeneAnnotationDto>))]
[JsonSerializable(typeof(GeneAnnotationDto[]))]
// Tool results
[JsonSerializable(typeof(FindOrfsResult))]
[JsonSerializable(typeof(LongestOrfsPerFrameResult))]
[JsonSerializable(typeof(FindRibosomeBindingSitesResult))]
[JsonSerializable(typeof(PredictGenesResult))]
[JsonSerializable(typeof(ParseGff3Result))]
[JsonSerializable(typeof(ToGff3Result))]
[JsonSerializable(typeof(FindPromoterMotifsResult))]
[JsonSerializable(typeof(CodingPotentialResult))]
[JsonSerializable(typeof(FindRepetitiveElementsResult))]
[JsonSerializable(typeof(CodonUsageResult))]
// VariantCaller — shared DTOs
[JsonSerializable(typeof(VariantDto))]
[JsonSerializable(typeof(AnnotatedVariantDto))]
[JsonSerializable(typeof(VariantStatisticsDto))]
// VariantCaller — input collections
[JsonSerializable(typeof(IReadOnlyList<VariantDto>))]
[JsonSerializable(typeof(List<VariantDto>))]
[JsonSerializable(typeof(VariantDto[]))]
// VariantCaller — tool results
[JsonSerializable(typeof(CallVariantsResult))]
[JsonSerializable(typeof(ClassifyMutationResult))]
[JsonSerializable(typeof(TiTvRatioResult))]
[JsonSerializable(typeof(PredictVariantEffectResult))]
[JsonSerializable(typeof(AnnotateVariantsResult))]
[JsonSerializable(typeof(VariantsToVcfResult))]
// VariantAnnotator — shared DTOs
[JsonSerializable(typeof(AnnotatorVariantDto))]
[JsonSerializable(typeof(GenomicIntervalDto))]
[JsonSerializable(typeof(TranscriptDto))]
[JsonSerializable(typeof(VariantAnnotationDto))]
[JsonSerializable(typeof(PathogenicityPredictionDto))]
[JsonSerializable(typeof(ConservationPositionInputDto))]
[JsonSerializable(typeof(ConservationScoreDto))]
[JsonSerializable(typeof(ConservedElementDto))]
[JsonSerializable(typeof(RegulatoryRegionInputDto))]
[JsonSerializable(typeof(RegulatoryAnnotationDto))]
[JsonSerializable(typeof(TfMotifInputDto))]
[JsonSerializable(typeof(TfBindingChangeDto))]
// VariantAnnotator — input collections
[JsonSerializable(typeof(IReadOnlyList<TranscriptDto>))]
[JsonSerializable(typeof(List<TranscriptDto>))]
[JsonSerializable(typeof(TranscriptDto[]))]
[JsonSerializable(typeof(IReadOnlyList<GenomicIntervalDto>))]
[JsonSerializable(typeof(List<GenomicIntervalDto>))]
[JsonSerializable(typeof(GenomicIntervalDto[]))]
[JsonSerializable(typeof(IReadOnlyList<ConservationPositionInputDto>))]
[JsonSerializable(typeof(List<ConservationPositionInputDto>))]
[JsonSerializable(typeof(ConservationPositionInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<ConservationScoreDto>))]
[JsonSerializable(typeof(List<ConservationScoreDto>))]
[JsonSerializable(typeof(ConservationScoreDto[]))]
[JsonSerializable(typeof(IReadOnlyList<RegulatoryRegionInputDto>))]
[JsonSerializable(typeof(List<RegulatoryRegionInputDto>))]
[JsonSerializable(typeof(RegulatoryRegionInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<TfMotifInputDto>))]
[JsonSerializable(typeof(List<TfMotifInputDto>))]
[JsonSerializable(typeof(TfMotifInputDto[]))]
[JsonSerializable(typeof(Dictionary<string, double>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(string[]))]
// VariantAnnotator — tool results
[JsonSerializable(typeof(ClassifyVariantResult))]
[JsonSerializable(typeof(AnnotatorVariantResult))]
[JsonSerializable(typeof(AnnotateVariantOnTranscriptsResult))]
[JsonSerializable(typeof(ImpactLevelResult))]
[JsonSerializable(typeof(PredictPathogenicityResult))]
[JsonSerializable(typeof(CalculateConservationResult))]
[JsonSerializable(typeof(FindConservedElementsResult))]
[JsonSerializable(typeof(AnnotateRegulatoryElementsResult))]
[JsonSerializable(typeof(PredictTfBindingChangeResult))]
[JsonSerializable(typeof(FormatVcfInfoResult))]
// EpigeneticsAnalyzer — shared DTOs
[JsonSerializable(typeof(MethylationSiteDto))]
[JsonSerializable(typeof(MethylationByPositionDto))]
[JsonSerializable(typeof(MethylationProfileDto))]
[JsonSerializable(typeof(CpGIslandDto))]
[JsonSerializable(typeof(BisulfiteReadDto))]
[JsonSerializable(typeof(DmrDto))]
[JsonSerializable(typeof(HistoneModificationInputDto))]
[JsonSerializable(typeof(HistoneModificationAnnotationDto))]
[JsonSerializable(typeof(AccessibilitySignalDto))]
[JsonSerializable(typeof(AccessibilityRegionDto))]
[JsonSerializable(typeof(ImprintedGeneInputDto))]
[JsonSerializable(typeof(ImprintedGeneDto))]
// EpigeneticsAnalyzer — input collections
[JsonSerializable(typeof(IReadOnlyList<int>))]
[JsonSerializable(typeof(List<int>))]
[JsonSerializable(typeof(int[]))]
[JsonSerializable(typeof(IReadOnlyList<MethylationSiteDto>))]
[JsonSerializable(typeof(List<MethylationSiteDto>))]
[JsonSerializable(typeof(MethylationSiteDto[]))]
[JsonSerializable(typeof(IReadOnlyList<BisulfiteReadDto>))]
[JsonSerializable(typeof(List<BisulfiteReadDto>))]
[JsonSerializable(typeof(BisulfiteReadDto[]))]
[JsonSerializable(typeof(IReadOnlyList<HistoneModificationInputDto>))]
[JsonSerializable(typeof(List<HistoneModificationInputDto>))]
[JsonSerializable(typeof(HistoneModificationInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<AccessibilitySignalDto>))]
[JsonSerializable(typeof(List<AccessibilitySignalDto>))]
[JsonSerializable(typeof(AccessibilitySignalDto[]))]
[JsonSerializable(typeof(IReadOnlyList<ImprintedGeneInputDto>))]
[JsonSerializable(typeof(List<ImprintedGeneInputDto>))]
[JsonSerializable(typeof(ImprintedGeneInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<MethylationByPositionDto>))]
[JsonSerializable(typeof(List<MethylationByPositionDto>))]
// EpigeneticsAnalyzer — tool results
[JsonSerializable(typeof(FindCpGSitesResult))]
[JsonSerializable(typeof(FindMethylationSitesResult))]
[JsonSerializable(typeof(CpGObservedExpectedResult))]
[JsonSerializable(typeof(FindCpGIslandsResult))]
[JsonSerializable(typeof(SimulateBisulfiteConversionResult))]
[JsonSerializable(typeof(MethylationProfileDto))]
[JsonSerializable(typeof(FindDmrsResult))]
[JsonSerializable(typeof(PredictChromatinStateResult))]
[JsonSerializable(typeof(AnnotateHistoneModificationsResult))]
[JsonSerializable(typeof(FindAccessibleRegionsResult))]
[JsonSerializable(typeof(PredictImprintedGenesResult))]
[JsonSerializable(typeof(EpigeneticAgeResult))]
// MiRnaAnalyzer — shared DTOs
[JsonSerializable(typeof(MiRnaDto))]
[JsonSerializable(typeof(TargetSiteDto))]
[JsonSerializable(typeof(PreMiRnaHairpinDto))]
[JsonSerializable(typeof(SeedFamilyDto))]
// MiRnaAnalyzer — input collections
[JsonSerializable(typeof(IReadOnlyList<MiRnaDto>))]
[JsonSerializable(typeof(List<MiRnaDto>))]
[JsonSerializable(typeof(MiRnaDto[]))]
[JsonSerializable(typeof(IReadOnlyList<TargetSiteDto>))]
[JsonSerializable(typeof(List<TargetSiteDto>))]
[JsonSerializable(typeof(TargetSiteDto[]))]
[JsonSerializable(typeof(IReadOnlyList<PreMiRnaHairpinDto>))]
[JsonSerializable(typeof(List<PreMiRnaHairpinDto>))]
[JsonSerializable(typeof(PreMiRnaHairpinDto[]))]
[JsonSerializable(typeof(IReadOnlyList<SeedFamilyDto>))]
[JsonSerializable(typeof(List<SeedFamilyDto>))]
[JsonSerializable(typeof(SeedFamilyDto[]))]
// MiRnaAnalyzer — tool results
[JsonSerializable(typeof(MiRnaSeedResult))]
[JsonSerializable(typeof(CreateMiRnaResult))]
[JsonSerializable(typeof(CompareSeedRegionsResult))]
[JsonSerializable(typeof(FindMiRnaTargetSitesResult))]
[JsonSerializable(typeof(RnaReverseComplementResult))]
[JsonSerializable(typeof(CanPairResult))]
[JsonSerializable(typeof(IsWobblePairResult))]
[JsonSerializable(typeof(AlignMiRnaToTargetResult))]
[JsonSerializable(typeof(FindPreMiRnaHairpinsResult))]
[JsonSerializable(typeof(AnalyzeTargetContextResult))]
[JsonSerializable(typeof(SiteAccessibilityResult))]
[JsonSerializable(typeof(GroupBySeedFamilyResult))]
[JsonSerializable(typeof(FindSimilarMiRnasResult))]
[JsonSerializable(typeof(GenerateSeedVariantsResult))]
// SpliceSitePredictor — shared DTOs
[JsonSerializable(typeof(SpliceSiteDto))]
[JsonSerializable(typeof(IntronDto))]
[JsonSerializable(typeof(ExonDto))]
[JsonSerializable(typeof(AlternativeSplicingEventDto))]
// SpliceSitePredictor — collections
[JsonSerializable(typeof(IReadOnlyList<SpliceSiteDto>))]
[JsonSerializable(typeof(List<SpliceSiteDto>))]
[JsonSerializable(typeof(SpliceSiteDto[]))]
[JsonSerializable(typeof(IReadOnlyList<IntronDto>))]
[JsonSerializable(typeof(List<IntronDto>))]
[JsonSerializable(typeof(IntronDto[]))]
[JsonSerializable(typeof(IReadOnlyList<ExonDto>))]
[JsonSerializable(typeof(List<ExonDto>))]
[JsonSerializable(typeof(ExonDto[]))]
[JsonSerializable(typeof(IReadOnlyList<AlternativeSplicingEventDto>))]
[JsonSerializable(typeof(List<AlternativeSplicingEventDto>))]
[JsonSerializable(typeof(AlternativeSplicingEventDto[]))]
// SpliceSitePredictor — tool results
[JsonSerializable(typeof(FindDonorSitesResult))]
[JsonSerializable(typeof(FindAcceptorSitesResult))]
[JsonSerializable(typeof(FindBranchPointsResult))]
[JsonSerializable(typeof(PredictIntronsResult))]
[JsonSerializable(typeof(PredictGeneStructureResult))]
[JsonSerializable(typeof(DetectAlternativeSplicingResult))]
[JsonSerializable(typeof(FindRetainedIntronCandidatesResult))]
[JsonSerializable(typeof(MaxEntScoreResult))]
[JsonSerializable(typeof(IsWithinCodingRegionResult))]
// StructuralVariantAnalyzer — shared DTOs
[JsonSerializable(typeof(StructuralVariantDto))]
[JsonSerializable(typeof(BreakpointDto))]
[JsonSerializable(typeof(CopyNumberSegmentDto))]
[JsonSerializable(typeof(ReadPairSignatureDto))]
[JsonSerializable(typeof(SplitReadDto))]
[JsonSerializable(typeof(SvAnnotationDto))]
// StructuralVariantAnalyzer — input DTOs
[JsonSerializable(typeof(ReadPairInputDto))]
[JsonSerializable(typeof(AlignmentInputDto))]
[JsonSerializable(typeof(CopyNumberProbeDto))]
[JsonSerializable(typeof(SvExonIntervalDto))]
[JsonSerializable(typeof(SvGeneInputDto))]
// StructuralVariantAnalyzer — input collections
[JsonSerializable(typeof(IReadOnlyList<ReadPairInputDto>))]
[JsonSerializable(typeof(List<ReadPairInputDto>))]
[JsonSerializable(typeof(ReadPairInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<ReadPairSignatureDto>))]
[JsonSerializable(typeof(List<ReadPairSignatureDto>))]
[JsonSerializable(typeof(ReadPairSignatureDto[]))]
[JsonSerializable(typeof(IReadOnlyList<AlignmentInputDto>))]
[JsonSerializable(typeof(List<AlignmentInputDto>))]
[JsonSerializable(typeof(AlignmentInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<SplitReadDto>))]
[JsonSerializable(typeof(List<SplitReadDto>))]
[JsonSerializable(typeof(SplitReadDto[]))]
[JsonSerializable(typeof(IReadOnlyList<CopyNumberProbeDto>))]
[JsonSerializable(typeof(List<CopyNumberProbeDto>))]
[JsonSerializable(typeof(CopyNumberProbeDto[]))]
[JsonSerializable(typeof(IReadOnlyList<CopyNumberSegmentDto>))]
[JsonSerializable(typeof(List<CopyNumberSegmentDto>))]
[JsonSerializable(typeof(CopyNumberSegmentDto[]))]
[JsonSerializable(typeof(IReadOnlyList<StructuralVariantDto>))]
[JsonSerializable(typeof(List<StructuralVariantDto>))]
[JsonSerializable(typeof(StructuralVariantDto[]))]
[JsonSerializable(typeof(IReadOnlyList<SvGeneInputDto>))]
[JsonSerializable(typeof(List<SvGeneInputDto>))]
[JsonSerializable(typeof(SvGeneInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<SvExonIntervalDto>))]
[JsonSerializable(typeof(List<SvExonIntervalDto>))]
[JsonSerializable(typeof(SvExonIntervalDto[]))]
// StructuralVariantAnalyzer — tool results
[JsonSerializable(typeof(FindDiscordantPairsResult))]
[JsonSerializable(typeof(ClusterDiscordantPairsResult))]
[JsonSerializable(typeof(FindSplitReadsResult))]
[JsonSerializable(typeof(ClusterSplitReadsResult))]
[JsonSerializable(typeof(SegmentCopyNumberResult))]
[JsonSerializable(typeof(IdentifyCnvsResult))]
[JsonSerializable(typeof(MergeOverlappingSvsResult))]
[JsonSerializable(typeof(FilterSvsResult))]
[JsonSerializable(typeof(AnnotateSvsResult))]
[JsonSerializable(typeof(GenotypeSvResult))]
[JsonSerializable(typeof(AssembleBreakpointSequenceResult))]
[JsonSerializable(typeof(FindMicrohomologyResult))]
// TranscriptomeAnalyzer — shared / input DTOs
[JsonSerializable(typeof(GeneCountInputDto))]
[JsonSerializable(typeof(GeneExpressionDto))]
[JsonSerializable(typeof(DiffExprInputDto))]
[JsonSerializable(typeof(DifferentialExpressionDto))]
[JsonSerializable(typeof(PathwayInputDto))]
[JsonSerializable(typeof(EnrichmentResultDto))]
[JsonSerializable(typeof(SkippedExonInputDto))]
[JsonSerializable(typeof(SplicingComparisonInputDto))]
[JsonSerializable(typeof(SplicingEventDto))]
[JsonSerializable(typeof(ExonRangeDto))]
[JsonSerializable(typeof(TranscriptIsoformDto))]
[JsonSerializable(typeof(DominantIsoformDto))]
[JsonSerializable(typeof(IsoformExpressionInputDto))]
[JsonSerializable(typeof(IsoformSwitchDto))]
[JsonSerializable(typeof(GeneProfileInputDto))]
[JsonSerializable(typeof(CoExpressionEdgeDto))]
[JsonSerializable(typeof(CoExpressionClusterDto))]
[JsonSerializable(typeof(SampleExpressionInputDto))]
[JsonSerializable(typeof(PcaPointDto))]
// TranscriptomeAnalyzer — input collections
[JsonSerializable(typeof(IReadOnlyList<GeneCountInputDto>))]
[JsonSerializable(typeof(List<GeneCountInputDto>))]
[JsonSerializable(typeof(GeneCountInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<DiffExprInputDto>))]
[JsonSerializable(typeof(List<DiffExprInputDto>))]
[JsonSerializable(typeof(DiffExprInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<PathwayInputDto>))]
[JsonSerializable(typeof(List<PathwayInputDto>))]
[JsonSerializable(typeof(PathwayInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<SkippedExonInputDto>))]
[JsonSerializable(typeof(List<SkippedExonInputDto>))]
[JsonSerializable(typeof(SkippedExonInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<SplicingComparisonInputDto>))]
[JsonSerializable(typeof(List<SplicingComparisonInputDto>))]
[JsonSerializable(typeof(SplicingComparisonInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<TranscriptIsoformDto>))]
[JsonSerializable(typeof(List<TranscriptIsoformDto>))]
[JsonSerializable(typeof(TranscriptIsoformDto[]))]
[JsonSerializable(typeof(IReadOnlyList<IsoformExpressionInputDto>))]
[JsonSerializable(typeof(List<IsoformExpressionInputDto>))]
[JsonSerializable(typeof(IsoformExpressionInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<GeneProfileInputDto>))]
[JsonSerializable(typeof(List<GeneProfileInputDto>))]
[JsonSerializable(typeof(GeneProfileInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<SampleExpressionInputDto>))]
[JsonSerializable(typeof(List<SampleExpressionInputDto>))]
[JsonSerializable(typeof(SampleExpressionInputDto[]))]
[JsonSerializable(typeof(IReadOnlyList<ExonRangeDto>))]
[JsonSerializable(typeof(List<ExonRangeDto>))]
[JsonSerializable(typeof(ExonRangeDto[]))]
[JsonSerializable(typeof(IReadOnlyList<double>))]
[JsonSerializable(typeof(List<double>))]
[JsonSerializable(typeof(double[]))]
[JsonSerializable(typeof(IReadOnlyList<IReadOnlyList<double>>))]
[JsonSerializable(typeof(List<List<double>>))]
[JsonSerializable(typeof(double[][]))]
// TranscriptomeAnalyzer — tool results
[JsonSerializable(typeof(CalculateTpmResult))]
[JsonSerializable(typeof(QuantileNormalizeResult))]
[JsonSerializable(typeof(Log2TransformResult))]
[JsonSerializable(typeof(DifferentialExpressionResult))]
[JsonSerializable(typeof(OverRepresentationAnalysisResult))]
[JsonSerializable(typeof(EnrichmentScoreResult))]
[JsonSerializable(typeof(FindSkippedExonEventsResult))]
[JsonSerializable(typeof(DetectDifferentialSplicingResult))]
[JsonSerializable(typeof(FindDominantIsoformsResult))]
[JsonSerializable(typeof(DetectIsoformSwitchingResult))]
[JsonSerializable(typeof(PearsonCorrelationResult))]
[JsonSerializable(typeof(BuildCoexpressionNetworkResult))]
[JsonSerializable(typeof(ClusterGenesByExpressionResult))]
[JsonSerializable(typeof(RnaseqQualityMetricsResult))]
[JsonSerializable(typeof(PerformPcaResult))]
public partial class AppJsonContext : JsonSerializerContext
{
}
