using Seqeron.Mcp.Analysis.Tools;
using Seqeron.Mcp.Tests.Contracts;
using NUnit.Framework;

namespace Seqeron.Mcp.Analysis.Tests;

/// <summary>
/// Pins the Seqeron.Mcp.Analysis server's public MCP tool surface. Assertions live in
/// <see cref="ToolRegistrationContractTestsBase"/>; this fixture supplies the tool class and the
/// documented tool-name set.
/// </summary>
[TestFixture]
public sealed class ToolRegistrationContractTests : ToolRegistrationContractTestsBase
{
    protected override Type ToolsType => typeof(AnalysisTools);

    protected override string[] ExpectedToolNames { get; } =
    {
        "analyze_gc_content",
        "analyze_kmers",
        "at_skew",
        "base_pair_type",
        "bulge_loop_energy",
        "calculate_ani",
        "can_pair",
        "codon_frequencies",
        "compare_genomes",
        "compression_ratio",
        "count_kmers",
        "count_kmers_both_strands",
        "create_pwm",
        "cumulative_gc_skew",
        "dangling_end_energy",
        "detect_pseudoknots",
        "detect_rearrangements",
        "dinucleotide_frequencies",
        "dinucleotide_ratios",
        "discover_motifs",
        "disorder_propensity",
        "dust_score",
        "entropy_profile",
        "find_clumps",
        "find_common_regions",
        "find_conserved_clusters",
        "find_degenerate_motif",
        "find_direct_repeats",
        "find_exact_motif",
        "find_inverted_repeats",
        "find_known_motifs",
        "find_low_complexity_regions",
        "find_microsatellites",
        "find_motif",
        "find_motif_by_pattern",
        "find_motif_by_prosite",
        "find_open_reading_frames",
        "find_orthologs",
        "find_palindromes",
        "find_protein_domains",
        "find_protein_low_complexity_regions",
        "find_protein_motifs",
        "find_reciprocal_best_hits",
        "find_regulatory_elements",
        "find_repeats",
        "find_rna_inverted_repeats",
        "find_shared_motifs",
        "find_stem_loops",
        "find_syntenic_blocks",
        "find_tandem_repeats",
        "flush_coaxial_stacking",
        "gc_content_profile",
        "gc_skew",
        "generate_all_kmers",
        "generate_consensus",
        "generate_dot_plot",
        "hairpin_loop_energy",
        "hydrophobicity_profile",
        "internal_loop_energy",
        "is_disorder_promoting",
        "kmer_distance",
        "kmer_frequencies",
        "kmer_positions",
        "kmer_spectrum",
        "kmers_with_min_count",
        "mask_low_complexity",
        "minimum_free_energy",
        "mismatch_coaxial_stacking",
        "most_frequent_kmers",
        "multibranch_loop_energy",
        "parse_dot_bracket",
        "predict_chou_fasman",
        "predict_coiled_coils",
        "predict_disorder",
        "predict_low_complexity_seg",
        "predict_morfs",
        "predict_replication_origin",
        "predict_rna_structure",
        "predict_signal_peptide",
        "predict_transmembrane_helices",
        "prosite_to_regex",
        "reversal_distance",
        "rna_complement_base",
        "scan_with_pwm",
        "stem_energy",
        "tandem_repeat_summary",
        "terminal_mismatch_energy",
        "unique_kmers",
        "validate_dot_bracket",
        "windowed_complexity",
        "windowed_gc_skew",
    };
}
